//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 非居民企业企业所得税核定征收申报按收入总额核定应纳税所得额明细信息
 *
 * <p>Java class for AsrzehdynsdesmxVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AsrzehdynsdesmxVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xmmc" type="{http://www.chinatax.gov.cn/dataspec/}xmmc" minOccurs="0"/>
 *         &lt;element name="xmDm" type="{http://www.chinatax.gov.cn/dataspec/}sdxmDm" minOccurs="0"/>
 *         &lt;element name="htzh" type="{http://www.chinatax.gov.cn/dataspec/}htzh" minOccurs="0"/>
 *         &lt;element name="zzjesre" type="{http://www.chinatax.gov.cn/dataspec/}je" minOccurs="0"/>
 *         &lt;element name="yfsbjesre" type="{http://www.chinatax.gov.cn/dataspec/}je" minOccurs="0"/>
 *         &lt;element name="yfsbjelrl" type="{http://www.chinatax.gov.cn/dataspec/}sl" minOccurs="0"/>
 *         &lt;element name="yfsbjeynssde" type="{http://www.chinatax.gov.cn/dataspec/}je" minOccurs="0"/>
 *         &lt;element name="bz" type="{http://www.chinatax.gov.cn/dataspec/}bz" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AsrzehdynsdesmxVO", propOrder = {
    "xmmc",
    "xmDm",
    "htzh",
    "zzjesre",
    "yfsbjesre",
    "yfsbjelrl",
    "yfsbjeynssde",
    "bz"
})
public class AsrzehdynsdesmxVO {

    protected String xmmc;
    protected String xmDm;
    protected String htzh;
    protected Double zzjesre;
    protected Double yfsbjesre;
    protected Double yfsbjelrl;
    protected Double yfsbjeynssde;
    protected String bz;

    /**
     * Gets the value of the xmmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getXmmc() {
        return xmmc;
    }

    /**
     * Sets the value of the xmmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setXmmc(String value) {
        this.xmmc = value;
    }

    /**
     * Gets the value of the xmDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getXmDm() {
        return xmDm;
    }

    /**
     * Sets the value of the xmDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setXmDm(String value) {
        this.xmDm = value;
    }

    /**
     * Gets the value of the htzh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHtzh() {
        return htzh;
    }

    /**
     * Sets the value of the htzh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHtzh(String value) {
        this.htzh = value;
    }

    /**
     * Gets the value of the zzjesre property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getZzjesre() {
        return zzjesre;
    }

    /**
     * Sets the value of the zzjesre property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setZzjesre(Double value) {
        this.zzjesre = value;
    }

    /**
     * Gets the value of the yfsbjesre property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getYfsbjesre() {
        return yfsbjesre;
    }

    /**
     * Sets the value of the yfsbjesre property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setYfsbjesre(Double value) {
        this.yfsbjesre = value;
    }

    /**
     * Gets the value of the yfsbjelrl property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getYfsbjelrl() {
        return yfsbjelrl;
    }

    /**
     * Sets the value of the yfsbjelrl property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setYfsbjelrl(Double value) {
        this.yfsbjelrl = value;
    }

    /**
     * Gets the value of the yfsbjeynssde property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getYfsbjeynssde() {
        return yfsbjeynssde;
    }

    /**
     * Sets the value of the yfsbjeynssde property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setYfsbjeynssde(Double value) {
        this.yfsbjeynssde = value;
    }

    /**
     * Gets the value of the bz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBz() {
        return bz;
    }

    /**
     * Sets the value of the bz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBz(String value) {
        this.bz = value;
    }

}
