//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 对外投资
 *
 * <p>Java class for DwtzGridlbVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DwtzGridlbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mxuuid" type="{http://www.chinatax.gov.cn/dataspec/}mxuuid"/>
 *         &lt;element name="btznsrmc" type="{http://www.chinatax.gov.cn/dataspec/}nsrmc" minOccurs="0"/>
 *         &lt;element name="nsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}nsrsbh" minOccurs="0"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh" minOccurs="0"/>
 *         &lt;element name="jjxz" type="{http://www.chinatax.gov.cn/dataspec/}hyDm" minOccurs="0"/>
 *         &lt;element name="tzbl" type="{http://www.chinatax.gov.cn/dataspec/}tzbl" minOccurs="0"/>
 *         &lt;element name="tzze" type="{http://www.chinatax.gov.cn/dataspec/}tzze" minOccurs="0"/>
 *         &lt;element name="zcdz" type="{http://www.chinatax.gov.cn/dataspec/}zcdz" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DwtzGridlbVO", propOrder = {
    "mxuuid",
    "btznsrmc",
    "nsrsbh",
    "djxh",
    "jjxz",
    "tzbl",
    "tzze",
    "zcdz"
})
public class DwtzGridlbVO {

    @XmlElement(required = true)
    protected String mxuuid;
    protected String btznsrmc;
    protected String nsrsbh;
    protected String djxh;
    protected String jjxz;
    protected Double tzbl;
    protected Double tzze;
    protected String zcdz;

    /**
     * Gets the value of the mxuuid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMxuuid() {
        return mxuuid;
    }

    /**
     * Sets the value of the mxuuid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMxuuid(String value) {
        this.mxuuid = value;
    }

    /**
     * Gets the value of the btznsrmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBtznsrmc() {
        return btznsrmc;
    }

    /**
     * Sets the value of the btznsrmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBtznsrmc(String value) {
        this.btznsrmc = value;
    }

    /**
     * Gets the value of the nsrsbh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNsrsbh() {
        return nsrsbh;
    }

    /**
     * Sets the value of the nsrsbh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNsrsbh(String value) {
        this.nsrsbh = value;
    }

    /**
     * Gets the value of the djxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the jjxz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getJjxz() {
        return jjxz;
    }

    /**
     * Sets the value of the jjxz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setJjxz(String value) {
        this.jjxz = value;
    }

    /**
     * Gets the value of the tzbl property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getTzbl() {
        return tzbl;
    }

    /**
     * Sets the value of the tzbl property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setTzbl(Double value) {
        this.tzbl = value;
    }

    /**
     * Gets the value of the tzze property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getTzze() {
        return tzze;
    }

    /**
     * Sets the value of the tzze property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setTzze(Double value) {
        this.tzze = value;
    }

    /**
     * Gets the value of the zcdz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZcdz() {
        return zcdz;
    }

    /**
     * Sets the value of the zcdz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZcdz(String value) {
        this.zcdz = value;
    }

}
