//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 增值税纳税申报表（小规模纳税人适用）附列资料（税额抵减情况表）
 *
 * <p>Java class for flzlsedjqkbGridlbVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="flzlsedjqkbGridlbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ewbhxh" type="{http://www.chinatax.gov.cn/dataspec/}ewbhxh"/>
 *         &lt;element name="djxm" type="{http://www.chinatax.gov.cn/dataspec/}djxm"/>
 *         &lt;element name="qcye" type="{http://www.chinatax.gov.cn/dataspec/}qcye"/>
 *         &lt;element name="bqfse" type="{http://www.chinatax.gov.cn/dataspec/}bqfse"/>
 *         &lt;element name="bqydjse" type="{http://www.chinatax.gov.cn/dataspec/}bqydjse"/>
 *         &lt;element name="bqsjdjse" type="{http://www.chinatax.gov.cn/dataspec/}bqsjdjse"/>
 *         &lt;element name="qmye" type="{http://www.chinatax.gov.cn/dataspec/}qmye"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flzlsedjqkbGridlbVO", propOrder = {
    "ewbhxh",
    "djxm",
    "qcye",
    "bqfse",
    "bqydjse",
    "bqsjdjse",
    "qmye"
})
public class FlzlsedjqkbGridlbVO {

    protected long ewbhxh;
    @XmlElement(required = true)
    protected String djxm;
    protected double qcye;
    protected double bqfse;
    protected double bqydjse;
    protected double bqsjdjse;
    protected double qmye;

    /**
     * Gets the value of the ewbhxh property.
     *
     */
    public long getEwbhxh() {
        return ewbhxh;
    }

    /**
     * Sets the value of the ewbhxh property.
     *
     */
    public void setEwbhxh(long value) {
        this.ewbhxh = value;
    }

    /**
     * Gets the value of the djxm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDjxm() {
        return djxm;
    }

    /**
     * Sets the value of the djxm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDjxm(String value) {
        this.djxm = value;
    }

    /**
     * Gets the value of the qcye property.
     *
     */
    public double getQcye() {
        return qcye;
    }

    /**
     * Sets the value of the qcye property.
     *
     */
    public void setQcye(double value) {
        this.qcye = value;
    }

    /**
     * Gets the value of the bqfse property.
     *
     */
    public double getBqfse() {
        return bqfse;
    }

    /**
     * Sets the value of the bqfse property.
     *
     */
    public void setBqfse(double value) {
        this.bqfse = value;
    }

    /**
     * Gets the value of the bqydjse property.
     *
     */
    public double getBqydjse() {
        return bqydjse;
    }

    /**
     * Sets the value of the bqydjse property.
     *
     */
    public void setBqydjse(double value) {
        this.bqydjse = value;
    }

    /**
     * Gets the value of the bqsjdjse property.
     *
     */
    public double getBqsjdjse() {
        return bqsjdjse;
    }

    /**
     * Sets the value of the bqsjdjse property.
     *
     */
    public void setBqsjdjse(double value) {
        this.bqsjdjse = value;
    }

    /**
     * Gets the value of the qmye property.
     *
     */
    public double getQmye() {
        return qmye;
    }

    /**
     * Sets the value of the qmye property.
     *
     */
    public void setQmye(double value) {
        this.qmye = value;
    }

}
