//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 增值税小规模纳税人申报申报保存接入报文
 *
 * <p>Java class for HXZGSB00045Request complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="HXZGSB00045Request">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}taxDoc">
 *       &lt;sequence>
 *         &lt;element name="sbxxGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="sbxxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}SBSbxxTjVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="jmxxGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="jmxxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}SBSbjmTjVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="yjxxGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="yjxxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}SBSbyjTjVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="zzssyyxgmnsrySbSbbdxxVO" type="{http://www.chinatax.gov.cn/dataspec/}zzssyyxgmnsrywbw"/>
 *         &lt;element name="sbbcTjqtxxVO" type="{http://www.chinatax.gov.cn/dataspec/}SBSBbcTjqtxxVO"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HXZGSB00045Request", propOrder = {
    "sbxxGrid",
    "jmxxGrid",
    "yjxxGrid",
    "zzssyyxgmnsrySbSbbdxxVO",
    "sbbcTjqtxxVO"
})
public class HXZGSB00045Request
    extends TaxDoc {

    @XmlElement(required = true)
    protected SbxxGrid sbxxGrid;
    @XmlElement(required = true)
    protected JmxxGrid jmxxGrid;
    @XmlElement(required = true)
    protected YjxxGrid yjxxGrid;
    @XmlElement(required = true)
    protected Zzssyyxgmnsrywbw zzssyyxgmnsrySbSbbdxxVO;
    @XmlElement(required = true)
    protected SBSBbcTjqtxxVO sbbcTjqtxxVO;

    /**
     * Gets the value of the sbxxGrid property.
     *
     * @return
     *     possible object is
     *     {@link SbxxGrid }
     *
     */
    public SbxxGrid getSbxxGrid() {
        return sbxxGrid;
    }

    /**
     * Sets the value of the sbxxGrid property.
     *
     * @param value
     *     allowed object is
     *     {@link SbxxGrid }
     *
     */
    public void setSbxxGrid(SbxxGrid value) {
        this.sbxxGrid = value;
    }

    /**
     * Gets the value of the jmxxGrid property.
     *
     * @return
     *     possible object is
     *     {@link JmxxGrid }
     *
     */
    public JmxxGrid getJmxxGrid() {
        return jmxxGrid;
    }

    /**
     * Sets the value of the jmxxGrid property.
     *
     * @param value
     *     allowed object is
     *     {@link JmxxGrid }
     *
     */
    public void setJmxxGrid(JmxxGrid value) {
        this.jmxxGrid = value;
    }

    /**
     * Gets the value of the yjxxGrid property.
     *
     * @return
     *     possible object is
     *     {@link YjxxGrid }
     *
     */
    public YjxxGrid getYjxxGrid() {
        return yjxxGrid;
    }

    /**
     * Sets the value of the yjxxGrid property.
     *
     * @param value
     *     allowed object is
     *     {@link YjxxGrid }
     *
     */
    public void setYjxxGrid(YjxxGrid value) {
        this.yjxxGrid = value;
    }

    /**
     * Gets the value of the zzssyyxgmnsrySbSbbdxxVO property.
     *
     * @return
     *     possible object is
     *     {@link Zzssyyxgmnsrywbw }
     *
     */
    public Zzssyyxgmnsrywbw getZzssyyxgmnsrySbSbbdxxVO() {
        return zzssyyxgmnsrySbSbbdxxVO;
    }

    /**
     * Sets the value of the zzssyyxgmnsrySbSbbdxxVO property.
     *
     * @param value
     *     allowed object is
     *     {@link Zzssyyxgmnsrywbw }
     *
     */
    public void setZzssyyxgmnsrySbSbbdxxVO(Zzssyyxgmnsrywbw value) {
        this.zzssyyxgmnsrySbSbbdxxVO = value;
    }

    /**
     * Gets the value of the sbbcTjqtxxVO property.
     *
     * @return
     *     possible object is
     *     {@link SBSBbcTjqtxxVO }
     *
     */
    public SBSBbcTjqtxxVO getSbbcTjqtxxVO() {
        return sbbcTjqtxxVO;
    }

    /**
     * Sets the value of the sbbcTjqtxxVO property.
     *
     * @param value
     *     allowed object is
     *     {@link SBSBbcTjqtxxVO }
     *
     */
    public void setSbbcTjqtxxVO(SBSBbcTjqtxxVO value) {
        this.sbbcTjqtxxVO = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="jmxxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}SBSbjmTjVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jmxxGridlb"
    })
    public static class JmxxGrid {

        protected List<SBSbjmTjVO> jmxxGridlb;

        /**
         * Gets the value of the jmxxGridlb property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the jmxxGridlb property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getJmxxGridlb().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SBSbjmTjVO }
         *
         *
         */
        public List<SBSbjmTjVO> getJmxxGridlb() {
            if (jmxxGridlb == null) {
                jmxxGridlb = new ArrayList<SBSbjmTjVO>();
            }
            return this.jmxxGridlb;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="sbxxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}SBSbxxTjVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sbxxGridlb"
    })
    public static class SbxxGrid {

        protected List<SBSbxxTjVO> sbxxGridlb;

        /**
         * Gets the value of the sbxxGridlb property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sbxxGridlb property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSbxxGridlb().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SBSbxxTjVO }
         *
         *
         */
        public List<SBSbxxTjVO> getSbxxGridlb() {
            if (sbxxGridlb == null) {
                sbxxGridlb = new ArrayList<SBSbxxTjVO>();
            }
            return this.sbxxGridlb;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="yjxxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}SBSbyjTjVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "yjxxGridlb"
    })
    public static class YjxxGrid {

        protected List<SBSbyjTjVO> yjxxGridlb;

        /**
         * Gets the value of the yjxxGridlb property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the yjxxGridlb property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getYjxxGridlb().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SBSbyjTjVO }
         *
         *
         */
        public List<SBSbyjTjVO> getYjxxGridlb() {
            if (yjxxGridlb == null) {
                yjxxGridlb = new ArrayList<SBSbyjTjVO>();
            }
            return this.yjxxGridlb;
        }

    }

}
