//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 《机动车辆生产企业销售明细表》业务报文
 *
 * <p>Java class for jdclscqyxsmxbywbw complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="jdclscqyxsmxbywbw">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}taxDoc">
 *       &lt;sequence>
 *         &lt;element name="jdclscqyxsmxb" type="{http://www.chinatax.gov.cn/dataspec/}jdclscqyxsmxb"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jdclscqyxsmxbywbw", propOrder = {
    "jdclscqyxsmxb"
})
public class Jdclscqyxsmxbywbw
    extends TaxDoc {

    @XmlElement(required = true)
    protected Jdclscqyxsmxb jdclscqyxsmxb;

    /**
     * Gets the value of the jdclscqyxsmxb property.
     *
     * @return
     *     possible object is
     *     {@link Jdclscqyxsmxb }
     *
     */
    public Jdclscqyxsmxb getJdclscqyxsmxb() {
        return jdclscqyxsmxb;
    }

    /**
     * Sets the value of the jdclscqyxsmxb property.
     *
     * @param value
     *     allowed object is
     *     {@link Jdclscqyxsmxb }
     *
     */
    public void setJdclscqyxsmxb(Jdclscqyxsmxb value) {
        this.jdclscqyxsmxb = value;
    }

}
