//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 机动车辆生产企业销售明细表
 *
 * <p>Java class for jdclscqyxsmxbGridlbVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="jdclscqyxsmxbGridlbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ewbhxh" type="{http://www.chinatax.gov.cn/dataspec/}ewbhxh"/>
 *         &lt;element name="xsdxmc" type="{http://www.chinatax.gov.cn/dataspec/}xsdxmc"/>
 *         &lt;element name="ghfnsrrbh" type="{http://www.chinatax.gov.cn/dataspec/}ghfnsrrbh"/>
 *         &lt;element name="cpxh1" type="{http://www.chinatax.gov.cn/dataspec/}cpxh1"/>
 *         &lt;element name="clsbdm" type="{http://www.chinatax.gov.cn/dataspec/}clsbdm"/>
 *         &lt;element name="xsjg" type="{http://www.chinatax.gov.cn/dataspec/}xsjg"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jdclscqyxsmxbGridlbVO", propOrder = {
    "ewbhxh",
    "xsdxmc",
    "ghfnsrrbh",
    "cpxh1",
    "clsbdm",
    "xsjg"
})
public class JdclscqyxsmxbGridlbVO {

    protected long ewbhxh;
    @XmlElement(required = true)
    protected String xsdxmc;
    @XmlElement(required = true)
    protected String ghfnsrrbh;
    @XmlElement(required = true)
    protected String cpxh1;
    @XmlElement(required = true)
    protected String clsbdm;
    protected double xsjg;

    /**
     * Gets the value of the ewbhxh property.
     *
     */
    public long getEwbhxh() {
        return ewbhxh;
    }

    /**
     * Sets the value of the ewbhxh property.
     *
     */
    public void setEwbhxh(long value) {
        this.ewbhxh = value;
    }

    /**
     * Gets the value of the xsdxmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getXsdxmc() {
        return xsdxmc;
    }

    /**
     * Sets the value of the xsdxmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setXsdxmc(String value) {
        this.xsdxmc = value;
    }

    /**
     * Gets the value of the ghfnsrrbh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGhfnsrrbh() {
        return ghfnsrrbh;
    }

    /**
     * Sets the value of the ghfnsrrbh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGhfnsrrbh(String value) {
        this.ghfnsrrbh = value;
    }

    /**
     * Gets the value of the cpxh1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCpxh1() {
        return cpxh1;
    }

    /**
     * Sets the value of the cpxh1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCpxh1(String value) {
        this.cpxh1 = value;
    }

    /**
     * Gets the value of the clsbdm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getClsbdm() {
        return clsbdm;
    }

    /**
     * Sets the value of the clsbdm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setClsbdm(String value) {
        this.clsbdm = value;
    }

    /**
     * Gets the value of the xsjg property.
     *
     */
    public double getXsjg() {
        return xsjg;
    }

    /**
     * Sets the value of the xsjg property.
     *
     */
    public void setXsjg(double value) {
        this.xsjg = value;
    }

}
