//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 《机动车销售统一发票清单》
 *
 * <p>Java class for jdcxstyfpqd complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="jdcxstyfpqd">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jdcxstyfpqdGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="jdcxstyfpqdGridlb" type="{http://www.chinatax.gov.cn/dataspec/}jdcxstyfpqdGridlbVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jdcxstyfpqd", propOrder = {
    "jdcxstyfpqdGrid"
})
public class Jdcxstyfpqd {

    @XmlElement(required = true)
    protected JdcxstyfpqdGrid jdcxstyfpqdGrid;

    /**
     * Gets the value of the jdcxstyfpqdGrid property.
     *
     * @return
     *     possible object is
     *     {@link JdcxstyfpqdGrid }
     *
     */
    public JdcxstyfpqdGrid getJdcxstyfpqdGrid() {
        return jdcxstyfpqdGrid;
    }

    /**
     * Sets the value of the jdcxstyfpqdGrid property.
     *
     * @param value
     *     allowed object is
     *     {@link JdcxstyfpqdGrid }
     *
     */
    public void setJdcxstyfpqdGrid(JdcxstyfpqdGrid value) {
        this.jdcxstyfpqdGrid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="jdcxstyfpqdGridlb" type="{http://www.chinatax.gov.cn/dataspec/}jdcxstyfpqdGridlbVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jdcxstyfpqdGridlb"
    })
    public static class JdcxstyfpqdGrid {

        protected List<JdcxstyfpqdGridlbVO> jdcxstyfpqdGridlb;

        /**
         * Gets the value of the jdcxstyfpqdGridlb property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the jdcxstyfpqdGridlb property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getJdcxstyfpqdGridlb().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JdcxstyfpqdGridlbVO }
         *
         *
         */
        public List<JdcxstyfpqdGridlbVO> getJdcxstyfpqdGridlb() {
            if (jdcxstyfpqdGridlb == null) {
                jdcxstyfpqdGridlb = new ArrayList<JdcxstyfpqdGridlbVO>();
            }
            return this.jdcxstyfpqdGridlb;
        }

    }

}
