//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 机动车销售统一发票清单
 *
 * <p>Java class for jdcxstyfpqdGrid complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="jdcxstyfpqdGrid">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="jdcxstyfpqdGridlbVO" type="{http://www.chinatax.gov.cn/dataspec/}jdcxstyfpqdGridlbVO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jdcxstyfpqdGrid", propOrder = {
    "jdcxstyfpqdGridlbVO"
})
public class JdcxstyfpqdGrid {

    @XmlElement(required = true)
    protected List<JdcxstyfpqdGridlbVO> jdcxstyfpqdGridlbVO;

    /**
     * Gets the value of the jdcxstyfpqdGridlbVO property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jdcxstyfpqdGridlbVO property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJdcxstyfpqdGridlbVO().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JdcxstyfpqdGridlbVO }
     *
     *
     */
    public List<JdcxstyfpqdGridlbVO> getJdcxstyfpqdGridlbVO() {
        if (jdcxstyfpqdGridlbVO == null) {
            jdcxstyfpqdGridlbVO = new ArrayList<JdcxstyfpqdGridlbVO>();
        }
        return this.jdcxstyfpqdGridlbVO;
    }

}
