//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 进项信息
 *
 * <p>Java class for jxGridlbVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="jxGridlbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ewbhxh" type="{http://www.chinatax.gov.cn/dataspec/}ewbhxh"/>
 *         &lt;element name="bqfsjx" type="{http://www.chinatax.gov.cn/dataspec/}bqfsjx"/>
 *         &lt;element name="mshwyjxse" type="{http://www.chinatax.gov.cn/dataspec/}mshwyjxse"/>
 *         &lt;element name="fzcssjxse" type="{http://www.chinatax.gov.cn/dataspec/}fzcssjxse"/>
 *         &lt;element name="zrjxse" type="{http://www.chinatax.gov.cn/dataspec/}zrjxse"/>
 *         &lt;element name="bqsjdkjxse" type="{http://www.chinatax.gov.cn/dataspec/}bqsjdkjxse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jxGridlbVO", propOrder = {
    "ewbhxh",
    "bqfsjx",
    "mshwyjxse",
    "fzcssjxse",
    "zrjxse",
    "bqsjdkjxse"
})
public class JxGridlbVO {

    protected long ewbhxh;
    protected double bqfsjx;
    protected double mshwyjxse;
    protected double fzcssjxse;
    protected double zrjxse;
    protected double bqsjdkjxse;

    /**
     * Gets the value of the ewbhxh property.
     *
     */
    public long getEwbhxh() {
        return ewbhxh;
    }

    /**
     * Sets the value of the ewbhxh property.
     *
     */
    public void setEwbhxh(long value) {
        this.ewbhxh = value;
    }

    /**
     * Gets the value of the bqfsjx property.
     *
     */
    public double getBqfsjx() {
        return bqfsjx;
    }

    /**
     * Sets the value of the bqfsjx property.
     *
     */
    public void setBqfsjx(double value) {
        this.bqfsjx = value;
    }

    /**
     * Gets the value of the mshwyjxse property.
     *
     */
    public double getMshwyjxse() {
        return mshwyjxse;
    }

    /**
     * Sets the value of the mshwyjxse property.
     *
     */
    public void setMshwyjxse(double value) {
        this.mshwyjxse = value;
    }

    /**
     * Gets the value of the fzcssjxse property.
     *
     */
    public double getFzcssjxse() {
        return fzcssjxse;
    }

    /**
     * Sets the value of the fzcssjxse property.
     *
     */
    public void setFzcssjxse(double value) {
        this.fzcssjxse = value;
    }

    /**
     * Gets the value of the zrjxse property.
     *
     */
    public double getZrjxse() {
        return zrjxse;
    }

    /**
     * Sets the value of the zrjxse property.
     *
     */
    public void setZrjxse(double value) {
        this.zrjxse = value;
    }

    /**
     * Gets the value of the bqsjdkjxse property.
     *
     */
    public double getBqsjdkjxse() {
        return bqsjdkjxse;
    }

    /**
     * Sets the value of the bqsjdkjxse property.
     *
     */
    public void setBqsjdkjxse(double value) {
        this.bqsjdkjxse = value;
    }

}
