//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import com.example.cloud.company.common.vo.xgm.hdxx.ZszmGridlbVO;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the cn.com.servyou.nfpt.commons.vo.sjgt3.zzsxgm package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TaxML_QNAME = new QName("http://www.chinatax.gov.cn/dataspec/", "taxML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cn.com.servyou.nfpt.commons.vo.sjgt3.zzsxgm
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zzsxgmflzlsedjqkb }
     *
     */
    public Zzsxgmflzlsedjqkb createZzsxgmflzlsedjqkb() {
        return new Zzsxgmflzlsedjqkb();
    }

    /**
     * Create an instance of {@link Zzsjmssbmxbywbw }
     *
     */
    public Zzsjmssbmxbywbw createZzsjmssbmxbywbw() {
        return new Zzsjmssbmxbywbw();
    }


    public Zzsjmssbmxb createZzsjmssbmxb() {
        return new Zzsjmssbmxb();
    }

    /**
     * Create an instance of {@link HXZGSB00045Request }
     *
     */
    public HXZGSB00045Request createHXZGSB00045Request() {
        return new HXZGSB00045Request();
    }

    /**
     * Create an instance of {@link Dlqyzzsxxsehjxsecdd }
     *
     */
    public Dlqyzzsxxsehjxsecdd createDlqyzzsxxsehjxsecdd() {
        return new Dlqyzzsxxsehjxsecdd();
    }

    /**
     * Create an instance of {@link Jdcxstyfpqd }
     *
     */
    public Jdcxstyfpqd createJdcxstyfpqd() {
        return new Jdcxstyfpqd();
    }

    /**
     * Create an instance of {@link SBSbxxkzJhVO }
     *
     */
    public SBSbxxkzJhVO createSBSbxxkzJhVO() {
        return new SBSbxxkzJhVO();
    }

    /**
     * Create an instance of {@link Zzssyyxgmnsr }
     *
     */
    public Zzssyyxgmnsr createZzssyyxgmnsr() {
        return new Zzssyyxgmnsr();
    }

    /**
     * Create an instance of {@link Jdclscqyxsmxb }
     *
     */
    public Jdclscqyxsmxb createJdclscqyxsmxb() {
        return new Jdclscqyxsmxb();
    }

    /**
     * Create an instance of {@link SBSbfBcYzxxVO }
     *
     */
    public SBSbfBcYzxxVO createSBSbfBcYzxxVO() {
        return new SBSbfBcYzxxVO();
    }

    /**
     * Create an instance of {@link FdcjysbxxGridlbVO }
     *
     */
    public FdcjysbxxGridlbVO createFdcjysbxxGridlbVO() {
        return new FdcjysbxxGridlbVO();
    }

    /**
     * Create an instance of {@link SBNsryjxxReturnVO }
     *
     */
    public SBNsryjxxReturnVO createSBNsryjxxReturnVO() {
        return new SBNsryjxxReturnVO();
    }

    /**
     * Create an instance of {@link Sbbheadkz1VO }
     *
     */
    public Sbbheadkz1VO createSbbheadkz1VO() {
        return new Sbbheadkz1VO();
    }

    /**
     * Create an instance of {@link SBSzpmsbztsbqxReturnVO }
     *
     */
    public SBSzpmsbztsbqxReturnVO createSBSzpmsbztsbqxReturnVO() {
        return new SBSzpmsbztsbqxReturnVO();
    }

    /**
     * Create an instance of {@link JdcxstyfpqdGridlbVO }
     *
     */
    public JdcxstyfpqdGridlbVO createJdcxstyfpqdGridlbVO() {
        return new JdcxstyfpqdGridlbVO();
    }

    /**
     * Create an instance of {@link XgmfjsxxGrid }
     *
     */
    public XgmfjsxxGrid createXgmfjsxxGrid() {
        return new XgmfjsxxGrid();
    }

    /**
     * Create an instance of {@link SBXfsjyjsjgVO }
     *
     */
    public SBXfsjyjsjgVO createSBXfsjyjsjgVO() {
        return new SBXfsjyjsjgVO();
    }


    public ZzsjmssbmxbjsxmGrid createZzsjmssbmxbjsxmGrid() {
        return new ZzsjmssbmxbjsxmGrid();
    }

    /**
     * Create an instance of {@link SBSBbcTjqtxxVO }
     *
     */
    public SBSBbcTjqtxxVO createSBSBbcTjqtxxVO() {
        return new SBSBbcTjqtxxVO();
    }

    /**
     * Create an instance of {@link SBXfssbsjxxVO }
     *
     */
    public SBXfssbsjxxVO createSBXfssbsjxxVO() {
        return new SBXfssbsjxxVO();
    }

    /**
     * Create an instance of {@link SBXfsbqdsdjsejsb2VO }
     *
     */
    public SBXfsbqdsdjsejsb2VO createSBXfsbqdsdjsejsb2VO() {
        return new SBXfsbqdsdjsejsb2VO();
    }

    /**
     * Create an instance of {@link SBKjywrxxReturnVO }
     *
     */
    public SBKjywrxxReturnVO createSBKjywrxxReturnVO() {
        return new SBKjywrxxReturnVO();
    }

    /**
     * Create an instance of {@link SBSbjmTjVO }
     *
     */
    public SBSbjmTjVO createSBSbjmTjVO() {
        return new SBSbjmTjVO();
    }

    /**
     * Create an instance of {@link Zzsxgmflzlsedjqkbywbw }
     *
     */
    public Zzsxgmflzlsedjqkbywbw createZzsxgmflzlsedjqkbywbw() {
        return new Zzsxgmflzlsedjqkbywbw();
    }

    /**
     * Create an instance of {@link Sbbheadkz2VO }
     *
     */
    public Sbbheadkz2VO createSbbheadkz2VO() {
        return new Sbbheadkz2VO();
    }

    /**
     * Create an instance of {@link SBQysdszjgxxVO }
     *
     */
    public SBQysdszjgxxVO createSBQysdszjgxxVO() {
        return new SBQysdszjgxxVO();
    }

    /**
     * Create an instance of {@link SBPlsbztsbqxReturnVO }
     *
     */
    public SBPlsbztsbqxReturnVO createSBPlsbztsbqxReturnVO() {
        return new SBPlsbztsbqxReturnVO();
    }

    /**
     * Create an instance of {@link SBsbqkReturnVO }
     *
     */
    public SBsbqkReturnVO createSBsbqkReturnVO() {
        return new SBsbqkReturnVO();
    }

    /**
     * Create an instance of {@link Jdclscqyxsmxbywbw }
     *
     */
    public Jdclscqyxsmxbywbw createJdclscqyxsmxbywbw() {
        return new Jdclscqyxsmxbywbw();
    }

    /**
     * Create an instance of {@link SBFjmQysdsjssbqtxxVO }
     *
     */
    public SBFjmQysdsjssbqtxxVO createSBFjmQysdsjssbqtxxVO() {
        return new SBFjmQysdsjssbqtxxVO();
    }

    /**
     * Create an instance of {@link SBCcsNsrjbxxVO }
     *
     */
    public SBCcsNsrjbxxVO createSBCcsNsrjbxxVO() {
        return new SBCcsNsrjbxxVO();
    }

    /**
     * Create an instance of {@link SedjqkbSlxxFormVO }
     *
     */
    public SedjqkbSlxxFormVO createSedjqkbSlxxFormVO() {
        return new SedjqkbSlxxFormVO();
    }

    /**
     * Create an instance of {@link SBCcsSlxxVO }
     *
     */
    public SBCcsSlxxVO createSBCcsSlxxVO() {
        return new SBCcsSlxxVO();
    }

    /**
     * Create an instance of {@link SBNsrhzsbnsrbzxxQueryVO }
     *
     */
    public SBNsrhzsbnsrbzxxQueryVO createSBNsrhzsbnsrbzxxQueryVO() {
        return new SBNsrhzsbnsrbzxxQueryVO();
    }

    /**
     * Create an instance of {@link SBFjmqyhtxmbaxxQueryVO }
     *
     */
    public SBFjmqyhtxmbaxxQueryVO createSBFjmqyhtxmbaxxQueryVO() {
        return new SBFjmqyhtxmbaxxQueryVO();
    }

    /**
     * Create an instance of {@link SbbFjxxVO }
     *
     */
    public SbbFjxxVO createSbbFjxxVO() {
        return new SbbFjxxVO();
    }


    public ZzsjmssbmxbmsxmGrid createZzsjmssbmxbmsxmGrid() {
        return new ZzsjmssbmxbmsxmGrid();
    }

    /**
     * Create an instance of {@link SBsbqkmxQueryVO }
     *
     */
    public SBsbqkmxQueryVO createSBsbqkmxQueryVO() {
        return new SBsbqkmxQueryVO();
    }

    /**
     * Create an instance of {@link SBQysdsczzsndsb2014NsrjbxxVO }
     *
     */
    public SBQysdsczzsndsb2014NsrjbxxVO createSBQysdsczzsndsb2014NsrjbxxVO() {
        return new SBQysdsczzsndsb2014NsrjbxxVO();
    }

    /**
     * Create an instance of {@link SBNsrxxJhVO }
     *
     */
    public SBNsrxxJhVO createSBNsrxxJhVO() {
        return new SBNsrxxJhVO();
    }

    /**
     * Create an instance of {@link SBJmxxJhVO }
     *
     */
    public SBJmxxJhVO createSBJmxxJhVO() {
        return new SBJmxxJhVO();
    }

    /**
     * Create an instance of {@link DwtzGridlbVO }
     *
     */
    public DwtzGridlbVO createDwtzGridlbVO() {
        return new DwtzGridlbVO();
    }

    /**
     * Create an instance of {@link SBSbfgyVO }
     *
     */
    public SBSbfgyVO createSBSbfgyVO() {
        return new SBSbfgyVO();
    }

    /**
     * Create an instance of {@link XgmfjsxxGridlb }
     *
     */
    public XgmfjsxxGridlb createXgmfjsxxGridlb() {
        return new XgmfjsxxGridlb();
    }

    /**
     * Create an instance of {@link SBNsrzdsyjkbzxxReturnVO }
     *
     */
    public SBNsrzdsyjkbzxxReturnVO createSBNsrzdsyjkbzxxReturnVO() {
        return new SBNsrzdsyjkbzxxReturnVO();
    }

    /**
     * Create an instance of {@link SBXfsscjyqkbVO }
     *
     */
    public SBXfsscjyqkbVO createSBXfsscjyqkbVO() {
        return new SBXfsscjyqkbVO();
    }

    /**
     * Create an instance of {@link SBSaveReturnVO }
     *
     */
    public SBSaveReturnVO createSBSaveReturnVO() {
        return new SBSaveReturnVO();
    }

    /**
     * Create an instance of {@link ZzsxgmGridlbVO }
     *
     */
    public ZzsxgmGridlbVO createZzsxgmGridlbVO() {
        return new ZzsxgmGridlbVO();
    }

    /**
     * Create an instance of {@link SBQysdsfzjgxxVO }
     *
     */
    public SBQysdsfzjgxxVO createSBQysdsfzjgxxVO() {
        return new SBQysdsfzjgxxVO();
    }

    /**
     * Create an instance of {@link SlxxForm }
     *
     */
    public SlxxForm createSlxxForm() {
        return new SlxxForm();
    }

    /**
     * Create an instance of {@link SBSysbxxQueryVO }
     *
     */
    public SBSysbxxQueryVO createSBSysbxxQueryVO() {
        return new SBSysbxxQueryVO();
    }

    /**
     * Create an instance of {@link ZzsjmssbmxbjsxmGridlbVO }
     *
     */
    public ZzsjmssbmxbjsxmGridlbVO createZzsjmssbmxbjsxmGridlbVO() {
        return new ZzsjmssbmxbjsxmGridlbVO();
    }

    /**
     * Create an instance of {@link SbbheadVO }
     *
     */
    public SbbheadVO createSbbheadVO() {
        return new SbbheadVO();
    }

    /**
     * Create an instance of {@link Zzsxgmflzl }
     *
     */
    public Zzsxgmflzl createZzsxgmflzl() {
        return new Zzsxgmflzl();
    }

    /**
     * Create an instance of {@link SBNsrhzsbnsrbzxxReturnVO }
     *
     */
    public SBNsrhzsbnsrbzxxReturnVO createSBNsrhzsbnsrbzxxReturnVO() {
        return new SBNsrhzsbnsrbzxxReturnVO();
    }

    /**
     * Create an instance of {@link ZzsjmssbmxbmsxmGridlbVO }
     *
     */
    public ZzsjmssbmxbmsxmGridlbVO createZzsjmssbmxbmsxmGridlbVO() {
        return new ZzsjmssbmxbmsxmGridlbVO();
    }

    /**
     * Create an instance of {@link SBCcsGxdcReturnVO }
     *
     */
    public SBCcsGxdcReturnVO createSBCcsGxdcReturnVO() {
        return new SBCcsGxdcReturnVO();
    }

    /**
     * Create an instance of {@link Dlqyzzsxxsehjxsecddywbw }
     *
     */
    public Dlqyzzsxxsehjxsecddywbw createDlqyzzsxxsehjxsecddywbw() {
        return new Dlqyzzsxxsehjxsecddywbw();
    }

    /**
     * Create an instance of {@link SedmyhmxbForm }
     *
     */
    public SedmyhmxbForm createSedmyhmxbForm() {
        return new SedmyhmxbForm();
    }

    /**
     * Create an instance of {@link SBsbqkQueryVO }
     *
     */
    public SBsbqkQueryVO createSBsbqkQueryVO() {
        return new SBsbqkQueryVO();
    }

    /**
     * Create an instance of {@link SBXfssbsjxxqtVO }
     *
     */
    public SBXfssbsjxxqtVO createSBXfssbsjxxqtVO() {
        return new SBXfssbsjxxqtVO();
    }

    /**
     * Create an instance of {@link SBXfsbqdsdjsejsbVO }
     *
     */
    public SBXfsbqdsdjsejsbVO createSBXfsbqdsdjsejsbVO() {
        return new SBXfsbqdsdjsejsbVO();
    }

    /**
     * Create an instance of {@link SBSbxxTjVO }
     *
     */
    public SBSbxxTjVO createSBSbxxTjVO() {
        return new SBSbxxTjVO();
    }

    /**
     * Create an instance of {@link SkzsFormVO }
     *
     */
    public SkzsFormVO createSkzsFormVO() {
        return new SkzsFormVO();
    }

    /**
     * Create an instance of {@link NsrxxFormVO }
     *
     */
    public NsrxxFormVO createNsrxxFormVO() {
        return new NsrxxFormVO();
    }

    /**
     * Create an instance of {@link SBXfssbysxmVO }
     *
     */
    public SBXfssbysxmVO createSBXfssbysxmVO() {
        return new SBXfssbysxmVO();
    }

    /**
     * Create an instance of {@link SBsbqkmxReturnVO }
     *
     */
    public SBsbqkmxReturnVO createSBsbqkmxReturnVO() {
        return new SBsbqkmxReturnVO();
    }

    /**
     * Create an instance of {@link JdclscqyxsmxbGrid }
     *
     */
    public JdclscqyxsmxbGrid createJdclscqyxsmxbGrid() {
        return new JdclscqyxsmxbGrid();
    }

    /**
     * Create an instance of {@link SBXfssbsjxxkz2VO }
     *
     */
    public SBXfssbsjxxkz2VO createSBXfssbsjxxkz2VO() {
        return new SBXfssbsjxxkz2VO();
    }

    /**
     * Create an instance of {@link SBZzsnsrldxxVO }
     *
     */
    public SBZzsnsrldxxVO createSBZzsnsrldxxVO() {
        return new SBZzsnsrldxxVO();
    }

    /**
     * Create an instance of {@link AsrzehdynsdesmxVO }
     *
     */
    public AsrzehdynsdesmxVO createAsrzehdynsdesmxVO() {
        return new AsrzehdynsdesmxVO();
    }

    /**
     * Create an instance of {@link SBSzpmsbztsbqxQueryVO }
     *
     */
    public SBSzpmsbztsbqxQueryVO createSBSzpmsbztsbqxQueryVO() {
        return new SBSzpmsbztsbqxQueryVO();
    }

    /**
     * Create an instance of {@link SBSysbxxReturnVO }
     *
     */
    public SBSysbxxReturnVO createSBSysbxxReturnVO() {
        return new SBSysbxxReturnVO();
    }

    /**
     * Create an instance of {@link SBNsryjxxQueryVO }
     *
     */
    public SBNsryjxxQueryVO createSBNsryjxxQueryVO() {
        return new SBNsryjxxQueryVO();
    }

    /**
     * Create an instance of {@link SBPlsbztsbqxQueryVO }
     *
     */
    public SBPlsbztsbqxQueryVO createSBPlsbztsbqxQueryVO() {
        return new SBPlsbztsbqxQueryVO();
    }

    /**
     * Create an instance of {@link TaxList }
     *
     */
    public TaxList createTaxList() {
        return new TaxList();
    }

    /**
     * Create an instance of {@link SBFjmqyhtxmbaxxReturnVO }
     *
     */
    public SBFjmqyhtxmbaxxReturnVO createSBFjmqyhtxmbaxxReturnVO() {
        return new SBFjmqyhtxmbaxxReturnVO();
    }

    /**
     * Create an instance of {@link SBXfssbsjxxkz1VO }
     *
     */
    public SBXfssbsjxxkz1VO createSBXfssbsjxxkz1VO() {
        return new SBXfssbsjxxkz1VO();
    }

    /**
     * Create an instance of {@link SBYjxxJhVO }
     *
     */
    public SBYjxxJhVO createSBYjxxJhVO() {
        return new SBYjxxJhVO();
    }

    /**
     * Create an instance of {@link SBCwbbbsyxxcjSaveVO }
     *
     */
    public SBCwbbbsyxxcjSaveVO createSBCwbbbsyxxcjSaveVO() {
        return new SBCwbbbsyxxcjSaveVO();
    }

    /**
     * Create an instance of {@link Zzsxgmfjssb }
     *
     */
    public Zzsxgmfjssb createZzsxgmfjssb() {
        return new Zzsxgmfjssb();
    }

    /**
     * Create an instance of {@link SBFjmQysdshdzshdzsqtxxVO }
     *
     */
    public SBFjmQysdshdzshdzsqtxxVO createSBFjmQysdshdzshdzsqtxxVO() {
        return new SBFjmQysdshdzshdzsqtxxVO();
    }

    /**
     * Create an instance of {@link SlxxFormVO }
     *
     */
    public SlxxFormVO createSlxxFormVO() {
        return new SlxxFormVO();
    }


    public XxGrid createXxGrid() {
        return new XxGrid();
    }

    /**
     * Create an instance of {@link JxGridlbVO }
     *
     */
    public JxGridlbVO createJxGridlbVO() {
        return new JxGridlbVO();
    }

    /**
     * Create an instance of {@link Zzsxgmflzlywbw }
     *
     */
    public Zzsxgmflzlywbw createZzsxgmflzlywbw() {
        return new Zzsxgmflzlywbw();
    }

    /**
     * Create an instance of {@link Jdcxstyfpqdywbw }
     *
     */
    public Jdcxstyfpqdywbw createJdcxstyfpqdywbw() {
        return new Jdcxstyfpqdywbw();
    }

    /**
     * Create an instance of {@link FlzlsedjqkbGridlbVO }
     *
     */
    public FlzlsedjqkbGridlbVO createFlzlsedjqkbGridlbVO() {
        return new FlzlsedjqkbGridlbVO();
    }

    /**
     * Create an instance of {@link ZspmGridlbVO }
     *
     */
    public ZspmGridlbVO createZspmGridlbVO() {
        return new ZspmGridlbVO();
    }

    /**
     * Create an instance of {@link JdclscqyxsmxbGridlbVO }
     *
     */
    public JdclscqyxsmxbGridlbVO createJdclscqyxsmxbGridlbVO() {
        return new JdclscqyxsmxbGridlbVO();
    }

    /**
     * Create an instance of {@link FlzlFormVO }
     *
     */
    public FlzlFormVO createFlzlFormVO() {
        return new FlzlFormVO();
    }

    /**
     * Create an instance of {@link SBKjywrxxQueryVO }
     *
     */
    public SBKjywrxxQueryVO createSBKjywrxxQueryVO() {
        return new SBKjywrxxQueryVO();
    }

    /**
     * Create an instance of {@link SBXfsxphxggjyhzVO }
     *
     */
    public SBXfsxphxggjyhzVO createSBXfsxphxggjyhzVO() {
        return new SBXfsxphxggjyhzVO();
    }

    /**
     * Create an instance of {@link Sbbslxxkz1VO }
     *
     */
    public Sbbslxxkz1VO createSbbslxxkz1VO() {
        return new Sbbslxxkz1VO();
    }

    /**
     * Create an instance of {@link ZszmGridlbVO }
     *
     */
    public ZszmGridlbVO createZszmGridlbVO() {
        return new ZszmGridlbVO();
    }

    /**
     * Create an instance of {@link SBSbfSbxxVO }
     *
     */
    public SBSbfSbxxVO createSBSbfSbxxVO() {
        return new SBSbfSbxxVO();
    }

    /**
     * Create an instance of {@link SBQysdsczzsndsbmbkstzxxVO }
     *
     */
    public SBQysdsczzsndsbmbkstzxxVO createSBQysdsczzsndsbmbkstzxxVO() {
        return new SBQysdsczzsndsbmbkstzxxVO();
    }

    /**
     * Create an instance of {@link SBSbxxJhVO }
     *
     */
    public SBSbxxJhVO createSBSbxxJhVO() {
        return new SBSbxxJhVO();
    }

    /**
     * Create an instance of {@link Zzssyyxgmnsrywbw }
     *
     */
    public Zzssyyxgmnsrywbw createZzssyyxgmnsrywbw() {
        return new Zzssyyxgmnsrywbw();
    }

    /**
     * Create an instance of {@link Sbbslxxkz3VO }
     *
     */
    public Sbbslxxkz3VO createSbbslxxkz3VO() {
        return new Sbbslxxkz3VO();
    }

    /**
     * Create an instance of {@link XxGridlbVO }
     *
     */
    public XxGridlbVO createXxGridlbVO() {
        return new XxGridlbVO();
    }

    /**
     * Create an instance of {@link Sbbslxxkz2VO }
     *
     */
    public Sbbslxxkz2VO createSbbslxxkz2VO() {
        return new Sbbslxxkz2VO();
    }

    /**
     * Create an instance of {@link Zzssyyxgmnsrzbywbw }
     *
     */
    public Zzssyyxgmnsrzbywbw createZzssyyxgmnsrzbywbw() {
        return new Zzssyyxgmnsrzbywbw();
    }

    /**
     * Create an instance of {@link Xgmfjssbywbw }
     *
     */
    public Xgmfjssbywbw createXgmfjssbywbw() {
        return new Xgmfjssbywbw();
    }

    /**
     * Create an instance of {@link SbbslxxVO }
     *
     */
    public SbbslxxVO createSbbslxxVO() {
        return new SbbslxxVO();
    }

    /**
     * Create an instance of {@link SBNsrzdsyjkbzxxQueryVO }
     *
     */
    public SBNsrzdsyjkbzxxQueryVO createSBNsrzdsyjkbzxxQueryVO() {
        return new SBNsrzdsyjkbzxxQueryVO();
    }


    public JdcxstyfpqdGrid createJdcxstyfpqdGrid() {
        return new JdcxstyfpqdGrid();
    }

    /**
     * Create an instance of {@link QyzygdGridlbVO }
     *
     */
    public QyzygdGridlbVO createQyzygdGridlbVO() {
        return new QyzygdGridlbVO();
    }


    public JxGrid createJxGrid() {
        return new JxGrid();
    }

    /**
     * Create an instance of {@link SBSbyjTjVO }
     *
     */
    public SBSbyjTjVO createSBSbyjTjVO() {
        return new SBSbyjTjVO();
    }

    /**
     * Create an instance of {@link SBCwbbbsyxxcjQueryVO }
     *
     */
    public SBCwbbbsyxxcjQueryVO createSBCwbbbsyxxcjQueryVO() {
        return new SBCwbbbsyxxcjQueryVO();
    }

    /**
     * Create an instance of {@link Zzsxgmflzlsedjqkb.FlzlsedjqkbGrid }
     *
     */
    public Zzsxgmflzlsedjqkb.FlzlsedjqkbGrid createZzsxgmflzlsedjqkbFlzlsedjqkbGrid() {
        return new Zzsxgmflzlsedjqkb.FlzlsedjqkbGrid();
    }

    /**
     * Create an instance of {@link Zzsjmssbmxbywbw.Zzsjmssbmxb }
     *
     */
    public Zzsjmssbmxbywbw.Zzsjmssbmxb createZzsjmssbmxbywbwZzsjmssbmxb() {
        return new Zzsjmssbmxbywbw.Zzsjmssbmxb();
    }


    public ZzsjmssbmxbjsxmGrid createZzsjmssbmxbZzsjmssbmxbjsxmGrid() {
        return new ZzsjmssbmxbjsxmGrid();
    }


    public ZzsjmssbmxbmsxmGrid createZzsjmssbmxbZzsjmssbmxbmsxmGrid() {
        return new ZzsjmssbmxbmsxmGrid();
    }

    /**
     * Create an instance of {@link HXZGSB00045Request.SbxxGrid }
     *
     */
    public HXZGSB00045Request.SbxxGrid createHXZGSB00045RequestSbxxGrid() {
        return new HXZGSB00045Request.SbxxGrid();
    }

    /**
     * Create an instance of {@link HXZGSB00045Request.JmxxGrid }
     *
     */
    public HXZGSB00045Request.JmxxGrid createHXZGSB00045RequestJmxxGrid() {
        return new HXZGSB00045Request.JmxxGrid();
    }

    /**
     * Create an instance of {@link HXZGSB00045Request.YjxxGrid }
     *
     */
    public HXZGSB00045Request.YjxxGrid createHXZGSB00045RequestYjxxGrid() {
        return new HXZGSB00045Request.YjxxGrid();
    }

    /**
     * Create an instance of {@link Dlqyzzsxxsehjxsecdd.XxGrid }
     *
     */
    public Dlqyzzsxxsehjxsecdd.XxGrid createDlqyzzsxxsehjxsecddXxGrid() {
        return new Dlqyzzsxxsehjxsecdd.XxGrid();
    }

    /**
     * Create an instance of {@link Dlqyzzsxxsehjxsecdd.JxGrid }
     *
     */
    public Dlqyzzsxxsehjxsecdd.JxGrid createDlqyzzsxxsehjxsecddJxGrid() {
        return new Dlqyzzsxxsehjxsecdd.JxGrid();
    }

    /**
     * Create an instance of {@link Jdcxstyfpqd.JdcxstyfpqdGrid }
     *
     */
    public Jdcxstyfpqd.JdcxstyfpqdGrid createJdcxstyfpqdJdcxstyfpqdGrid() {
        return new Jdcxstyfpqd.JdcxstyfpqdGrid();
    }

    /**
     * Create an instance of {@link SBSbxxkzJhVO.ZszmGrid }
     *
     */
    public SBSbxxkzJhVO.ZszmGrid createSBSbxxkzJhVOZszmGrid() {
        return new SBSbxxkzJhVO.ZszmGrid();
    }

    /**
     * Create an instance of {@link SBSbxxkzJhVO.ZspmGrid }
     *
     */
    public SBSbxxkzJhVO.ZspmGrid createSBSbxxkzJhVOZspmGrid() {
        return new SBSbxxkzJhVO.ZspmGrid();
    }

    /**
     * Create an instance of {@link Zzssyyxgmnsr.ZzsxgmGrid }
     *
     */
    public Zzssyyxgmnsr.ZzsxgmGrid createZzssyyxgmnsrZzsxgmGrid() {
        return new Zzssyyxgmnsr.ZzsxgmGrid();
    }

    /**
     * Create an instance of {@link Jdclscqyxsmxb.JdcljxqyxsmxbGrid }
     *
     */
    public Jdclscqyxsmxb.JdcljxqyxsmxbGrid createJdclscqyxsmxbJdcljxqyxsmxbGrid() {
        return new Jdclscqyxsmxb.JdcljxqyxsmxbGrid();
    }

    /**
     * Create an instance of {@link SBSbfBcYzxxVO.SbfSbxxGrid }
     *
     */
    public SBSbfBcYzxxVO.SbfSbxxGrid createSBSbfBcYzxxVOSbfSbxxGrid() {
        return new SBSbfBcYzxxVO.SbfSbxxGrid();
    }

    /**
     * Create an instance of {@link FdcjysbxxGridlbVO.ZspmGrid }
     *
     */
    public FdcjysbxxGridlbVO.ZspmGrid createFdcjysbxxGridlbVOZspmGrid() {
        return new FdcjysbxxGridlbVO.ZspmGrid();
    }

    /**
     * Create an instance of {@link FdcjysbxxGridlbVO.ZszmGrid }
     *
     */
    public FdcjysbxxGridlbVO.ZszmGrid createFdcjysbxxGridlbVOZszmGrid() {
        return new FdcjysbxxGridlbVO.ZszmGrid();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxDoc }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.chinatax.gov.cn/dataspec/", name = "taxML")
    public JAXBElement<TaxDoc> createTaxML(TaxDoc value) {
        return new JAXBElement<TaxDoc>(_TaxML_QNAME, TaxDoc.class, null, value);
    }

}
