//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 居民企业企业所得税查账征收年度申报（2014）企业主要股东信息
 *
 * <p>Java class for QyzygdGridlbVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="QyzygdGridlbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mxuuid" type="{http://www.chinatax.gov.cn/dataspec/}mxuuid" minOccurs="0"/>
 *         &lt;element name="gdmc" type="{http://www.chinatax.gov.cn/dataspec/}gdmc" minOccurs="0"/>
 *         &lt;element name="sfzjzlDm" type="{http://www.chinatax.gov.cn/dataspec/}sfzjzlDm" minOccurs="0"/>
 *         &lt;element name="zjhm" type="{http://www.chinatax.gov.cn/dataspec/}zjhm" minOccurs="0"/>
 *         &lt;element name="jjxz" type="{http://www.chinatax.gov.cn/dataspec/}hyDm" minOccurs="0"/>
 *         &lt;element name="tzbl" type="{http://www.chinatax.gov.cn/dataspec/}tzbl" minOccurs="0"/>
 *         &lt;element name="gjdqDm" type="{http://www.chinatax.gov.cn/dataspec/}gjdqDm" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QyzygdGridlbVO", propOrder = {
    "mxuuid",
    "gdmc",
    "sfzjzlDm",
    "zjhm",
    "jjxz",
    "tzbl",
    "gjdqDm"
})
public class QyzygdGridlbVO {

    protected String mxuuid;
    protected String gdmc;
    protected String sfzjzlDm;
    protected String zjhm;
    protected String jjxz;
    protected Double tzbl;
    protected String gjdqDm;

    /**
     * Gets the value of the mxuuid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMxuuid() {
        return mxuuid;
    }

    /**
     * Sets the value of the mxuuid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMxuuid(String value) {
        this.mxuuid = value;
    }

    /**
     * Gets the value of the gdmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGdmc() {
        return gdmc;
    }

    /**
     * Sets the value of the gdmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGdmc(String value) {
        this.gdmc = value;
    }

    /**
     * Gets the value of the sfzjzlDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSfzjzlDm() {
        return sfzjzlDm;
    }

    /**
     * Sets the value of the sfzjzlDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSfzjzlDm(String value) {
        this.sfzjzlDm = value;
    }

    /**
     * Gets the value of the zjhm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * Sets the value of the zjhm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZjhm(String value) {
        this.zjhm = value;
    }

    /**
     * Gets the value of the jjxz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getJjxz() {
        return jjxz;
    }

    /**
     * Sets the value of the jjxz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setJjxz(String value) {
        this.jjxz = value;
    }

    /**
     * Gets the value of the tzbl property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getTzbl() {
        return tzbl;
    }

    /**
     * Sets the value of the tzbl property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setTzbl(Double value) {
        this.tzbl = value;
    }

    /**
     * Gets the value of the gjdqDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGjdqDm() {
        return gjdqDm;
    }

    /**
     * Sets the value of the gjdqDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGjdqDm(String value) {
        this.gjdqDm = value;
    }

}
