//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 申报表附加信息VO
 *
 * <p>Java class for sbbFjxxVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="sbbFjxxVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="swdlrdwmc" type="{http://www.chinatax.gov.cn/dataspec/}swdlrdwmc" minOccurs="0"/>
 *         &lt;element name="swdlrlxdh" type="{http://www.chinatax.gov.cn/dataspec/}swdlrlxdh" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sbbFjxxVO", propOrder = {
    "swdlrdwmc",
    "swdlrlxdh"
})
public class SbbFjxxVO {

    protected String swdlrdwmc;
    protected String swdlrlxdh;

    /**
     * Gets the value of the swdlrdwmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSwdlrdwmc() {
        return swdlrdwmc;
    }

    /**
     * Sets the value of the swdlrdwmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSwdlrdwmc(String value) {
        this.swdlrdwmc = value;
    }

    /**
     * Gets the value of the swdlrlxdh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSwdlrlxdh() {
        return swdlrlxdh;
    }

    /**
     * Sets the value of the swdlrlxdh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSwdlrlxdh(String value) {
        this.swdlrlxdh = value;
    }

}
