//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 申报表受理信息VO扩展2，增加办税人相关信息
 *
 * <p>Java class for sbbslxxkz2VO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="sbbslxxkz2VO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}sbbslxxVO">
 *       &lt;sequence>
 *         &lt;element name="bsy" type="{http://www.chinatax.gov.cn/dataspec/}bsy"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sbbslxxkz2VO", propOrder = {
    "bsy"
})
public class Sbbslxxkz2VO
    extends SbbslxxVO {

    @XmlElement(required = true)
    protected String bsy;

    /**
     * Gets the value of the bsy property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBsy() {
        return bsy;
    }

    /**
     * Sets the value of the bsy property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBsy(String value) {
        this.bsy = value;
    }

}
