//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 财产税更新底层返回VO
 *
 * <p>Java class for SBCcsGxdcReturnVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBCcsGxdcReturnVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sybh" type="{http://www.chinatax.gov.cn/dataspec/}sybh" minOccurs="0"/>
 *         &lt;element name="returnBz" type="{http://www.chinatax.gov.cn/dataspec/}bz"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBCcsGxdcReturnVO", propOrder = {
    "sybh",
    "returnBz"
})
public class SBCcsGxdcReturnVO {

    protected String sybh;
    @XmlElement(required = true)
    protected String returnBz;

    /**
     * Gets the value of the sybh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSybh() {
        return sybh;
    }

    /**
     * Sets the value of the sybh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSybh(String value) {
        this.sybh = value;
    }

    /**
     * Gets the value of the returnBz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReturnBz() {
        return returnBz;
    }

    /**
     * Sets the value of the returnBz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReturnBz(String value) {
        this.returnBz = value;
    }

}
