//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 非居民企业合同项目备案信息查询VO
 *
 * <p>Java class for SBFjmqyhtxmbaxxReturnVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBFjmqyhtxmbaxxReturnVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zwmc" type="{http://www.chinatax.gov.cn/dataspec/}zwmc"/>
 *         &lt;element name="ywmc" type="{http://www.chinatax.gov.cn/dataspec/}ywmc"/>
 *         &lt;element name="zqjmgnsrzwmc" type="{http://www.chinatax.gov.cn/dataspec/}zqjmgnsrzwmc"/>
 *         &lt;element name="zqjmgnsrywmc" type="{http://www.chinatax.gov.cn/dataspec/}zqjmgnsrywmc"/>
 *         &lt;element name="gjhdqzwqc" type="{http://www.chinatax.gov.cn/dataspec/}gjhdqzwqc"/>
 *         &lt;element name="nsrZqjmgzwdz" type="{http://www.chinatax.gov.cn/dataspec/}nsrZqjmgzwdz"/>
 *         &lt;element name="nsrZqjmgywdz" type="{http://www.chinatax.gov.cn/dataspec/}nsrZqjmgywdz"/>
 *         &lt;element name="hthxymc" type="{http://www.chinatax.gov.cn/dataspec/}hthxymc"/>
 *         &lt;element name="htbh" type="{http://www.chinatax.gov.cn/dataspec/}htbh"/>
 *         &lt;element name="htzxqssj" type="{http://www.chinatax.gov.cn/dataspec/}htzxqssj"/>
 *         &lt;element name="htzxzzsj" type="{http://www.chinatax.gov.cn/dataspec/}htzxzzsj"/>
 *         &lt;element name="htje" type="{http://www.chinatax.gov.cn/dataspec/}htje"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBFjmqyhtxmbaxxReturnVO", propOrder = {
    "zwmc",
    "ywmc",
    "zqjmgnsrzwmc",
    "zqjmgnsrywmc",
    "gjhdqzwqc",
    "nsrZqjmgzwdz",
    "nsrZqjmgywdz",
    "hthxymc",
    "htbh",
    "htzxqssj",
    "htzxzzsj",
    "htje"
})
public class SBFjmqyhtxmbaxxReturnVO {

    @XmlElement(required = true, nillable = true)
    protected String zwmc;
    @XmlElement(required = true, nillable = true)
    protected String ywmc;
    @XmlElement(required = true, nillable = true)
    protected String zqjmgnsrzwmc;
    @XmlElement(required = true, nillable = true)
    protected String zqjmgnsrywmc;
    @XmlElement(required = true, nillable = true)
    protected String gjhdqzwqc;
    @XmlElement(required = true, nillable = true)
    protected String nsrZqjmgzwdz;
    @XmlElement(required = true, nillable = true)
    protected String nsrZqjmgywdz;
    @XmlElement(required = true, nillable = true)
    protected String hthxymc;
    @XmlElement(required = true, nillable = true)
    protected String htbh;
    @XmlElement(required = true, nillable = true)
    protected String htzxqssj;
    @XmlElement(required = true, nillable = true)
    protected String htzxzzsj;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double htje;

    /**
     * Gets the value of the zwmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZwmc() {
        return zwmc;
    }

    /**
     * Sets the value of the zwmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZwmc(String value) {
        this.zwmc = value;
    }

    /**
     * Gets the value of the ywmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getYwmc() {
        return ywmc;
    }

    /**
     * Sets the value of the ywmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setYwmc(String value) {
        this.ywmc = value;
    }

    /**
     * Gets the value of the zqjmgnsrzwmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZqjmgnsrzwmc() {
        return zqjmgnsrzwmc;
    }

    /**
     * Sets the value of the zqjmgnsrzwmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZqjmgnsrzwmc(String value) {
        this.zqjmgnsrzwmc = value;
    }

    /**
     * Gets the value of the zqjmgnsrywmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZqjmgnsrywmc() {
        return zqjmgnsrywmc;
    }

    /**
     * Sets the value of the zqjmgnsrywmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZqjmgnsrywmc(String value) {
        this.zqjmgnsrywmc = value;
    }

    /**
     * Gets the value of the gjhdqzwqc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGjhdqzwqc() {
        return gjhdqzwqc;
    }

    /**
     * Sets the value of the gjhdqzwqc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGjhdqzwqc(String value) {
        this.gjhdqzwqc = value;
    }

    /**
     * Gets the value of the nsrZqjmgzwdz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNsrZqjmgzwdz() {
        return nsrZqjmgzwdz;
    }

    /**
     * Sets the value of the nsrZqjmgzwdz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNsrZqjmgzwdz(String value) {
        this.nsrZqjmgzwdz = value;
    }

    /**
     * Gets the value of the nsrZqjmgywdz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNsrZqjmgywdz() {
        return nsrZqjmgywdz;
    }

    /**
     * Sets the value of the nsrZqjmgywdz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNsrZqjmgywdz(String value) {
        this.nsrZqjmgywdz = value;
    }

    /**
     * Gets the value of the hthxymc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHthxymc() {
        return hthxymc;
    }

    /**
     * Sets the value of the hthxymc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHthxymc(String value) {
        this.hthxymc = value;
    }

    /**
     * Gets the value of the htbh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHtbh() {
        return htbh;
    }

    /**
     * Sets the value of the htbh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHtbh(String value) {
        this.htbh = value;
    }

    /**
     * Gets the value of the htzxqssj property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHtzxqssj() {
        return htzxqssj;
    }

    /**
     * Sets the value of the htzxqssj property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHtzxqssj(String value) {
        this.htzxqssj = value;
    }

    /**
     * Gets the value of the htzxzzsj property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHtzxzzsj() {
        return htzxzzsj;
    }

    /**
     * Sets the value of the htzxzzsj property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHtzxzzsj(String value) {
        this.htzxzzsj = value;
    }

    /**
     * Gets the value of the htje property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getHtje() {
        return htje;
    }

    /**
     * Sets the value of the htje property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setHtje(Double value) {
        this.htje = value;
    }

}
