//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 企业所得税汇总纳税分支机构分配表分支机构情况信息
 *
 * <p>Java class for SBQysdsfzjgxxVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBQysdsfzjgxxVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fzjgfpbfzjguuid" type="{http://www.chinatax.gov.cn/dataspec/}fzjgfpbfzjguuid"/>
 *         &lt;element name="pzxh" type="{http://www.chinatax.gov.cn/dataspec/}pzxh"/>
 *         &lt;element name="zjgnsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}zjgnsrsbh"/>
 *         &lt;element name="zjgdjxh" type="{http://www.chinatax.gov.cn/dataspec/}zjgdjxh"/>
 *         &lt;element name="fzjgnsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}nsrsbh"/>
 *         &lt;element name="fzjgdjxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="nsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}nsrsbh"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="fzjgmc" type="{http://www.chinatax.gov.cn/dataspec/}fzjgmc"/>
 *         &lt;element name="fzjglxlb" type="{http://www.chinatax.gov.cn/dataspec/}bz"/>
 *         &lt;element name="fzjgsrze" type="{http://www.chinatax.gov.cn/dataspec/}srze"/>
 *         &lt;element name="fzjggzze" type="{http://www.chinatax.gov.cn/dataspec/}gzze"/>
 *         &lt;element name="fzjgzcze" type="{http://www.chinatax.gov.cn/dataspec/}zcze"/>
 *         &lt;element name="fpbl" type="{http://www.chinatax.gov.cn/dataspec/}fpbl"/>
 *         &lt;element name="fpse" type="{http://www.chinatax.gov.cn/dataspec/}fzjgfpse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBQysdsfzjgxxVO", propOrder = {
    "fzjgfpbfzjguuid",
    "pzxh",
    "zjgnsrsbh",
    "zjgdjxh",
    "fzjgnsrsbh",
    "fzjgdjxh",
    "nsrsbh",
    "djxh",
    "fzjgmc",
    "fzjglxlb",
    "fzjgsrze",
    "fzjggzze",
    "fzjgzcze",
    "fpbl",
    "fpse"
})
public class SBQysdsfzjgxxVO {

    @XmlElement(required = true)
    protected String fzjgfpbfzjguuid;
    @XmlElement(required = true)
    protected String pzxh;
    @XmlElement(required = true)
    protected String zjgnsrsbh;
    @XmlElement(required = true)
    protected String zjgdjxh;
    @XmlElement(required = true)
    protected String fzjgnsrsbh;
    @XmlElement(required = true)
    protected String fzjgdjxh;
    @XmlElement(required = true)
    protected String nsrsbh;
    @XmlElement(required = true)
    protected String djxh;
    @XmlElement(required = true)
    protected String fzjgmc;
    @XmlElement(required = true)
    protected String fzjglxlb;
    protected double fzjgsrze;
    protected double fzjggzze;
    protected double fzjgzcze;
    protected double fpbl;
    protected double fpse;

    /**
     * Gets the value of the fzjgfpbfzjguuid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFzjgfpbfzjguuid() {
        return fzjgfpbfzjguuid;
    }

    /**
     * Sets the value of the fzjgfpbfzjguuid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFzjgfpbfzjguuid(String value) {
        this.fzjgfpbfzjguuid = value;
    }

    /**
     * Gets the value of the pzxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPzxh() {
        return pzxh;
    }

    /**
     * Sets the value of the pzxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPzxh(String value) {
        this.pzxh = value;
    }

    /**
     * Gets the value of the zjgnsrsbh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZjgnsrsbh() {
        return zjgnsrsbh;
    }

    /**
     * Sets the value of the zjgnsrsbh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZjgnsrsbh(String value) {
        this.zjgnsrsbh = value;
    }

    /**
     * Gets the value of the zjgdjxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZjgdjxh() {
        return zjgdjxh;
    }

    /**
     * Sets the value of the zjgdjxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZjgdjxh(String value) {
        this.zjgdjxh = value;
    }

    /**
     * Gets the value of the fzjgnsrsbh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFzjgnsrsbh() {
        return fzjgnsrsbh;
    }

    /**
     * Sets the value of the fzjgnsrsbh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFzjgnsrsbh(String value) {
        this.fzjgnsrsbh = value;
    }

    /**
     * Gets the value of the fzjgdjxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFzjgdjxh() {
        return fzjgdjxh;
    }

    /**
     * Sets the value of the fzjgdjxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFzjgdjxh(String value) {
        this.fzjgdjxh = value;
    }

    /**
     * Gets the value of the nsrsbh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNsrsbh() {
        return nsrsbh;
    }

    /**
     * Sets the value of the nsrsbh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNsrsbh(String value) {
        this.nsrsbh = value;
    }

    /**
     * Gets the value of the djxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the fzjgmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFzjgmc() {
        return fzjgmc;
    }

    /**
     * Sets the value of the fzjgmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFzjgmc(String value) {
        this.fzjgmc = value;
    }

    /**
     * Gets the value of the fzjglxlb property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFzjglxlb() {
        return fzjglxlb;
    }

    /**
     * Sets the value of the fzjglxlb property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFzjglxlb(String value) {
        this.fzjglxlb = value;
    }

    /**
     * Gets the value of the fzjgsrze property.
     *
     */
    public double getFzjgsrze() {
        return fzjgsrze;
    }

    /**
     * Sets the value of the fzjgsrze property.
     *
     */
    public void setFzjgsrze(double value) {
        this.fzjgsrze = value;
    }

    /**
     * Gets the value of the fzjggzze property.
     *
     */
    public double getFzjggzze() {
        return fzjggzze;
    }

    /**
     * Sets the value of the fzjggzze property.
     *
     */
    public void setFzjggzze(double value) {
        this.fzjggzze = value;
    }

    /**
     * Gets the value of the fzjgzcze property.
     *
     */
    public double getFzjgzcze() {
        return fzjgzcze;
    }

    /**
     * Sets the value of the fzjgzcze property.
     *
     */
    public void setFzjgzcze(double value) {
        this.fzjgzcze = value;
    }

    /**
     * Gets the value of the fpbl property.
     *
     */
    public double getFpbl() {
        return fpbl;
    }

    /**
     * Sets the value of the fpbl property.
     *
     */
    public void setFpbl(double value) {
        this.fpbl = value;
    }

    /**
     * Gets the value of the fpse property.
     *
     */
    public double getFpse() {
        return fpse;
    }

    /**
     * Sets the value of the fpse property.
     *
     */
    public void setFpse(double value) {
        this.fpse = value;
    }

}
