//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 居民企业企业所得税查账征收年度申报（2014）纳税人基本信息
 *
 * <p>Java class for SBQysdsczzsndsb2014NsrjbxxVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBQysdsczzsndsb2014NsrjbxxVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}nsrsbh"/>
 *         &lt;element name="nsrmc" type="{http://www.chinatax.gov.cn/dataspec/}nsrmc"/>
 *         &lt;element name="skssqq" type="{http://www.chinatax.gov.cn/dataspec/}skssqq"/>
 *         &lt;element name="skssqz" type="{http://www.chinatax.gov.cn/dataspec/}skssqz"/>
 *         &lt;element name="fddbr" type="{http://www.chinatax.gov.cn/dataspec/}fddbr" minOccurs="0"/>
 *         &lt;element name="kjzgmc" type="{http://www.chinatax.gov.cn/dataspec/}nsrmc" minOccurs="0"/>
 *         &lt;element name="sbrq1" type="{http://www.chinatax.gov.cn/dataspec/}sbrq1"/>
 *         &lt;element name="tbrq" type="{http://www.chinatax.gov.cn/dataspec/}tbrq" minOccurs="0"/>
 *         &lt;element name="hznsqy" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="zczb" type="{http://www.chinatax.gov.cn/dataspec/}zczb" minOccurs="0"/>
 *         &lt;element name="jwzzkgjmqy" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="sshyDm" type="{http://www.chinatax.gov.cn/dataspec/}sshyDm" minOccurs="0"/>
 *         &lt;element name="csgjfxzhjzhy" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="cyrs" type="{http://www.chinatax.gov.cn/dataspec/}nsrsbh" minOccurs="0"/>
 *         &lt;element name="czjwgljy" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="zcze" type="{http://www.chinatax.gov.cn/dataspec/}zcze" minOccurs="0"/>
 *         &lt;element name="ssgs" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="qykjzz" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="xqykjzz" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="qykjzd" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="sydwkjzz" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="mjfylzzkjzd" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="cjtjjzzkjzd" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="nmzyhzscwkjzd" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="kjzdqt" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="kjdacfd" type="{http://www.chinatax.gov.cn/dataspec/}dz" minOccurs="0"/>
 *         &lt;element name="kjhsrjmc" type="{http://www.chinatax.gov.cn/dataspec/}kjhsrjmc" minOccurs="0"/>
 *         &lt;element name="kjjzbb" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="kjzchgjsffsbh" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="gdzczjff" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="chcbjjff" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="hzsshsff" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="sdsjsff" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="yxbz" type="{http://www.chinatax.gov.cn/dataspec/}yxbz" minOccurs="0"/>
 *         &lt;element name="qysdsndsbtbb" type="{http://www.chinatax.gov.cn/dataspec/}bz1" minOccurs="0"/>
 *         &lt;element name="dljbrxm" type="{http://www.chinatax.gov.cn/dataspec/}nsrmc"/>
 *         &lt;element name="dljbrzjhm" type="{http://www.chinatax.gov.cn/dataspec/}zjhm"/>
 *         &lt;element name="dlsbrq" type="{http://www.chinatax.gov.cn/dataspec/}skssqq"/>
 *         &lt;element name="slrxm" type="{http://www.chinatax.gov.cn/dataspec/}nsrmc"/>
 *         &lt;element name="slrq" type="{http://www.chinatax.gov.cn/dataspec/}skssqq"/>
 *         &lt;element name="slswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}swjgDm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBQysdsczzsndsb2014NsrjbxxVO", propOrder = {
    "nsrsbh",
    "nsrmc",
    "skssqq",
    "skssqz",
    "fddbr",
    "kjzgmc",
    "sbrq1",
    "tbrq",
    "hznsqy",
    "zczb",
    "jwzzkgjmqy",
    "sshyDm",
    "csgjfxzhjzhy",
    "cyrs",
    "czjwgljy",
    "zcze",
    "ssgs",
    "qykjzz",
    "xqykjzz",
    "qykjzd",
    "sydwkjzz",
    "mjfylzzkjzd",
    "cjtjjzzkjzd",
    "nmzyhzscwkjzd",
    "kjzdqt",
    "kjdacfd",
    "kjhsrjmc",
    "kjjzbb",
    "kjzchgjsffsbh",
    "gdzczjff",
    "chcbjjff",
    "hzsshsff",
    "sdsjsff",
    "yxbz",
    "qysdsndsbtbb",
    "dljbrxm",
    "dljbrzjhm",
    "dlsbrq",
    "slrxm",
    "slrq",
    "slswjgDm"
})
public class SBQysdsczzsndsb2014NsrjbxxVO {

    @XmlElement(required = true)
    protected String nsrsbh;
    @XmlElement(required = true)
    protected String nsrmc;
    @XmlElement(required = true)
    protected String skssqq;
    @XmlElement(required = true)
    protected String skssqz;
    protected String fddbr;
    protected String kjzgmc;
    @XmlElement(required = true)
    protected String sbrq1;
    protected String tbrq;
    protected String hznsqy;
    protected Double zczb;
    protected String jwzzkgjmqy;
    protected String sshyDm;
    protected String csgjfxzhjzhy;
    protected String cyrs;
    protected String czjwgljy;
    protected Double zcze;
    protected String ssgs;
    protected String qykjzz;
    protected String xqykjzz;
    protected String qykjzd;
    protected String sydwkjzz;
    protected String mjfylzzkjzd;
    protected String cjtjjzzkjzd;
    protected String nmzyhzscwkjzd;
    protected String kjzdqt;
    protected String kjdacfd;
    protected String kjhsrjmc;
    protected String kjjzbb;
    protected String kjzchgjsffsbh;
    protected String gdzczjff;
    protected String chcbjjff;
    protected String hzsshsff;
    protected String sdsjsff;
    protected String yxbz;
    protected String qysdsndsbtbb;
    @XmlElement(required = true)
    protected String dljbrxm;
    @XmlElement(required = true)
    protected String dljbrzjhm;
    @XmlElement(required = true)
    protected String dlsbrq;
    @XmlElement(required = true)
    protected String slrxm;
    @XmlElement(required = true)
    protected String slrq;
    @XmlElement(required = true)
    protected String slswjgDm;

    /**
     * Gets the value of the nsrsbh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNsrsbh() {
        return nsrsbh;
    }

    /**
     * Sets the value of the nsrsbh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNsrsbh(String value) {
        this.nsrsbh = value;
    }

    /**
     * Gets the value of the nsrmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNsrmc() {
        return nsrmc;
    }

    /**
     * Sets the value of the nsrmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNsrmc(String value) {
        this.nsrmc = value;
    }

    /**
     * Gets the value of the skssqq property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSkssqq() {
        return skssqq;
    }

    /**
     * Sets the value of the skssqq property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSkssqq(String value) {
        this.skssqq = value;
    }

    /**
     * Gets the value of the skssqz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSkssqz() {
        return skssqz;
    }

    /**
     * Sets the value of the skssqz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSkssqz(String value) {
        this.skssqz = value;
    }

    /**
     * Gets the value of the fddbr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFddbr() {
        return fddbr;
    }

    /**
     * Sets the value of the fddbr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFddbr(String value) {
        this.fddbr = value;
    }

    /**
     * Gets the value of the kjzgmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKjzgmc() {
        return kjzgmc;
    }

    /**
     * Sets the value of the kjzgmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKjzgmc(String value) {
        this.kjzgmc = value;
    }

    /**
     * Gets the value of the sbrq1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSbrq1() {
        return sbrq1;
    }

    /**
     * Sets the value of the sbrq1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSbrq1(String value) {
        this.sbrq1 = value;
    }

    /**
     * Gets the value of the tbrq property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTbrq() {
        return tbrq;
    }

    /**
     * Sets the value of the tbrq property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTbrq(String value) {
        this.tbrq = value;
    }

    /**
     * Gets the value of the hznsqy property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHznsqy() {
        return hznsqy;
    }

    /**
     * Sets the value of the hznsqy property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHznsqy(String value) {
        this.hznsqy = value;
    }

    /**
     * Gets the value of the zczb property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getZczb() {
        return zczb;
    }

    /**
     * Sets the value of the zczb property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setZczb(Double value) {
        this.zczb = value;
    }

    /**
     * Gets the value of the jwzzkgjmqy property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getJwzzkgjmqy() {
        return jwzzkgjmqy;
    }

    /**
     * Sets the value of the jwzzkgjmqy property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setJwzzkgjmqy(String value) {
        this.jwzzkgjmqy = value;
    }

    /**
     * Gets the value of the sshyDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSshyDm() {
        return sshyDm;
    }

    /**
     * Sets the value of the sshyDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSshyDm(String value) {
        this.sshyDm = value;
    }

    /**
     * Gets the value of the csgjfxzhjzhy property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCsgjfxzhjzhy() {
        return csgjfxzhjzhy;
    }

    /**
     * Sets the value of the csgjfxzhjzhy property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCsgjfxzhjzhy(String value) {
        this.csgjfxzhjzhy = value;
    }

    /**
     * Gets the value of the cyrs property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCyrs() {
        return cyrs;
    }

    /**
     * Sets the value of the cyrs property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCyrs(String value) {
        this.cyrs = value;
    }

    /**
     * Gets the value of the czjwgljy property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCzjwgljy() {
        return czjwgljy;
    }

    /**
     * Sets the value of the czjwgljy property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCzjwgljy(String value) {
        this.czjwgljy = value;
    }

    /**
     * Gets the value of the zcze property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getZcze() {
        return zcze;
    }

    /**
     * Sets the value of the zcze property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setZcze(Double value) {
        this.zcze = value;
    }

    /**
     * Gets the value of the ssgs property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSsgs() {
        return ssgs;
    }

    /**
     * Sets the value of the ssgs property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSsgs(String value) {
        this.ssgs = value;
    }

    /**
     * Gets the value of the qykjzz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQykjzz() {
        return qykjzz;
    }

    /**
     * Sets the value of the qykjzz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQykjzz(String value) {
        this.qykjzz = value;
    }

    /**
     * Gets the value of the xqykjzz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getXqykjzz() {
        return xqykjzz;
    }

    /**
     * Sets the value of the xqykjzz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setXqykjzz(String value) {
        this.xqykjzz = value;
    }

    /**
     * Gets the value of the qykjzd property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQykjzd() {
        return qykjzd;
    }

    /**
     * Sets the value of the qykjzd property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQykjzd(String value) {
        this.qykjzd = value;
    }

    /**
     * Gets the value of the sydwkjzz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSydwkjzz() {
        return sydwkjzz;
    }

    /**
     * Sets the value of the sydwkjzz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSydwkjzz(String value) {
        this.sydwkjzz = value;
    }

    /**
     * Gets the value of the mjfylzzkjzd property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMjfylzzkjzd() {
        return mjfylzzkjzd;
    }

    /**
     * Sets the value of the mjfylzzkjzd property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMjfylzzkjzd(String value) {
        this.mjfylzzkjzd = value;
    }

    /**
     * Gets the value of the cjtjjzzkjzd property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCjtjjzzkjzd() {
        return cjtjjzzkjzd;
    }

    /**
     * Sets the value of the cjtjjzzkjzd property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCjtjjzzkjzd(String value) {
        this.cjtjjzzkjzd = value;
    }

    /**
     * Gets the value of the nmzyhzscwkjzd property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNmzyhzscwkjzd() {
        return nmzyhzscwkjzd;
    }

    /**
     * Sets the value of the nmzyhzscwkjzd property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNmzyhzscwkjzd(String value) {
        this.nmzyhzscwkjzd = value;
    }

    /**
     * Gets the value of the kjzdqt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKjzdqt() {
        return kjzdqt;
    }

    /**
     * Sets the value of the kjzdqt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKjzdqt(String value) {
        this.kjzdqt = value;
    }

    /**
     * Gets the value of the kjdacfd property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKjdacfd() {
        return kjdacfd;
    }

    /**
     * Sets the value of the kjdacfd property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKjdacfd(String value) {
        this.kjdacfd = value;
    }

    /**
     * Gets the value of the kjhsrjmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKjhsrjmc() {
        return kjhsrjmc;
    }

    /**
     * Sets the value of the kjhsrjmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKjhsrjmc(String value) {
        this.kjhsrjmc = value;
    }

    /**
     * Gets the value of the kjjzbb property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKjjzbb() {
        return kjjzbb;
    }

    /**
     * Sets the value of the kjjzbb property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKjjzbb(String value) {
        this.kjjzbb = value;
    }

    /**
     * Gets the value of the kjzchgjsffsbh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKjzchgjsffsbh() {
        return kjzchgjsffsbh;
    }

    /**
     * Sets the value of the kjzchgjsffsbh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKjzchgjsffsbh(String value) {
        this.kjzchgjsffsbh = value;
    }

    /**
     * Gets the value of the gdzczjff property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGdzczjff() {
        return gdzczjff;
    }

    /**
     * Sets the value of the gdzczjff property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGdzczjff(String value) {
        this.gdzczjff = value;
    }

    /**
     * Gets the value of the chcbjjff property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getChcbjjff() {
        return chcbjjff;
    }

    /**
     * Sets the value of the chcbjjff property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setChcbjjff(String value) {
        this.chcbjjff = value;
    }

    /**
     * Gets the value of the hzsshsff property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHzsshsff() {
        return hzsshsff;
    }

    /**
     * Sets the value of the hzsshsff property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHzsshsff(String value) {
        this.hzsshsff = value;
    }

    /**
     * Gets the value of the sdsjsff property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSdsjsff() {
        return sdsjsff;
    }

    /**
     * Sets the value of the sdsjsff property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSdsjsff(String value) {
        this.sdsjsff = value;
    }

    /**
     * Gets the value of the yxbz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getYxbz() {
        return yxbz;
    }

    /**
     * Sets the value of the yxbz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setYxbz(String value) {
        this.yxbz = value;
    }

    /**
     * Gets the value of the qysdsndsbtbb property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQysdsndsbtbb() {
        return qysdsndsbtbb;
    }

    /**
     * Sets the value of the qysdsndsbtbb property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQysdsndsbtbb(String value) {
        this.qysdsndsbtbb = value;
    }

    /**
     * Gets the value of the dljbrxm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDljbrxm() {
        return dljbrxm;
    }

    /**
     * Sets the value of the dljbrxm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDljbrxm(String value) {
        this.dljbrxm = value;
    }

    /**
     * Gets the value of the dljbrzjhm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDljbrzjhm() {
        return dljbrzjhm;
    }

    /**
     * Sets the value of the dljbrzjhm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDljbrzjhm(String value) {
        this.dljbrzjhm = value;
    }

    /**
     * Gets the value of the dlsbrq property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDlsbrq() {
        return dlsbrq;
    }

    /**
     * Sets the value of the dlsbrq property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDlsbrq(String value) {
        this.dlsbrq = value;
    }

    /**
     * Gets the value of the slrxm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSlrxm() {
        return slrxm;
    }

    /**
     * Sets the value of the slrxm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSlrxm(String value) {
        this.slrxm = value;
    }

    /**
     * Gets the value of the slrq property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSlrq() {
        return slrq;
    }

    /**
     * Sets the value of the slrq property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSlrq(String value) {
        this.slrq = value;
    }

    /**
     * Gets the value of the slswjgDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSlswjgDm() {
        return slswjgDm;
    }

    /**
     * Sets the value of the slswjgDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSlswjgDm(String value) {
        this.slswjgDm = value;
    }

}
