//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 企业所得税汇总纳税分支机构分配表总机构情况信息
 *
 * <p>Java class for SBQysdszjgxxVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBQysdszjgxxVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fzjgfpbzjguuid" type="{http://www.chinatax.gov.cn/dataspec/}fzjgfpbzjguuid"/>
 *         &lt;element name="pzxh" type="{http://www.chinatax.gov.cn/dataspec/}pzxh"/>
 *         &lt;element name="sbuuid" type="{http://www.chinatax.gov.cn/dataspec/}sbuuid"/>
 *         &lt;element name="skssqq" type="{http://www.chinatax.gov.cn/dataspec/}skssqq" minOccurs="0"/>
 *         &lt;element name="skssqz" type="{http://www.chinatax.gov.cn/dataspec/}skssqz" minOccurs="0"/>
 *         &lt;element name="zjgnsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}zjgnsrsbh" minOccurs="0"/>
 *         &lt;element name="zjgdjxh" type="{http://www.chinatax.gov.cn/dataspec/}zjgdjxh" minOccurs="0"/>
 *         &lt;element name="ynsdse" type="{http://www.chinatax.gov.cn/dataspec/}ynsdse" minOccurs="0"/>
 *         &lt;element name="zjgftsdse" type="{http://www.chinatax.gov.cn/dataspec/}zjgftsdse" minOccurs="0"/>
 *         &lt;element name="zjgczjzfpsdse" type="{http://www.chinatax.gov.cn/dataspec/}zjgczjzfpsdse" minOccurs="0"/>
 *         &lt;element name="fzjgftdsdse" type="{http://www.chinatax.gov.cn/dataspec/}fzjgftdsdse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBQysdszjgxxVO", propOrder = {
    "fzjgfpbzjguuid",
    "pzxh",
    "sbuuid",
    "skssqq",
    "skssqz",
    "zjgnsrsbh",
    "zjgdjxh",
    "ynsdse",
    "zjgftsdse",
    "zjgczjzfpsdse",
    "fzjgftdsdse"
})
public class SBQysdszjgxxVO {

    @XmlElement(required = true)
    protected String fzjgfpbzjguuid;
    @XmlElement(required = true)
    protected String pzxh;
    @XmlElement(required = true)
    protected String sbuuid;
    protected String skssqq;
    protected String skssqz;
    protected String zjgnsrsbh;
    protected String zjgdjxh;
    protected Double ynsdse;
    protected Double zjgftsdse;
    protected Double zjgczjzfpsdse;
    protected Double fzjgftdsdse;

    /**
     * Gets the value of the fzjgfpbzjguuid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFzjgfpbzjguuid() {
        return fzjgfpbzjguuid;
    }

    /**
     * Sets the value of the fzjgfpbzjguuid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFzjgfpbzjguuid(String value) {
        this.fzjgfpbzjguuid = value;
    }

    /**
     * Gets the value of the pzxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPzxh() {
        return pzxh;
    }

    /**
     * Sets the value of the pzxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPzxh(String value) {
        this.pzxh = value;
    }

    /**
     * Gets the value of the sbuuid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSbuuid() {
        return sbuuid;
    }

    /**
     * Sets the value of the sbuuid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSbuuid(String value) {
        this.sbuuid = value;
    }

    /**
     * Gets the value of the skssqq property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSkssqq() {
        return skssqq;
    }

    /**
     * Sets the value of the skssqq property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSkssqq(String value) {
        this.skssqq = value;
    }

    /**
     * Gets the value of the skssqz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSkssqz() {
        return skssqz;
    }

    /**
     * Sets the value of the skssqz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSkssqz(String value) {
        this.skssqz = value;
    }

    /**
     * Gets the value of the zjgnsrsbh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZjgnsrsbh() {
        return zjgnsrsbh;
    }

    /**
     * Sets the value of the zjgnsrsbh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZjgnsrsbh(String value) {
        this.zjgnsrsbh = value;
    }

    /**
     * Gets the value of the zjgdjxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZjgdjxh() {
        return zjgdjxh;
    }

    /**
     * Sets the value of the zjgdjxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZjgdjxh(String value) {
        this.zjgdjxh = value;
    }

    /**
     * Gets the value of the ynsdse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getYnsdse() {
        return ynsdse;
    }

    /**
     * Sets the value of the ynsdse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setYnsdse(Double value) {
        this.ynsdse = value;
    }

    /**
     * Gets the value of the zjgftsdse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getZjgftsdse() {
        return zjgftsdse;
    }

    /**
     * Sets the value of the zjgftsdse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setZjgftsdse(Double value) {
        this.zjgftsdse = value;
    }

    /**
     * Gets the value of the zjgczjzfpsdse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getZjgczjzfpsdse() {
        return zjgczjzfpsdse;
    }

    /**
     * Sets the value of the zjgczjzfpsdse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setZjgczjzfpsdse(Double value) {
        this.zjgczjzfpsdse = value;
    }

    /**
     * Gets the value of the fzjgftdsdse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getFzjgftdsdse() {
        return fzjgftdsdse;
    }

    /**
     * Sets the value of the fzjgftdsdse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setFzjgftdsdse(Double value) {
        this.fzjgftdsdse = value;
    }

}
