//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 申报保存返回数据信息
 *
 * <p>Java class for SBSaveReturnVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBSaveReturnVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pzxh" type="{http://www.chinatax.gov.cn/dataspec/}pzxh" minOccurs="0"/>
 *         &lt;element name="ybtse" type="{http://www.chinatax.gov.cn/dataspec/}ybtse" minOccurs="0"/>
 *         &lt;element name="returnBz" type="{http://www.chinatax.gov.cn/dataspec/}bz" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBSaveReturnVO", propOrder = {
    "pzxh",
    "ybtse",
    "returnBz"
})
public class SBSaveReturnVO {

    protected String pzxh;
    protected Double ybtse;
    protected String returnBz;

    /**
     * Gets the value of the pzxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPzxh() {
        return pzxh;
    }

    /**
     * Sets the value of the pzxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPzxh(String value) {
        this.pzxh = value;
    }

    /**
     * Gets the value of the ybtse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getYbtse() {
        return ybtse;
    }

    /**
     * Sets the value of the ybtse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setYbtse(Double value) {
        this.ybtse = value;
    }

    /**
     * Gets the value of the returnBz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReturnBz() {
        return returnBz;
    }

    /**
     * Sets the value of the returnBz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReturnBz(String value) {
        this.returnBz = value;
    }

}
