//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 社保费公用VO
 *
 * <p>Java class for SBSbfgyVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBSbfgyVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wylsh" type="{http://www.chinatax.gov.cn/dataspec/}yzpzxh" minOccurs="0"/>
 *         &lt;element name="yzpzxh" type="{http://www.chinatax.gov.cn/dataspec/}yzpzxh" minOccurs="0"/>
 *         &lt;element name="sfcgbz" type="{http://www.chinatax.gov.cn/dataspec/}sfbzDm" minOccurs="0"/>
 *         &lt;element name="zfrDm" type="{http://www.chinatax.gov.cn/dataspec/}zfrDm" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBSbfgyVO", propOrder = {
    "wylsh",
    "yzpzxh",
    "sfcgbz",
    "zfrDm"
})
public class SBSbfgyVO {

    protected String wylsh;
    protected String yzpzxh;
    protected String sfcgbz;
    protected String zfrDm;

    /**
     * Gets the value of the wylsh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWylsh() {
        return wylsh;
    }

    /**
     * Sets the value of the wylsh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWylsh(String value) {
        this.wylsh = value;
    }

    /**
     * Gets the value of the yzpzxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getYzpzxh() {
        return yzpzxh;
    }

    /**
     * Sets the value of the yzpzxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setYzpzxh(String value) {
        this.yzpzxh = value;
    }

    /**
     * Gets the value of the sfcgbz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSfcgbz() {
        return sfcgbz;
    }

    /**
     * Sets the value of the sfcgbz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSfcgbz(String value) {
        this.sfcgbz = value;
    }

    /**
     * Gets the value of the zfrDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZfrDm() {
        return zfrDm;
    }

    /**
     * Sets the value of the zfrDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZfrDm(String value) {
        this.zfrDm = value;
    }

}
