//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 申报纳税人申报保存提交数据信息对象
 *
 * <p>Java class for SBSbxxTjVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBSbxxTjVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rdpzuuid" type="{http://www.chinatax.gov.cn/dataspec/}rdpzuuid" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBSbxxTjVO", propOrder = {
    "rdpzuuid"
})
public class SBSbxxTjVO {

    protected String rdpzuuid;

    /**
     * Gets the value of the rdpzuuid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRdpzuuid() {
        return rdpzuuid;
    }

    /**
     * Sets the value of the rdpzuuid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRdpzuuid(String value) {
        this.rdpzuuid = value;
    }

}
