//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 申报情况明细返回VO
 *
 * <p>Java class for SBsbqkmxReturnVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBsbqkmxReturnVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="yzpzxh" type="{http://www.chinatax.gov.cn/dataspec/}yzpzxh"/>
 *         &lt;element name="yzpzmxxh" type="{http://www.chinatax.gov.cn/dataspec/}yzpzxh"/>
 *         &lt;element name="zsxmDm" type="{http://www.chinatax.gov.cn/dataspec/}zsxmDm"/>
 *         &lt;element name="zspmDm" type="{http://www.chinatax.gov.cn/dataspec/}zspmDm"/>
 *         &lt;element name="skssqq" type="{http://www.chinatax.gov.cn/dataspec/}skssqq"/>
 *         &lt;element name="skssqz" type="{http://www.chinatax.gov.cn/dataspec/}skssqz"/>
 *         &lt;element name="sbje" type="{http://www.chinatax.gov.cn/dataspec/}sbje"/>
 *         &lt;element name="sl" type="{http://www.chinatax.gov.cn/dataspec/}sl"/>
 *         &lt;element name="ynse" type="{http://www.chinatax.gov.cn/dataspec/}ynse"/>
 *         &lt;element name="ybtse" type="{http://www.chinatax.gov.cn/dataspec/}ybtse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBsbqkmxReturnVO", propOrder = {
    "yzpzxh",
    "yzpzmxxh",
    "zsxmDm",
    "zspmDm",
    "skssqq",
    "skssqz",
    "sbje",
    "sl",
    "ynse",
    "ybtse"
})
public class SBsbqkmxReturnVO {

    @XmlElement(required = true, nillable = true)
    protected String yzpzxh;
    @XmlElement(required = true, nillable = true)
    protected String yzpzmxxh;
    @XmlElement(required = true, nillable = true)
    protected String zsxmDm;
    @XmlElement(required = true, nillable = true)
    protected String zspmDm;
    @XmlElement(required = true, nillable = true)
    protected String skssqq;
    @XmlElement(required = true, nillable = true)
    protected String skssqz;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double sbje;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double sl;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ynse;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ybtse;

    /**
     * Gets the value of the yzpzxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getYzpzxh() {
        return yzpzxh;
    }

    /**
     * Sets the value of the yzpzxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setYzpzxh(String value) {
        this.yzpzxh = value;
    }

    /**
     * Gets the value of the yzpzmxxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getYzpzmxxh() {
        return yzpzmxxh;
    }

    /**
     * Sets the value of the yzpzmxxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setYzpzmxxh(String value) {
        this.yzpzmxxh = value;
    }

    /**
     * Gets the value of the zsxmDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZsxmDm() {
        return zsxmDm;
    }

    /**
     * Sets the value of the zsxmDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZsxmDm(String value) {
        this.zsxmDm = value;
    }

    /**
     * Gets the value of the zspmDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZspmDm() {
        return zspmDm;
    }

    /**
     * Sets the value of the zspmDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZspmDm(String value) {
        this.zspmDm = value;
    }

    /**
     * Gets the value of the skssqq property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSkssqq() {
        return skssqq;
    }

    /**
     * Sets the value of the skssqq property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSkssqq(String value) {
        this.skssqq = value;
    }

    /**
     * Gets the value of the skssqz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSkssqz() {
        return skssqz;
    }

    /**
     * Sets the value of the skssqz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSkssqz(String value) {
        this.skssqz = value;
    }

    /**
     * Gets the value of the sbje property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getSbje() {
        return sbje;
    }

    /**
     * Sets the value of the sbje property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setSbje(Double value) {
        this.sbje = value;
    }

    /**
     * Gets the value of the sl property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getSl() {
        return sl;
    }

    /**
     * Sets the value of the sl property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setSl(Double value) {
        this.sl = value;
    }

    /**
     * Gets the value of the ynse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getYnse() {
        return ynse;
    }

    /**
     * Sets the value of the ynse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setYnse(Double value) {
        this.ynse = value;
    }

    /**
     * Gets the value of the ybtse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getYbtse() {
        return ybtse;
    }

    /**
     * Sets the value of the ybtse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setYbtse(Double value) {
        this.ybtse = value;
    }

}
