//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 税源申报信息返回VO
 *
 * <p>Java class for SBSysbxxReturnVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBSysbxxReturnVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zfbz" type="{http://www.chinatax.gov.cn/dataspec/}zfbz"/>
 *         &lt;element name="sbfsDm" type="{http://www.chinatax.gov.cn/dataspec/}sbfsDm"/>
 *         &lt;element name="sybh1" type="{http://www.chinatax.gov.cn/dataspec/}sybh1"/>
 *         &lt;element name="ybtse" type="{http://www.chinatax.gov.cn/dataspec/}ybtse"/>
 *         &lt;element name="sbrq" type="{http://www.chinatax.gov.cn/dataspec/}sbrq"/>
 *         &lt;element name="nsrsbztDm" type="{http://www.chinatax.gov.cn/dataspec/}nsrsbztDm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBSysbxxReturnVO", propOrder = {
    "zfbz",
    "sbfsDm",
    "sybh1",
    "ybtse",
    "sbrq",
    "nsrsbztDm"
})
public class SBSysbxxReturnVO {

    protected double zfbz;
    @XmlElement(required = true)
    protected String sbfsDm;
    @XmlElement(required = true)
    protected String sybh1;
    protected double ybtse;
    @XmlElement(required = true)
    protected String sbrq;
    @XmlElement(required = true)
    protected String nsrsbztDm;

    /**
     * Gets the value of the zfbz property.
     *
     */
    public double getZfbz() {
        return zfbz;
    }

    /**
     * Sets the value of the zfbz property.
     *
     */
    public void setZfbz(double value) {
        this.zfbz = value;
    }

    /**
     * Gets the value of the sbfsDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSbfsDm() {
        return sbfsDm;
    }

    /**
     * Sets the value of the sbfsDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSbfsDm(String value) {
        this.sbfsDm = value;
    }

    /**
     * Gets the value of the sybh1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSybh1() {
        return sybh1;
    }

    /**
     * Sets the value of the sybh1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSybh1(String value) {
        this.sybh1 = value;
    }

    /**
     * Gets the value of the ybtse property.
     *
     */
    public double getYbtse() {
        return ybtse;
    }

    /**
     * Sets the value of the ybtse property.
     *
     */
    public void setYbtse(double value) {
        this.ybtse = value;
    }

    /**
     * Gets the value of the sbrq property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSbrq() {
        return sbrq;
    }

    /**
     * Sets the value of the sbrq property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSbrq(String value) {
        this.sbrq = value;
    }

    /**
     * Gets the value of the nsrsbztDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNsrsbztDm() {
        return nsrsbztDm;
    }

    /**
     * Sets the value of the nsrsbztDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNsrsbztDm(String value) {
        this.nsrsbztDm = value;
    }

}
