//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 税源申报信息查询VO
 *
 * <p>Java class for SBSysbxxQueryVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBSysbxxQueryVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="skssqq" type="{http://www.chinatax.gov.cn/dataspec/}skssqq"/>
 *         &lt;element name="skssqz" type="{http://www.chinatax.gov.cn/dataspec/}skssqz"/>
 *         &lt;element name="zsxmDm" type="{http://www.chinatax.gov.cn/dataspec/}zsxmDm"/>
 *         &lt;element name="zspmDm" type="{http://www.chinatax.gov.cn/dataspec/}zspmDm"/>
 *         &lt;element name="yzpzzlDm" type="{http://www.chinatax.gov.cn/dataspec/}yzpzzlDm"/>
 *         &lt;element name="sybh1" type="{http://www.chinatax.gov.cn/dataspec/}sybh1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBSysbxxQueryVO", propOrder = {
    "djxh",
    "skssqq",
    "skssqz",
    "zsxmDm",
    "zspmDm",
    "yzpzzlDm",
    "sybh1"
})
public class SBSysbxxQueryVO {

    @XmlElement(required = true, nillable = true)
    protected String djxh;
    @XmlElement(required = true, nillable = true)
    protected String skssqq;
    @XmlElement(required = true, nillable = true)
    protected String skssqz;
    @XmlElement(required = true, nillable = true)
    protected String zsxmDm;
    @XmlElement(required = true, nillable = true)
    protected String zspmDm;
    @XmlElement(required = true, nillable = true)
    protected String yzpzzlDm;
    @XmlElement(required = true, nillable = true)
    protected String sybh1;

    /**
     * Gets the value of the djxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the skssqq property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSkssqq() {
        return skssqq;
    }

    /**
     * Sets the value of the skssqq property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSkssqq(String value) {
        this.skssqq = value;
    }

    /**
     * Gets the value of the skssqz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSkssqz() {
        return skssqz;
    }

    /**
     * Sets the value of the skssqz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSkssqz(String value) {
        this.skssqz = value;
    }

    /**
     * Gets the value of the zsxmDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZsxmDm() {
        return zsxmDm;
    }

    /**
     * Sets the value of the zsxmDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZsxmDm(String value) {
        this.zsxmDm = value;
    }

    /**
     * Gets the value of the zspmDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZspmDm() {
        return zspmDm;
    }

    /**
     * Sets the value of the zspmDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZspmDm(String value) {
        this.zspmDm = value;
    }

    /**
     * Gets the value of the yzpzzlDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getYzpzzlDm() {
        return yzpzzlDm;
    }

    /**
     * Sets the value of the yzpzzlDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setYzpzzlDm(String value) {
        this.yzpzzlDm = value;
    }

    /**
     * Gets the value of the sybh1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSybh1() {
        return sybh1;
    }

    /**
     * Sets the value of the sybh1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSybh1(String value) {
        this.sybh1 = value;
    }

}
