//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 消费税新牌号新规格卷烟信息汇总表VO
 *
 * <p>Java class for SBXfsxphxggjyhzVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBXfsxphxggjyhzVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scqy" type="{http://www.chinatax.gov.cn/dataspec/}scqy"/>
 *         &lt;element name="jyphgg" type="{http://www.chinatax.gov.cn/dataspec/}jyphgg"/>
 *         &lt;element name="jylbDm1" type="{http://www.chinatax.gov.cn/dataspec/}jylbDm1"/>
 *         &lt;element name="jytbzsptm" type="{http://www.chinatax.gov.cn/dataspec/}jytbzsptm"/>
 *         &lt;element name="dbjg" type="{http://www.chinatax.gov.cn/dataspec/}dbjg"/>
 *         &lt;element name="pfjg" type="{http://www.chinatax.gov.cn/dataspec/}pfjg"/>
 *         &lt;element name="jsjg" type="{http://www.chinatax.gov.cn/dataspec/}jsjg"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBXfsxphxggjyhzVO", propOrder = {
    "scqy",
    "jyphgg",
    "jylbDm1",
    "jytbzsptm",
    "dbjg",
    "pfjg",
    "jsjg"
})
public class SBXfsxphxggjyhzVO {

    @XmlElement(required = true)
    protected String scqy;
    @XmlElement(required = true)
    protected String jyphgg;
    @XmlElement(required = true)
    protected String jylbDm1;
    @XmlElement(required = true)
    protected String jytbzsptm;
    protected double dbjg;
    protected double pfjg;
    protected double jsjg;

    /**
     * Gets the value of the scqy property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getScqy() {
        return scqy;
    }

    /**
     * Sets the value of the scqy property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setScqy(String value) {
        this.scqy = value;
    }

    /**
     * Gets the value of the jyphgg property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getJyphgg() {
        return jyphgg;
    }

    /**
     * Sets the value of the jyphgg property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setJyphgg(String value) {
        this.jyphgg = value;
    }

    /**
     * Gets the value of the jylbDm1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getJylbDm1() {
        return jylbDm1;
    }

    /**
     * Sets the value of the jylbDm1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setJylbDm1(String value) {
        this.jylbDm1 = value;
    }

    /**
     * Gets the value of the jytbzsptm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getJytbzsptm() {
        return jytbzsptm;
    }

    /**
     * Sets the value of the jytbzsptm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setJytbzsptm(String value) {
        this.jytbzsptm = value;
    }

    /**
     * Gets the value of the dbjg property.
     *
     */
    public double getDbjg() {
        return dbjg;
    }

    /**
     * Sets the value of the dbjg property.
     *
     */
    public void setDbjg(double value) {
        this.dbjg = value;
    }

    /**
     * Gets the value of the pfjg property.
     *
     */
    public double getPfjg() {
        return pfjg;
    }

    /**
     * Sets the value of the pfjg property.
     *
     */
    public void setPfjg(double value) {
        this.pfjg = value;
    }

    /**
     * Gets the value of the jsjg property.
     *
     */
    public double getJsjg() {
        return jsjg;
    }

    /**
     * Sets the value of the jsjg property.
     *
     */
    public void setJsjg(double value) {
        this.jsjg = value;
    }

}
