//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 消费税申报数据信息扩展2VO
 *
 * <p>Java class for SBXfssbsjxxkz2VO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBXfssbsjxxkz2VO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xfssbblxDm" type="{http://www.chinatax.gov.cn/dataspec/}xfssbblxDm"/>
 *         &lt;element name="qcwjse" type="{http://www.chinatax.gov.cn/dataspec/}qcwjse"/>
 *         &lt;element name="bqjnqqynse" type="{http://www.chinatax.gov.cn/dataspec/}bqjnqqynse"/>
 *         &lt;element name="bqyjse" type="{http://www.chinatax.gov.cn/dataspec/}bqyjse"/>
 *         &lt;element name="bqybtse" type="{http://www.chinatax.gov.cn/dataspec/}bqybtse"/>
 *         &lt;element name="qmwjse" type="{http://www.chinatax.gov.cn/dataspec/}qmwjse"/>
 *         &lt;element name="bqzykcse" type="{http://www.chinatax.gov.cn/dataspec/}bqzykcse"/>
 *         &lt;element name="bqjmse" type="{http://www.chinatax.gov.cn/dataspec/}bqjmse"/>
 *         &lt;element name="qcldse" type="{http://www.chinatax.gov.cn/dataspec/}qcldse"/>
 *         &lt;element name="bqydkse" type="{http://www.chinatax.gov.cn/dataspec/}bqydkse"/>
 *         &lt;element name="qmldse" type="{http://www.chinatax.gov.cn/dataspec/}qmldse"/>
 *         &lt;element name="bqsjdkse" type="{http://www.chinatax.gov.cn/dataspec/}bqsjdkse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBXfssbsjxxkz2VO", propOrder = {
    "xfssbblxDm",
    "qcwjse",
    "bqjnqqynse",
    "bqyjse",
    "bqybtse",
    "qmwjse",
    "bqzykcse",
    "bqjmse",
    "qcldse",
    "bqydkse",
    "qmldse",
    "bqsjdkse"
})
public class SBXfssbsjxxkz2VO {

    @XmlElement(required = true)
    protected String xfssbblxDm;
    protected double qcwjse;
    protected double bqjnqqynse;
    protected double bqyjse;
    protected double bqybtse;
    protected double qmwjse;
    protected double bqzykcse;
    protected double bqjmse;
    protected double qcldse;
    protected double bqydkse;
    protected double qmldse;
    protected double bqsjdkse;

    /**
     * Gets the value of the xfssbblxDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getXfssbblxDm() {
        return xfssbblxDm;
    }

    /**
     * Sets the value of the xfssbblxDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setXfssbblxDm(String value) {
        this.xfssbblxDm = value;
    }

    /**
     * Gets the value of the qcwjse property.
     *
     */
    public double getQcwjse() {
        return qcwjse;
    }

    /**
     * Sets the value of the qcwjse property.
     *
     */
    public void setQcwjse(double value) {
        this.qcwjse = value;
    }

    /**
     * Gets the value of the bqjnqqynse property.
     *
     */
    public double getBqjnqqynse() {
        return bqjnqqynse;
    }

    /**
     * Sets the value of the bqjnqqynse property.
     *
     */
    public void setBqjnqqynse(double value) {
        this.bqjnqqynse = value;
    }

    /**
     * Gets the value of the bqyjse property.
     *
     */
    public double getBqyjse() {
        return bqyjse;
    }

    /**
     * Sets the value of the bqyjse property.
     *
     */
    public void setBqyjse(double value) {
        this.bqyjse = value;
    }

    /**
     * Gets the value of the bqybtse property.
     *
     */
    public double getBqybtse() {
        return bqybtse;
    }

    /**
     * Sets the value of the bqybtse property.
     *
     */
    public void setBqybtse(double value) {
        this.bqybtse = value;
    }

    /**
     * Gets the value of the qmwjse property.
     *
     */
    public double getQmwjse() {
        return qmwjse;
    }

    /**
     * Sets the value of the qmwjse property.
     *
     */
    public void setQmwjse(double value) {
        this.qmwjse = value;
    }

    /**
     * Gets the value of the bqzykcse property.
     *
     */
    public double getBqzykcse() {
        return bqzykcse;
    }

    /**
     * Sets the value of the bqzykcse property.
     *
     */
    public void setBqzykcse(double value) {
        this.bqzykcse = value;
    }

    /**
     * Gets the value of the bqjmse property.
     *
     */
    public double getBqjmse() {
        return bqjmse;
    }

    /**
     * Sets the value of the bqjmse property.
     *
     */
    public void setBqjmse(double value) {
        this.bqjmse = value;
    }

    /**
     * Gets the value of the qcldse property.
     *
     */
    public double getQcldse() {
        return qcldse;
    }

    /**
     * Sets the value of the qcldse property.
     *
     */
    public void setQcldse(double value) {
        this.qcldse = value;
    }

    /**
     * Gets the value of the bqydkse property.
     *
     */
    public double getBqydkse() {
        return bqydkse;
    }

    /**
     * Sets the value of the bqydkse property.
     *
     */
    public void setBqydkse(double value) {
        this.bqydkse = value;
    }

    /**
     * Gets the value of the qmldse property.
     *
     */
    public double getQmldse() {
        return qmldse;
    }

    /**
     * Sets the value of the qmldse property.
     *
     */
    public void setQmldse(double value) {
        this.qmldse = value;
    }

    /**
     * Gets the value of the bqsjdkse property.
     *
     */
    public double getBqsjdkse() {
        return bqsjdkse;
    }

    /**
     * Sets the value of the bqsjdkse property.
     *
     */
    public void setBqsjdkse(double value) {
        this.bqsjdkse = value;
    }

}
