//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 消费税申报应税项目信息VO
 *
 * <p>Java class for SBXfssbysxmVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBXfssbysxmVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ewbhxh" type="{http://www.chinatax.gov.cn/dataspec/}ewbhxh"/>
 *         &lt;element name="zspmDm" type="{http://www.chinatax.gov.cn/dataspec/}zspmDm"/>
 *         &lt;element name="sl1" type="{http://www.chinatax.gov.cn/dataspec/}sl1"/>
 *         &lt;element name="xssl" type="{http://www.chinatax.gov.cn/dataspec/}xssl"/>
 *         &lt;element name="xse" type="{http://www.chinatax.gov.cn/dataspec/}xse"/>
 *         &lt;element name="ynse" type="{http://www.chinatax.gov.cn/dataspec/}ynse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBXfssbysxmVO", propOrder = {
    "ewbhxh",
    "zspmDm",
    "sl1",
    "xssl",
    "xse",
    "ynse"
})
public class SBXfssbysxmVO {

    protected long ewbhxh;
    @XmlElement(required = true)
    protected String zspmDm;
    protected double sl1;
    protected double xssl;
    protected double xse;
    protected double ynse;

    /**
     * Gets the value of the ewbhxh property.
     *
     */
    public long getEwbhxh() {
        return ewbhxh;
    }

    /**
     * Sets the value of the ewbhxh property.
     *
     */
    public void setEwbhxh(long value) {
        this.ewbhxh = value;
    }

    /**
     * Gets the value of the zspmDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZspmDm() {
        return zspmDm;
    }

    /**
     * Sets the value of the zspmDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZspmDm(String value) {
        this.zspmDm = value;
    }

    /**
     * Gets the value of the sl1 property.
     *
     */
    public double getSl1() {
        return sl1;
    }

    /**
     * Sets the value of the sl1 property.
     *
     */
    public void setSl1(double value) {
        this.sl1 = value;
    }

    /**
     * Gets the value of the xssl property.
     *
     */
    public double getXssl() {
        return xssl;
    }

    /**
     * Sets the value of the xssl property.
     *
     */
    public void setXssl(double value) {
        this.xssl = value;
    }

    /**
     * Gets the value of the xse property.
     *
     */
    public double getXse() {
        return xse;
    }

    /**
     * Sets the value of the xse property.
     *
     */
    public void setXse(double value) {
        this.xse = value;
    }

    /**
     * Gets the value of the ynse property.
     *
     */
    public double getYnse() {
        return ynse;
    }

    /**
     * Sets the value of the ynse property.
     *
     */
    public void setYnse(double value) {
        this.ynse = value;
    }

}
