//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 消费税申报生产经营情况表VO
 *
 * <p>Java class for SBXfsscjyqkbVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBXfsscjyqkbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ewblxh" type="{http://www.chinatax.gov.cn/dataspec/}ewblxh"/>
 *         &lt;element name="zspmDm" type="{http://www.chinatax.gov.cn/dataspec/}zspmDm"/>
 *         &lt;element name="scsl" type="{http://www.chinatax.gov.cn/dataspec/}scsl"/>
 *         &lt;element name="xssl" type="{http://www.chinatax.gov.cn/dataspec/}xssl"/>
 *         &lt;element name="wtjgshysxfpzjxssl" type="{http://www.chinatax.gov.cn/dataspec/}wtjgshysxfpzjxssl"/>
 *         &lt;element name="wtjgshysxfpzjxse" type="{http://www.chinatax.gov.cn/dataspec/}wtjgshysxfpzjxse"/>
 *         &lt;element name="ckmsxssl" type="{http://www.chinatax.gov.cn/dataspec/}ckmsxssl"/>
 *         &lt;element name="ckmsxse" type="{http://www.chinatax.gov.cn/dataspec/}ckmsxse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBXfsscjyqkbVO", propOrder = {
    "ewblxh",
    "zspmDm",
    "scsl",
    "xssl",
    "wtjgshysxfpzjxssl",
    "wtjgshysxfpzjxse",
    "ckmsxssl",
    "ckmsxse"
})
public class SBXfsscjyqkbVO {

    protected long ewblxh;
    @XmlElement(required = true)
    protected String zspmDm;
    protected double scsl;
    protected double xssl;
    protected double wtjgshysxfpzjxssl;
    protected double wtjgshysxfpzjxse;
    protected double ckmsxssl;
    protected double ckmsxse;

    /**
     * Gets the value of the ewblxh property.
     *
     */
    public long getEwblxh() {
        return ewblxh;
    }

    /**
     * Sets the value of the ewblxh property.
     *
     */
    public void setEwblxh(long value) {
        this.ewblxh = value;
    }

    /**
     * Gets the value of the zspmDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZspmDm() {
        return zspmDm;
    }

    /**
     * Sets the value of the zspmDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZspmDm(String value) {
        this.zspmDm = value;
    }

    /**
     * Gets the value of the scsl property.
     *
     */
    public double getScsl() {
        return scsl;
    }

    /**
     * Sets the value of the scsl property.
     *
     */
    public void setScsl(double value) {
        this.scsl = value;
    }

    /**
     * Gets the value of the xssl property.
     *
     */
    public double getXssl() {
        return xssl;
    }

    /**
     * Sets the value of the xssl property.
     *
     */
    public void setXssl(double value) {
        this.xssl = value;
    }

    /**
     * Gets the value of the wtjgshysxfpzjxssl property.
     *
     */
    public double getWtjgshysxfpzjxssl() {
        return wtjgshysxfpzjxssl;
    }

    /**
     * Sets the value of the wtjgshysxfpzjxssl property.
     *
     */
    public void setWtjgshysxfpzjxssl(double value) {
        this.wtjgshysxfpzjxssl = value;
    }

    /**
     * Gets the value of the wtjgshysxfpzjxse property.
     *
     */
    public double getWtjgshysxfpzjxse() {
        return wtjgshysxfpzjxse;
    }

    /**
     * Sets the value of the wtjgshysxfpzjxse property.
     *
     */
    public void setWtjgshysxfpzjxse(double value) {
        this.wtjgshysxfpzjxse = value;
    }

    /**
     * Gets the value of the ckmsxssl property.
     *
     */
    public double getCkmsxssl() {
        return ckmsxssl;
    }

    /**
     * Sets the value of the ckmsxssl property.
     *
     */
    public void setCkmsxssl(double value) {
        this.ckmsxssl = value;
    }

    /**
     * Gets the value of the ckmsxse property.
     *
     */
    public double getCkmsxse() {
        return ckmsxse;
    }

    /**
     * Sets the value of the ckmsxse property.
     *
     */
    public void setCkmsxse(double value) {
        this.ckmsxse = value;
    }

}
