////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2015.08.28 at 06:10:39 PM CST
////
//
//
package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "SBYjxxJhVO",
        propOrder = {"yjskuuid", "zsxmDm", "zspmDm", "djxh", "skssqq", "skssqz", "yjze", "yjye1", "sksxDm", "zgswskfjDm", "sjgsdq", "hyDm"}
)
public class SBYjxxJhVO {
    @XmlElement(
            name = "yjskuuid",
            required = true,
            nillable = true
    )
    protected String yjskuuid;
    @XmlElement(
            name = "zsxmDm",
            required = true,
            nillable = true
    )
    protected String zsxmDm;
    @XmlElement(
            name = "zspmDm",
            required = true,
            nillable = true
    )
    protected String zspmDm;
    @XmlElement(
            name = "djxh",
            required = true,
            nillable = true
    )
    protected String djxh;
    @XmlElement(
            name = "skssqq",
            required = true,
            nillable = true
    )
    protected String skssqq;
    @XmlElement(
            name = "skssqz",
            required = true,
            nillable = true
    )
    protected String skssqz;
    @XmlElement(
            name = "yjze",
            required = true,
            type = Double.class,
            nillable = true
    )
    protected Double yjze;
    @XmlElement(
            name = "yjye1",
            required = true,
            type = Double.class,
            nillable = true
    )
    protected Double yjye1;
    @XmlElement(
            name = "sksxDm",
            required = true,
            nillable = true
    )
    protected String sksxDm;
    @XmlElement(
            name = "zgswskfjDm",
            required = true,
            nillable = true
    )
    protected String zgswskfjDm;
    @XmlElement(
            name = "sjgsdq",
            required = true,
            nillable = true
    )
    protected String sjgsdq;
    @XmlElement(
            name = "hyDm",
            required = true,
            nillable = true
    )
    protected String hyDm;

    public SBYjxxJhVO() {
    }

    public String getYjskuuid() {
        return this.yjskuuid;
    }

    public void setYjskuuid(String value) {
        this.yjskuuid = value;
    }

    public String getZsxmDm() {
        return this.zsxmDm;
    }

    public void setZsxmDm(String value) {
        this.zsxmDm = value;
    }

    public String getZspmDm() {
        return this.zspmDm;
    }

    public void setZspmDm(String value) {
        this.zspmDm = value;
    }

    public String getDjxh() {
        return this.djxh;
    }

    public void setDjxh(String value) {
        this.djxh = value;
    }

    public String getSkssqq() {
        return this.skssqq;
    }

    public void setSkssqq(String value) {
        this.skssqq = value;
    }

    public String getSkssqz() {
        return this.skssqz;
    }

    public void setSkssqz(String value) {
        this.skssqz = value;
    }

    public Double getYjze() {
        return this.yjze;
    }

    public void setYjze(Double value) {
        this.yjze = value;
    }

    public Double getYjye1() {
        return this.yjye1;
    }

    public void setYjye1(Double value) {
        this.yjye1 = value;
    }

    public String getSksxDm() {
        return this.sksxDm;
    }

    public void setSksxDm(String value) {
        this.sksxDm = value;
    }

    public String getZgswskfjDm() {
        return this.zgswskfjDm;
    }

    public void setZgswskfjDm(String value) {
        this.zgswskfjDm = value;
    }

    public String getSjgsdq() {
        return this.sjgsdq;
    }

    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    public String getHyDm() {
        return this.hyDm;
    }

    public void setHyDm(String value) {
        this.hyDm = value;
    }
}

//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * 申报纳税人预缴数据信息对象
// *
// * <p>Java class for SBYjxxJhVO complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="SBYjxxJhVO">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="yjskuuid" type="{http://www.chinatax.gov.cn/dataspec/}yjskuuid"/>
// *         &lt;element name="zsxmDm" type="{http://www.chinatax.gov.cn/dataspec/}zsxmDm"/>
// *         &lt;element name="zspmDm" type="{http://www.chinatax.gov.cn/dataspec/}zspmDm"/>
// *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
// *         &lt;element name="skssqq" type="{http://www.chinatax.gov.cn/dataspec/}skssqq"/>
// *         &lt;element name="skssqz" type="{http://www.chinatax.gov.cn/dataspec/}skssqz"/>
// *         &lt;element name="yjze" type="{http://www.chinatax.gov.cn/dataspec/}yjze"/>
// *         &lt;element name="yjye" type="{http://www.chinatax.gov.cn/dataspec/}yjye"/>
// *         &lt;element name="sksxDm" type="{http://www.chinatax.gov.cn/dataspec/}sksxDm"/>
// *         &lt;element name="zgswskfjDm" type="{http://www.chinatax.gov.cn/dataspec/}zgswskfjDm"/>
// *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
// *         &lt;element name="hyDm" type="{http://www.chinatax.gov.cn/dataspec/}hyDm"/>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "SBYjxxJhVO", propOrder = {
//    "yjskuuid",
//    "zsxmDm",
//    "zspmDm",
//    "djxh",
//    "skssqq",
//    "skssqz",
//    "yjze",
//    "yjye",
//    "sksxDm",
//    "zgswskfjDm",
//    "sjgsdq",
//    "hyDm"
//})
//public class SBYjxxJhVO {
//
//    @XmlElement(required = true, nillable = true)
//    protected String yjskuuid;
//    @XmlElement(required = true, nillable = true)
//    protected String zsxmDm;
//    @XmlElement(required = true, nillable = true)
//    protected String zspmDm;
//    @XmlElement(required = true, nillable = true)
//    protected String djxh;
//    @XmlElement(required = true, nillable = true)
//    protected String skssqq;
//    @XmlElement(required = true, nillable = true)
//    protected String skssqz;
//    @XmlElement(required = true, type = Double.class, nillable = true)
//    protected Double yjze;
//    @XmlElement(required = true, type = Double.class, nillable = true)
//    protected Double yjye;
//    @XmlElement(required = true, nillable = true)
//    protected String sksxDm;
//    @XmlElement(required = true, nillable = true)
//    protected String zgswskfjDm;
//    @XmlElement(required = true, nillable = true)
//    protected String sjgsdq;
//    @XmlElement(required = true, nillable = true)
//    protected String hyDm;
//
//    /**
//     * Gets the value of the yjskuuid property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getYjskuuid() {
//        return yjskuuid;
//    }
//
//    /**
//     * Sets the value of the yjskuuid property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setYjskuuid(String value) {
//        this.yjskuuid = value;
//    }
//
//    /**
//     * Gets the value of the zsxmDm property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getZsxmDm() {
//        return zsxmDm;
//    }
//
//    /**
//     * Sets the value of the zsxmDm property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setZsxmDm(String value) {
//        this.zsxmDm = value;
//    }
//
//    /**
//     * Gets the value of the zspmDm property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getZspmDm() {
//        return zspmDm;
//    }
//
//    /**
//     * Sets the value of the zspmDm property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setZspmDm(String value) {
//        this.zspmDm = value;
//    }
//
//    /**
//     * Gets the value of the djxh property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getDjxh() {
//        return djxh;
//    }
//
//    /**
//     * Sets the value of the djxh property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setDjxh(String value) {
//        this.djxh = value;
//    }
//
//    /**
//     * Gets the value of the skssqq property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getSkssqq() {
//        return skssqq;
//    }
//
//    /**
//     * Sets the value of the skssqq property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setSkssqq(String value) {
//        this.skssqq = value;
//    }
//
//    /**
//     * Gets the value of the skssqz property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getSkssqz() {
//        return skssqz;
//    }
//
//    /**
//     * Sets the value of the skssqz property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setSkssqz(String value) {
//        this.skssqz = value;
//    }
//
//    /**
//     * Gets the value of the yjze property.
//     *
//     * @return
//     *     possible object is
//     *     {@link Double }
//     *
//     */
//    public Double getYjze() {
//        return yjze;
//    }
//
//    /**
//     * Sets the value of the yjze property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link Double }
//     *
//     */
//    public void setYjze(Double value) {
//        this.yjze = value;
//    }
//
//    /**
//     * Gets the value of the yjye property.
//     *
//     * @return
//     *     possible object is
//     *     {@link Double }
//     *
//     */
//    public Double getYjye() {
//        return yjye;
//    }
//
//    /**
//     * Sets the value of the yjye property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link Double }
//     *
//     */
//    public void setYjye(Double value) {
//        this.yjye = value;
//    }
//
//    /**
//     * Gets the value of the sksxDm property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getSksxDm() {
//        return sksxDm;
//    }
//
//    /**
//     * Sets the value of the sksxDm property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setSksxDm(String value) {
//        this.sksxDm = value;
//    }
//
//    /**
//     * Gets the value of the zgswskfjDm property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getZgswskfjDm() {
//        return zgswskfjDm;
//    }
//
//    /**
//     * Sets the value of the zgswskfjDm property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setZgswskfjDm(String value) {
//        this.zgswskfjDm = value;
//    }
//
//    /**
//     * Gets the value of the sjgsdq property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getSjgsdq() {
//        return sjgsdq;
//    }
//
//    /**
//     * Sets the value of the sjgsdq property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setSjgsdq(String value) {
//        this.sjgsdq = value;
//    }
//
//    /**
//     * Gets the value of the hyDm property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getHyDm() {
//        return hyDm;
//    }
//
//    /**
//     * Sets the value of the hyDm property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setHyDm(String value) {
//        this.hyDm = value;
//    }
//
//}
