//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 增值税留抵数据信息
 *
 * <p>Java class for SBZzsnsrldxxVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SBZzsnsrldxxVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sqldpzxh" type="{http://www.chinatax.gov.cn/dataspec/}sqldpzxh" minOccurs="0"/>
 *         &lt;element name="skssqq" type="{http://www.chinatax.gov.cn/dataspec/}skssqq"/>
 *         &lt;element name="skssqz" type="{http://www.chinatax.gov.cn/dataspec/}skssqz"/>
 *         &lt;element name="sqldse" type="{http://www.chinatax.gov.cn/dataspec/}sqldse"/>
 *         &lt;element name="sqldsebnlj" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bqqmldse" type="{http://www.chinatax.gov.cn/dataspec/}bqqmldse"/>
 *         &lt;element name="bqqmldsebnlj" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="ldlx" type="{http://www.chinatax.gov.cn/dataspec/}ldlx" minOccurs="0"/>
 *         &lt;element name="zgswskfjDm" type="{http://www.chinatax.gov.cn/dataspec/}zgswskfjDm" minOccurs="0"/>
 *         &lt;element name="swjgDm" type="{http://www.chinatax.gov.cn/dataspec/}swjgDm" minOccurs="0"/>
 *         &lt;element name="zzslx" type="{http://www.chinatax.gov.cn/dataspec/}zzslx" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SBZzsnsrldxxVO", propOrder = {
    "sqldpzxh",
    "skssqq",
    "skssqz",
    "sqldse",
    "sqldsebnlj",
    "bqqmldse",
    "bqqmldsebnlj",
    "ldlx",
    "zgswskfjDm",
    "swjgDm",
    "zzslx"
})
public class SBZzsnsrldxxVO {

    protected String sqldpzxh;
    @XmlElement(required = true)
    protected String skssqq;
    @XmlElement(required = true)
    protected String skssqz;
    protected double sqldse;
    protected double sqldsebnlj;
    protected double bqqmldse;
    protected double bqqmldsebnlj;
    protected String ldlx;
    protected String zgswskfjDm;
    protected String swjgDm;
    protected String zzslx;

    /**
     * Gets the value of the sqldpzxh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSqldpzxh() {
        return sqldpzxh;
    }

    /**
     * Sets the value of the sqldpzxh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSqldpzxh(String value) {
        this.sqldpzxh = value;
    }

    /**
     * Gets the value of the skssqq property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSkssqq() {
        return skssqq;
    }

    /**
     * Sets the value of the skssqq property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSkssqq(String value) {
        this.skssqq = value;
    }

    /**
     * Gets the value of the skssqz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSkssqz() {
        return skssqz;
    }

    /**
     * Sets the value of the skssqz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSkssqz(String value) {
        this.skssqz = value;
    }

    /**
     * Gets the value of the sqldse property.
     *
     */
    public double getSqldse() {
        return sqldse;
    }

    /**
     * Sets the value of the sqldse property.
     *
     */
    public void setSqldse(double value) {
        this.sqldse = value;
    }

    /**
     * Gets the value of the sqldsebnlj property.
     *
     */
    public double getSqldsebnlj() {
        return sqldsebnlj;
    }

    /**
     * Sets the value of the sqldsebnlj property.
     *
     */
    public void setSqldsebnlj(double value) {
        this.sqldsebnlj = value;
    }

    /**
     * Gets the value of the bqqmldse property.
     *
     */
    public double getBqqmldse() {
        return bqqmldse;
    }

    /**
     * Sets the value of the bqqmldse property.
     *
     */
    public void setBqqmldse(double value) {
        this.bqqmldse = value;
    }

    /**
     * Gets the value of the bqqmldsebnlj property.
     *
     */
    public double getBqqmldsebnlj() {
        return bqqmldsebnlj;
    }

    /**
     * Sets the value of the bqqmldsebnlj property.
     *
     */
    public void setBqqmldsebnlj(double value) {
        this.bqqmldsebnlj = value;
    }

    /**
     * Gets the value of the ldlx property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLdlx() {
        return ldlx;
    }

    /**
     * Sets the value of the ldlx property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLdlx(String value) {
        this.ldlx = value;
    }

    /**
     * Gets the value of the zgswskfjDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZgswskfjDm() {
        return zgswskfjDm;
    }

    /**
     * Sets the value of the zgswskfjDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZgswskfjDm(String value) {
        this.zgswskfjDm = value;
    }

    /**
     * Gets the value of the swjgDm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSwjgDm() {
        return swjgDm;
    }

    /**
     * Sets the value of the swjgDm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSwjgDm(String value) {
        this.swjgDm = value;
    }

    /**
     * Gets the value of the zzslx property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZzslx() {
        return zzslx;
    }

    /**
     * Sets the value of the zzslx property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZzslx(String value) {
        this.zzslx = value;
    }

}
