//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 税额抵免优惠明细表
 *
 * <p>Java class for SedmyhmxbForm complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SedmyhmxbForm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nd5" type="{http://www.chinatax.gov.cn/dataspec/}nd"/>
 *         &lt;element name="bndmqynse5" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnyxdmdzysbtze5" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnkdmse5" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqwund5" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqsind5" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqsannd5" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqernd5" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqyind5" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmexj5" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnsjdmdgndse5" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="nd4" type="{http://www.chinatax.gov.cn/dataspec/}nd"/>
 *         &lt;element name="bndmqynse4" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnyxdmdzysbtze4" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnkdmse4" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqsind4" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqsannd4" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqernd4" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqyind4" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmexj4" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnsjdmdgndse4" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="kjzyhnddmdse4" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="nd3" type="{http://www.chinatax.gov.cn/dataspec/}nd"/>
 *         &lt;element name="bndmqynse3" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnyxdmdzysbtze3" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnkdmse3" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqsannd3" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqernd3" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqyind3" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmexj3" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnsjdmdgndse3" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="kjzyhnddmdse3" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="nd2" type="{http://www.chinatax.gov.cn/dataspec/}nd"/>
 *         &lt;element name="bndmqynse2" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnyxdmdzysbtze2" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnkdmse2" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqernd2" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqyind2" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmexj2" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnsjdmdgndse2" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="kjzyhnddmdse2" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="nd1" type="{http://www.chinatax.gov.cn/dataspec/}nd"/>
 *         &lt;element name="bndmqynse1" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnyxdmdzysbtze1" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnkdmse1" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmeqyind1" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="yqndydmexj1" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnsjdmdgndse1" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="kjzyhnddmdse1" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnd" type="{http://www.chinatax.gov.cn/dataspec/}nd"/>
 *         &lt;element name="bndmqynse" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnyxdmdzysbtze" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnkdmse" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnsjdmdgndse" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="kjzyhnddmdse" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bndsjdmsehj" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="kjzyhnddmdsehj" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnyxdmdhjbhzysbtze" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnyxdmjejsdzysbtze" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="bnyxdmdaqsczysbtze" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="qwundsjkjzdmje" type="{http://www.chinatax.gov.cn/dataspec/}je" minOccurs="0"/>
 *         &lt;element name="qsindsjkjzdmje" type="{http://www.chinatax.gov.cn/dataspec/}je" minOccurs="0"/>
 *         &lt;element name="qsanndsjkjzdmje" type="{http://www.chinatax.gov.cn/dataspec/}je" minOccurs="0"/>
 *         &lt;element name="qerndsjkjzdmje" type="{http://www.chinatax.gov.cn/dataspec/}je" minOccurs="0"/>
 *         &lt;element name="qyindsjkjzdmje" type="{http://www.chinatax.gov.cn/dataspec/}je" minOccurs="0"/>
 *         &lt;element name="benndsjkjzdmje" type="{http://www.chinatax.gov.cn/dataspec/}je" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SedmyhmxbForm", propOrder = {
    "nd5",
    "bndmqynse5",
    "bnyxdmdzysbtze5",
    "bnkdmse5",
    "yqndydmeqwund5",
    "yqndydmeqsind5",
    "yqndydmeqsannd5",
    "yqndydmeqernd5",
    "yqndydmeqyind5",
    "yqndydmexj5",
    "bnsjdmdgndse5",
    "nd4",
    "bndmqynse4",
    "bnyxdmdzysbtze4",
    "bnkdmse4",
    "yqndydmeqsind4",
    "yqndydmeqsannd4",
    "yqndydmeqernd4",
    "yqndydmeqyind4",
    "yqndydmexj4",
    "bnsjdmdgndse4",
    "kjzyhnddmdse4",
    "nd3",
    "bndmqynse3",
    "bnyxdmdzysbtze3",
    "bnkdmse3",
    "yqndydmeqsannd3",
    "yqndydmeqernd3",
    "yqndydmeqyind3",
    "yqndydmexj3",
    "bnsjdmdgndse3",
    "kjzyhnddmdse3",
    "nd2",
    "bndmqynse2",
    "bnyxdmdzysbtze2",
    "bnkdmse2",
    "yqndydmeqernd2",
    "yqndydmeqyind2",
    "yqndydmexj2",
    "bnsjdmdgndse2",
    "kjzyhnddmdse2",
    "nd1",
    "bndmqynse1",
    "bnyxdmdzysbtze1",
    "bnkdmse1",
    "yqndydmeqyind1",
    "yqndydmexj1",
    "bnsjdmdgndse1",
    "kjzyhnddmdse1",
    "bnd",
    "bndmqynse",
    "bnyxdmdzysbtze",
    "bnkdmse",
    "bnsjdmdgndse",
    "kjzyhnddmdse",
    "bndsjdmsehj",
    "kjzyhnddmdsehj",
    "bnyxdmdhjbhzysbtze",
    "bnyxdmjejsdzysbtze",
    "bnyxdmdaqsczysbtze",
    "qwundsjkjzdmje",
    "qsindsjkjzdmje",
    "qsanndsjkjzdmje",
    "qerndsjkjzdmje",
    "qyindsjkjzdmje",
    "benndsjkjzdmje"
})
public class SedmyhmxbForm {

    @XmlElement(required = true)
    protected String nd5;
    protected double bndmqynse5;
    protected double bnyxdmdzysbtze5;
    protected double bnkdmse5;
    protected double yqndydmeqwund5;
    protected double yqndydmeqsind5;
    protected double yqndydmeqsannd5;
    protected double yqndydmeqernd5;
    protected double yqndydmeqyind5;
    protected double yqndydmexj5;
    protected double bnsjdmdgndse5;
    @XmlElement(required = true)
    protected String nd4;
    protected double bndmqynse4;
    protected double bnyxdmdzysbtze4;
    protected double bnkdmse4;
    protected double yqndydmeqsind4;
    protected double yqndydmeqsannd4;
    protected double yqndydmeqernd4;
    protected double yqndydmeqyind4;
    protected double yqndydmexj4;
    protected double bnsjdmdgndse4;
    protected double kjzyhnddmdse4;
    @XmlElement(required = true)
    protected String nd3;
    protected double bndmqynse3;
    protected double bnyxdmdzysbtze3;
    protected double bnkdmse3;
    protected double yqndydmeqsannd3;
    protected double yqndydmeqernd3;
    protected double yqndydmeqyind3;
    protected double yqndydmexj3;
    protected double bnsjdmdgndse3;
    protected double kjzyhnddmdse3;
    @XmlElement(required = true)
    protected String nd2;
    protected double bndmqynse2;
    protected double bnyxdmdzysbtze2;
    protected double bnkdmse2;
    protected double yqndydmeqernd2;
    protected double yqndydmeqyind2;
    protected double yqndydmexj2;
    protected double bnsjdmdgndse2;
    protected double kjzyhnddmdse2;
    @XmlElement(required = true)
    protected String nd1;
    protected double bndmqynse1;
    protected double bnyxdmdzysbtze1;
    protected double bnkdmse1;
    protected double yqndydmeqyind1;
    protected double yqndydmexj1;
    protected double bnsjdmdgndse1;
    protected double kjzyhnddmdse1;
    @XmlElement(required = true)
    protected String bnd;
    protected double bndmqynse;
    protected double bnyxdmdzysbtze;
    protected double bnkdmse;
    protected double bnsjdmdgndse;
    protected double kjzyhnddmdse;
    protected double bndsjdmsehj;
    protected double kjzyhnddmdsehj;
    protected double bnyxdmdhjbhzysbtze;
    protected double bnyxdmjejsdzysbtze;
    protected double bnyxdmdaqsczysbtze;
    protected Double qwundsjkjzdmje;
    protected Double qsindsjkjzdmje;
    protected Double qsanndsjkjzdmje;
    protected Double qerndsjkjzdmje;
    protected Double qyindsjkjzdmje;
    protected Double benndsjkjzdmje;

    /**
     * Gets the value of the nd5 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNd5() {
        return nd5;
    }

    /**
     * Sets the value of the nd5 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNd5(String value) {
        this.nd5 = value;
    }

    /**
     * Gets the value of the bndmqynse5 property.
     *
     */
    public double getBndmqynse5() {
        return bndmqynse5;
    }

    /**
     * Sets the value of the bndmqynse5 property.
     *
     */
    public void setBndmqynse5(double value) {
        this.bndmqynse5 = value;
    }

    /**
     * Gets the value of the bnyxdmdzysbtze5 property.
     *
     */
    public double getBnyxdmdzysbtze5() {
        return bnyxdmdzysbtze5;
    }

    /**
     * Sets the value of the bnyxdmdzysbtze5 property.
     *
     */
    public void setBnyxdmdzysbtze5(double value) {
        this.bnyxdmdzysbtze5 = value;
    }

    /**
     * Gets the value of the bnkdmse5 property.
     *
     */
    public double getBnkdmse5() {
        return bnkdmse5;
    }

    /**
     * Sets the value of the bnkdmse5 property.
     *
     */
    public void setBnkdmse5(double value) {
        this.bnkdmse5 = value;
    }

    /**
     * Gets the value of the yqndydmeqwund5 property.
     *
     */
    public double getYqndydmeqwund5() {
        return yqndydmeqwund5;
    }

    /**
     * Sets the value of the yqndydmeqwund5 property.
     *
     */
    public void setYqndydmeqwund5(double value) {
        this.yqndydmeqwund5 = value;
    }

    /**
     * Gets the value of the yqndydmeqsind5 property.
     *
     */
    public double getYqndydmeqsind5() {
        return yqndydmeqsind5;
    }

    /**
     * Sets the value of the yqndydmeqsind5 property.
     *
     */
    public void setYqndydmeqsind5(double value) {
        this.yqndydmeqsind5 = value;
    }

    /**
     * Gets the value of the yqndydmeqsannd5 property.
     *
     */
    public double getYqndydmeqsannd5() {
        return yqndydmeqsannd5;
    }

    /**
     * Sets the value of the yqndydmeqsannd5 property.
     *
     */
    public void setYqndydmeqsannd5(double value) {
        this.yqndydmeqsannd5 = value;
    }

    /**
     * Gets the value of the yqndydmeqernd5 property.
     *
     */
    public double getYqndydmeqernd5() {
        return yqndydmeqernd5;
    }

    /**
     * Sets the value of the yqndydmeqernd5 property.
     *
     */
    public void setYqndydmeqernd5(double value) {
        this.yqndydmeqernd5 = value;
    }

    /**
     * Gets the value of the yqndydmeqyind5 property.
     *
     */
    public double getYqndydmeqyind5() {
        return yqndydmeqyind5;
    }

    /**
     * Sets the value of the yqndydmeqyind5 property.
     *
     */
    public void setYqndydmeqyind5(double value) {
        this.yqndydmeqyind5 = value;
    }

    /**
     * Gets the value of the yqndydmexj5 property.
     *
     */
    public double getYqndydmexj5() {
        return yqndydmexj5;
    }

    /**
     * Sets the value of the yqndydmexj5 property.
     *
     */
    public void setYqndydmexj5(double value) {
        this.yqndydmexj5 = value;
    }

    /**
     * Gets the value of the bnsjdmdgndse5 property.
     *
     */
    public double getBnsjdmdgndse5() {
        return bnsjdmdgndse5;
    }

    /**
     * Sets the value of the bnsjdmdgndse5 property.
     *
     */
    public void setBnsjdmdgndse5(double value) {
        this.bnsjdmdgndse5 = value;
    }

    /**
     * Gets the value of the nd4 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNd4() {
        return nd4;
    }

    /**
     * Sets the value of the nd4 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNd4(String value) {
        this.nd4 = value;
    }

    /**
     * Gets the value of the bndmqynse4 property.
     *
     */
    public double getBndmqynse4() {
        return bndmqynse4;
    }

    /**
     * Sets the value of the bndmqynse4 property.
     *
     */
    public void setBndmqynse4(double value) {
        this.bndmqynse4 = value;
    }

    /**
     * Gets the value of the bnyxdmdzysbtze4 property.
     *
     */
    public double getBnyxdmdzysbtze4() {
        return bnyxdmdzysbtze4;
    }

    /**
     * Sets the value of the bnyxdmdzysbtze4 property.
     *
     */
    public void setBnyxdmdzysbtze4(double value) {
        this.bnyxdmdzysbtze4 = value;
    }

    /**
     * Gets the value of the bnkdmse4 property.
     *
     */
    public double getBnkdmse4() {
        return bnkdmse4;
    }

    /**
     * Sets the value of the bnkdmse4 property.
     *
     */
    public void setBnkdmse4(double value) {
        this.bnkdmse4 = value;
    }

    /**
     * Gets the value of the yqndydmeqsind4 property.
     *
     */
    public double getYqndydmeqsind4() {
        return yqndydmeqsind4;
    }

    /**
     * Sets the value of the yqndydmeqsind4 property.
     *
     */
    public void setYqndydmeqsind4(double value) {
        this.yqndydmeqsind4 = value;
    }

    /**
     * Gets the value of the yqndydmeqsannd4 property.
     *
     */
    public double getYqndydmeqsannd4() {
        return yqndydmeqsannd4;
    }

    /**
     * Sets the value of the yqndydmeqsannd4 property.
     *
     */
    public void setYqndydmeqsannd4(double value) {
        this.yqndydmeqsannd4 = value;
    }

    /**
     * Gets the value of the yqndydmeqernd4 property.
     *
     */
    public double getYqndydmeqernd4() {
        return yqndydmeqernd4;
    }

    /**
     * Sets the value of the yqndydmeqernd4 property.
     *
     */
    public void setYqndydmeqernd4(double value) {
        this.yqndydmeqernd4 = value;
    }

    /**
     * Gets the value of the yqndydmeqyind4 property.
     *
     */
    public double getYqndydmeqyind4() {
        return yqndydmeqyind4;
    }

    /**
     * Sets the value of the yqndydmeqyind4 property.
     *
     */
    public void setYqndydmeqyind4(double value) {
        this.yqndydmeqyind4 = value;
    }

    /**
     * Gets the value of the yqndydmexj4 property.
     *
     */
    public double getYqndydmexj4() {
        return yqndydmexj4;
    }

    /**
     * Sets the value of the yqndydmexj4 property.
     *
     */
    public void setYqndydmexj4(double value) {
        this.yqndydmexj4 = value;
    }

    /**
     * Gets the value of the bnsjdmdgndse4 property.
     *
     */
    public double getBnsjdmdgndse4() {
        return bnsjdmdgndse4;
    }

    /**
     * Sets the value of the bnsjdmdgndse4 property.
     *
     */
    public void setBnsjdmdgndse4(double value) {
        this.bnsjdmdgndse4 = value;
    }

    /**
     * Gets the value of the kjzyhnddmdse4 property.
     *
     */
    public double getKjzyhnddmdse4() {
        return kjzyhnddmdse4;
    }

    /**
     * Sets the value of the kjzyhnddmdse4 property.
     *
     */
    public void setKjzyhnddmdse4(double value) {
        this.kjzyhnddmdse4 = value;
    }

    /**
     * Gets the value of the nd3 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNd3() {
        return nd3;
    }

    /**
     * Sets the value of the nd3 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNd3(String value) {
        this.nd3 = value;
    }

    /**
     * Gets the value of the bndmqynse3 property.
     *
     */
    public double getBndmqynse3() {
        return bndmqynse3;
    }

    /**
     * Sets the value of the bndmqynse3 property.
     *
     */
    public void setBndmqynse3(double value) {
        this.bndmqynse3 = value;
    }

    /**
     * Gets the value of the bnyxdmdzysbtze3 property.
     *
     */
    public double getBnyxdmdzysbtze3() {
        return bnyxdmdzysbtze3;
    }

    /**
     * Sets the value of the bnyxdmdzysbtze3 property.
     *
     */
    public void setBnyxdmdzysbtze3(double value) {
        this.bnyxdmdzysbtze3 = value;
    }

    /**
     * Gets the value of the bnkdmse3 property.
     *
     */
    public double getBnkdmse3() {
        return bnkdmse3;
    }

    /**
     * Sets the value of the bnkdmse3 property.
     *
     */
    public void setBnkdmse3(double value) {
        this.bnkdmse3 = value;
    }

    /**
     * Gets the value of the yqndydmeqsannd3 property.
     *
     */
    public double getYqndydmeqsannd3() {
        return yqndydmeqsannd3;
    }

    /**
     * Sets the value of the yqndydmeqsannd3 property.
     *
     */
    public void setYqndydmeqsannd3(double value) {
        this.yqndydmeqsannd3 = value;
    }

    /**
     * Gets the value of the yqndydmeqernd3 property.
     *
     */
    public double getYqndydmeqernd3() {
        return yqndydmeqernd3;
    }

    /**
     * Sets the value of the yqndydmeqernd3 property.
     *
     */
    public void setYqndydmeqernd3(double value) {
        this.yqndydmeqernd3 = value;
    }

    /**
     * Gets the value of the yqndydmeqyind3 property.
     *
     */
    public double getYqndydmeqyind3() {
        return yqndydmeqyind3;
    }

    /**
     * Sets the value of the yqndydmeqyind3 property.
     *
     */
    public void setYqndydmeqyind3(double value) {
        this.yqndydmeqyind3 = value;
    }

    /**
     * Gets the value of the yqndydmexj3 property.
     *
     */
    public double getYqndydmexj3() {
        return yqndydmexj3;
    }

    /**
     * Sets the value of the yqndydmexj3 property.
     *
     */
    public void setYqndydmexj3(double value) {
        this.yqndydmexj3 = value;
    }

    /**
     * Gets the value of the bnsjdmdgndse3 property.
     *
     */
    public double getBnsjdmdgndse3() {
        return bnsjdmdgndse3;
    }

    /**
     * Sets the value of the bnsjdmdgndse3 property.
     *
     */
    public void setBnsjdmdgndse3(double value) {
        this.bnsjdmdgndse3 = value;
    }

    /**
     * Gets the value of the kjzyhnddmdse3 property.
     *
     */
    public double getKjzyhnddmdse3() {
        return kjzyhnddmdse3;
    }

    /**
     * Sets the value of the kjzyhnddmdse3 property.
     *
     */
    public void setKjzyhnddmdse3(double value) {
        this.kjzyhnddmdse3 = value;
    }

    /**
     * Gets the value of the nd2 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNd2() {
        return nd2;
    }

    /**
     * Sets the value of the nd2 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNd2(String value) {
        this.nd2 = value;
    }

    /**
     * Gets the value of the bndmqynse2 property.
     *
     */
    public double getBndmqynse2() {
        return bndmqynse2;
    }

    /**
     * Sets the value of the bndmqynse2 property.
     *
     */
    public void setBndmqynse2(double value) {
        this.bndmqynse2 = value;
    }

    /**
     * Gets the value of the bnyxdmdzysbtze2 property.
     *
     */
    public double getBnyxdmdzysbtze2() {
        return bnyxdmdzysbtze2;
    }

    /**
     * Sets the value of the bnyxdmdzysbtze2 property.
     *
     */
    public void setBnyxdmdzysbtze2(double value) {
        this.bnyxdmdzysbtze2 = value;
    }

    /**
     * Gets the value of the bnkdmse2 property.
     *
     */
    public double getBnkdmse2() {
        return bnkdmse2;
    }

    /**
     * Sets the value of the bnkdmse2 property.
     *
     */
    public void setBnkdmse2(double value) {
        this.bnkdmse2 = value;
    }

    /**
     * Gets the value of the yqndydmeqernd2 property.
     *
     */
    public double getYqndydmeqernd2() {
        return yqndydmeqernd2;
    }

    /**
     * Sets the value of the yqndydmeqernd2 property.
     *
     */
    public void setYqndydmeqernd2(double value) {
        this.yqndydmeqernd2 = value;
    }

    /**
     * Gets the value of the yqndydmeqyind2 property.
     *
     */
    public double getYqndydmeqyind2() {
        return yqndydmeqyind2;
    }

    /**
     * Sets the value of the yqndydmeqyind2 property.
     *
     */
    public void setYqndydmeqyind2(double value) {
        this.yqndydmeqyind2 = value;
    }

    /**
     * Gets the value of the yqndydmexj2 property.
     *
     */
    public double getYqndydmexj2() {
        return yqndydmexj2;
    }

    /**
     * Sets the value of the yqndydmexj2 property.
     *
     */
    public void setYqndydmexj2(double value) {
        this.yqndydmexj2 = value;
    }

    /**
     * Gets the value of the bnsjdmdgndse2 property.
     *
     */
    public double getBnsjdmdgndse2() {
        return bnsjdmdgndse2;
    }

    /**
     * Sets the value of the bnsjdmdgndse2 property.
     *
     */
    public void setBnsjdmdgndse2(double value) {
        this.bnsjdmdgndse2 = value;
    }

    /**
     * Gets the value of the kjzyhnddmdse2 property.
     *
     */
    public double getKjzyhnddmdse2() {
        return kjzyhnddmdse2;
    }

    /**
     * Sets the value of the kjzyhnddmdse2 property.
     *
     */
    public void setKjzyhnddmdse2(double value) {
        this.kjzyhnddmdse2 = value;
    }

    /**
     * Gets the value of the nd1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNd1() {
        return nd1;
    }

    /**
     * Sets the value of the nd1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNd1(String value) {
        this.nd1 = value;
    }

    /**
     * Gets the value of the bndmqynse1 property.
     *
     */
    public double getBndmqynse1() {
        return bndmqynse1;
    }

    /**
     * Sets the value of the bndmqynse1 property.
     *
     */
    public void setBndmqynse1(double value) {
        this.bndmqynse1 = value;
    }

    /**
     * Gets the value of the bnyxdmdzysbtze1 property.
     *
     */
    public double getBnyxdmdzysbtze1() {
        return bnyxdmdzysbtze1;
    }

    /**
     * Sets the value of the bnyxdmdzysbtze1 property.
     *
     */
    public void setBnyxdmdzysbtze1(double value) {
        this.bnyxdmdzysbtze1 = value;
    }

    /**
     * Gets the value of the bnkdmse1 property.
     *
     */
    public double getBnkdmse1() {
        return bnkdmse1;
    }

    /**
     * Sets the value of the bnkdmse1 property.
     *
     */
    public void setBnkdmse1(double value) {
        this.bnkdmse1 = value;
    }

    /**
     * Gets the value of the yqndydmeqyind1 property.
     *
     */
    public double getYqndydmeqyind1() {
        return yqndydmeqyind1;
    }

    /**
     * Sets the value of the yqndydmeqyind1 property.
     *
     */
    public void setYqndydmeqyind1(double value) {
        this.yqndydmeqyind1 = value;
    }

    /**
     * Gets the value of the yqndydmexj1 property.
     *
     */
    public double getYqndydmexj1() {
        return yqndydmexj1;
    }

    /**
     * Sets the value of the yqndydmexj1 property.
     *
     */
    public void setYqndydmexj1(double value) {
        this.yqndydmexj1 = value;
    }

    /**
     * Gets the value of the bnsjdmdgndse1 property.
     *
     */
    public double getBnsjdmdgndse1() {
        return bnsjdmdgndse1;
    }

    /**
     * Sets the value of the bnsjdmdgndse1 property.
     *
     */
    public void setBnsjdmdgndse1(double value) {
        this.bnsjdmdgndse1 = value;
    }

    /**
     * Gets the value of the kjzyhnddmdse1 property.
     *
     */
    public double getKjzyhnddmdse1() {
        return kjzyhnddmdse1;
    }

    /**
     * Sets the value of the kjzyhnddmdse1 property.
     *
     */
    public void setKjzyhnddmdse1(double value) {
        this.kjzyhnddmdse1 = value;
    }

    /**
     * Gets the value of the bnd property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBnd() {
        return bnd;
    }

    /**
     * Sets the value of the bnd property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBnd(String value) {
        this.bnd = value;
    }

    /**
     * Gets the value of the bndmqynse property.
     *
     */
    public double getBndmqynse() {
        return bndmqynse;
    }

    /**
     * Sets the value of the bndmqynse property.
     *
     */
    public void setBndmqynse(double value) {
        this.bndmqynse = value;
    }

    /**
     * Gets the value of the bnyxdmdzysbtze property.
     *
     */
    public double getBnyxdmdzysbtze() {
        return bnyxdmdzysbtze;
    }

    /**
     * Sets the value of the bnyxdmdzysbtze property.
     *
     */
    public void setBnyxdmdzysbtze(double value) {
        this.bnyxdmdzysbtze = value;
    }

    /**
     * Gets the value of the bnkdmse property.
     *
     */
    public double getBnkdmse() {
        return bnkdmse;
    }

    /**
     * Sets the value of the bnkdmse property.
     *
     */
    public void setBnkdmse(double value) {
        this.bnkdmse = value;
    }

    /**
     * Gets the value of the bnsjdmdgndse property.
     *
     */
    public double getBnsjdmdgndse() {
        return bnsjdmdgndse;
    }

    /**
     * Sets the value of the bnsjdmdgndse property.
     *
     */
    public void setBnsjdmdgndse(double value) {
        this.bnsjdmdgndse = value;
    }

    /**
     * Gets the value of the kjzyhnddmdse property.
     *
     */
    public double getKjzyhnddmdse() {
        return kjzyhnddmdse;
    }

    /**
     * Sets the value of the kjzyhnddmdse property.
     *
     */
    public void setKjzyhnddmdse(double value) {
        this.kjzyhnddmdse = value;
    }

    /**
     * Gets the value of the bndsjdmsehj property.
     *
     */
    public double getBndsjdmsehj() {
        return bndsjdmsehj;
    }

    /**
     * Sets the value of the bndsjdmsehj property.
     *
     */
    public void setBndsjdmsehj(double value) {
        this.bndsjdmsehj = value;
    }

    /**
     * Gets the value of the kjzyhnddmdsehj property.
     *
     */
    public double getKjzyhnddmdsehj() {
        return kjzyhnddmdsehj;
    }

    /**
     * Sets the value of the kjzyhnddmdsehj property.
     *
     */
    public void setKjzyhnddmdsehj(double value) {
        this.kjzyhnddmdsehj = value;
    }

    /**
     * Gets the value of the bnyxdmdhjbhzysbtze property.
     *
     */
    public double getBnyxdmdhjbhzysbtze() {
        return bnyxdmdhjbhzysbtze;
    }

    /**
     * Sets the value of the bnyxdmdhjbhzysbtze property.
     *
     */
    public void setBnyxdmdhjbhzysbtze(double value) {
        this.bnyxdmdhjbhzysbtze = value;
    }

    /**
     * Gets the value of the bnyxdmjejsdzysbtze property.
     *
     */
    public double getBnyxdmjejsdzysbtze() {
        return bnyxdmjejsdzysbtze;
    }

    /**
     * Sets the value of the bnyxdmjejsdzysbtze property.
     *
     */
    public void setBnyxdmjejsdzysbtze(double value) {
        this.bnyxdmjejsdzysbtze = value;
    }

    /**
     * Gets the value of the bnyxdmdaqsczysbtze property.
     *
     */
    public double getBnyxdmdaqsczysbtze() {
        return bnyxdmdaqsczysbtze;
    }

    /**
     * Sets the value of the bnyxdmdaqsczysbtze property.
     *
     */
    public void setBnyxdmdaqsczysbtze(double value) {
        this.bnyxdmdaqsczysbtze = value;
    }

    /**
     * Gets the value of the qwundsjkjzdmje property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getQwundsjkjzdmje() {
        return qwundsjkjzdmje;
    }

    /**
     * Sets the value of the qwundsjkjzdmje property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setQwundsjkjzdmje(Double value) {
        this.qwundsjkjzdmje = value;
    }

    /**
     * Gets the value of the qsindsjkjzdmje property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getQsindsjkjzdmje() {
        return qsindsjkjzdmje;
    }

    /**
     * Sets the value of the qsindsjkjzdmje property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setQsindsjkjzdmje(Double value) {
        this.qsindsjkjzdmje = value;
    }

    /**
     * Gets the value of the qsanndsjkjzdmje property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getQsanndsjkjzdmje() {
        return qsanndsjkjzdmje;
    }

    /**
     * Sets the value of the qsanndsjkjzdmje property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setQsanndsjkjzdmje(Double value) {
        this.qsanndsjkjzdmje = value;
    }

    /**
     * Gets the value of the qerndsjkjzdmje property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getQerndsjkjzdmje() {
        return qerndsjkjzdmje;
    }

    /**
     * Sets the value of the qerndsjkjzdmje property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setQerndsjkjzdmje(Double value) {
        this.qerndsjkjzdmje = value;
    }

    /**
     * Gets the value of the qyindsjkjzdmje property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getQyindsjkjzdmje() {
        return qyindsjkjzdmje;
    }

    /**
     * Sets the value of the qyindsjkjzdmje property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setQyindsjkjzdmje(Double value) {
        this.qyindsjkjzdmje = value;
    }

    /**
     * Gets the value of the benndsjkjzdmje property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getBenndsjkjzdmje() {
        return benndsjkjzdmje;
    }

    /**
     * Sets the value of the benndsjkjzdmje property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setBenndsjkjzdmje(Double value) {
        this.benndsjkjzdmje = value;
    }

}
