//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 税款征收信息
 *
 * <p>Java class for skzsFormVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="skzsFormVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="qylxbz" type="{http://www.chinatax.gov.cn/dataspec/}qylxbz"/>
 *         &lt;element name="slsdljt" type="{http://www.chinatax.gov.cn/dataspec/}slsdljt"/>
 *         &lt;element name="bqyjzzs1" type="{http://www.chinatax.gov.cn/dataspec/}bqyjzzs1"/>
 *         &lt;element name="bqyjzzshcbsk" type="{http://www.chinatax.gov.cn/dataspec/}bqyjzzshcbsk"/>
 *         &lt;element name="bqqjzzs" type="{http://www.chinatax.gov.cn/dataspec/}bqqjzzs"/>
 *         &lt;element name="bnljjnzzs" type="{http://www.chinatax.gov.cn/dataspec/}bnljjnzzs"/>
 *         &lt;element name="shswry" type="{http://www.chinatax.gov.cn/dataspec/}swryxm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "skzsFormVO", propOrder = {
    "qylxbz",
    "slsdljt",
    "bqyjzzs1",
    "bqyjzzshcbsk",
    "bqqjzzs",
    "bnljjnzzs",
    "shswry"
})
public class SkzsFormVO {

    @XmlElement(required = true)
    protected String qylxbz;
    @XmlElement(required = true)
    protected String slsdljt;
    protected double bqyjzzs1;
    protected double bqyjzzshcbsk;
    protected double bqqjzzs;
    protected double bnljjnzzs;
    @XmlElement(required = true)
    protected String shswry;

    /**
     * Gets the value of the qylxbz property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQylxbz() {
        return qylxbz;
    }

    /**
     * Sets the value of the qylxbz property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQylxbz(String value) {
        this.qylxbz = value;
    }

    /**
     * Gets the value of the slsdljt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSlsdljt() {
        return slsdljt;
    }

    /**
     * Sets the value of the slsdljt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSlsdljt(String value) {
        this.slsdljt = value;
    }

    /**
     * Gets the value of the bqyjzzs1 property.
     *
     */
    public double getBqyjzzs1() {
        return bqyjzzs1;
    }

    /**
     * Sets the value of the bqyjzzs1 property.
     *
     */
    public void setBqyjzzs1(double value) {
        this.bqyjzzs1 = value;
    }

    /**
     * Gets the value of the bqyjzzshcbsk property.
     *
     */
    public double getBqyjzzshcbsk() {
        return bqyjzzshcbsk;
    }

    /**
     * Sets the value of the bqyjzzshcbsk property.
     *
     */
    public void setBqyjzzshcbsk(double value) {
        this.bqyjzzshcbsk = value;
    }

    /**
     * Gets the value of the bqqjzzs property.
     *
     */
    public double getBqqjzzs() {
        return bqqjzzs;
    }

    /**
     * Sets the value of the bqqjzzs property.
     *
     */
    public void setBqqjzzs(double value) {
        this.bqqjzzs = value;
    }

    /**
     * Gets the value of the bnljjnzzs property.
     *
     */
    public double getBnljjnzzs() {
        return bnljjnzzs;
    }

    /**
     * Sets the value of the bnljjnzzs property.
     *
     */
    public void setBnljjnzzs(double value) {
        this.bnljjnzzs = value;
    }

    /**
     * Gets the value of the shswry property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getShswry() {
        return shswry;
    }

    /**
     * Sets the value of the shswry property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setShswry(String value) {
        this.shswry = value;
    }

}
