//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for slxxFormVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="slxxFormVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="swrymc" type="{http://www.chinatax.gov.cn/dataspec/}slrDm" minOccurs="0"/>
 *         &lt;element name="swjgmc" type="{http://www.chinatax.gov.cn/dataspec/}slswjgDm" minOccurs="0"/>
 *         &lt;element name="lrrq" type="{http://www.chinatax.gov.cn/dataspec/}slrq"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "slxxFormVO", propOrder = {
    "swrymc",
    "swjgmc",
    "lrrq"
})
public class SlxxFormVO {

    protected String swrymc;
    protected String swjgmc;
    @XmlElement(required = true)
    protected String lrrq;

    /**
     * Gets the value of the swrymc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSwrymc() {
        return swrymc;
    }

    /**
     * Sets the value of the swrymc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSwrymc(String value) {
        this.swrymc = value;
    }

    /**
     * Gets the value of the swjgmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSwjgmc() {
        return swjgmc;
    }

    /**
     * Sets the value of the swjgmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSwjgmc(String value) {
        this.swjgmc = value;
    }

    /**
     * Gets the value of the lrrq property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLrrq() {
        return lrrq;
    }

    /**
     * Sets the value of the lrrq property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLrrq(String value) {
        this.lrrq = value;
    }

}
