////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2015.08.28 at 06:10:39 PM CST
////
//
//
package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "xgmfjsxxGridlb",
        propOrder = {"sybh", "rdpzuuid", "zsxmDm", "zspmDm", "jsyj", "sl1", "ynse", "ssjmxzDm", "jmse", "yjse1", "ybtse", "rdyxqq", "rdyxqz", "phjmxzDm", "phjzbl", "phjmse", "phjmswsxDm"}
)
public class XgmfjsxxGridlb {
    @XmlElement(
            required = true
    )
    protected String sybh;
    @XmlElement(
            required = true
    )
    protected String rdpzuuid;
    @XmlElement(
            required = true
    )
    protected String zsxmDm;
    @XmlElement(
            required = true
    )
    protected String zspmDm;
    protected double jsyj;
    protected double sl1;
    protected double ynse;
    @XmlElement(
            required = true
    )
    protected String ssjmxzDm;
    protected double jmse;
    protected double yjse1;
    protected double ybtse;
    @XmlElement(
            required = true
    )
    protected Object rdyxqq;
    @XmlElement(
            required = true
    )
    protected Object rdyxqz;
    protected String phjmxzDm;
    protected Double phjzbl;
    protected Double phjmse;
    protected String phjmswsxDm;

    public XgmfjsxxGridlb() {
    }

    public String getSybh() {
        return this.sybh;
    }

    public void setSybh(String value) {
        this.sybh = value;
    }

    public String getRdpzuuid() {
        return this.rdpzuuid;
    }

    public void setRdpzuuid(String value) {
        this.rdpzuuid = value;
    }

    public String getZsxmDm() {
        return this.zsxmDm;
    }

    public void setZsxmDm(String value) {
        this.zsxmDm = value;
    }

    public String getZspmDm() {
        return this.zspmDm;
    }

    public void setZspmDm(String value) {
        this.zspmDm = value;
    }

    public double getJsyj() {
        return this.jsyj;
    }

    public void setJsyj(double value) {
        this.jsyj = value;
    }

    public double getSl1() {
        return this.sl1;
    }

    public void setSl1(double value) {
        this.sl1 = value;
    }

    public double getYnse() {
        return this.ynse;
    }

    public void setYnse(double value) {
        this.ynse = value;
    }

    public String getSsjmxzDm() {
        return this.ssjmxzDm;
    }

    public void setSsjmxzDm(String value) {
        this.ssjmxzDm = value;
    }

    public double getJmse() {
        return this.jmse;
    }

    public void setJmse(double value) {
        this.jmse = value;
    }

    public double getYjse1() {
        return this.yjse1;
    }

    public void setYjse1(double value) {
        this.yjse1 = value;
    }

    public double getYbtse() {
        return this.ybtse;
    }

    public void setYbtse(double value) {
        this.ybtse = value;
    }

    public Object getRdyxqq() {
        return this.rdyxqq;
    }

    public void setRdyxqq(Object value) {
        this.rdyxqq = value;
    }

    public Object getRdyxqz() {
        return this.rdyxqz;
    }

    public void setRdyxqz(Object value) {
        this.rdyxqz = value;
    }

    public String getPhjmxzDm() {
        return this.phjmxzDm;
    }

    public void setPhjmxzDm(String value) {
        this.phjmxzDm = value;
    }

    public Double getPhjzbl() {
        return this.phjzbl;
    }

    public void setPhjzbl(Double value) {
        this.phjzbl = value;
    }

    public Double getPhjmse() {
        return this.phjmse;
    }

    public void setPhjmse(Double value) {
        this.phjmse = value;
    }

    public String getPhjmswsxDm() {
        return this.phjmswsxDm;
    }

    public void setPhjmswsxDm(String value) {
        this.phjmswsxDm = value;
    }
}

//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * 附加税申报
// *
// * <p>Java class for xgmfjsxxGridlb complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="xgmfjsxxGridlb">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="sybh" type="{http://www.chinatax.gov.cn/dataspec/}sybh"/>
// *         &lt;element name="rdpzuuid" type="{http://www.chinatax.gov.cn/dataspec/}rdpzuuid"/>
// *         &lt;element name="zsxmDm" type="{http://www.chinatax.gov.cn/dataspec/}zsxmDm"/>
// *         &lt;element name="zspmDm" type="{http://www.chinatax.gov.cn/dataspec/}zspmDm"/>
// *         &lt;element name="jsyj" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
// *         &lt;element name="sl1" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
// *         &lt;element name="ynse" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
// *         &lt;element name="ssjmxzDm" type="{http://www.chinatax.gov.cn/dataspec/}ssjmxzDm"/>
// *         &lt;element name="jmse" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
// *         &lt;element name="yjse1" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
// *         &lt;element name="ybtse" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "xgmfjsxxGridlb", propOrder = {
//    "sybh",
//    "rdpzuuid",
//    "zsxmDm",
//    "zspmDm",
//    "jsyj",
//    "sl1",
//    "ynse",
//    "ssjmxzDm",
//    "jmse",
//    "yjse1",
//    "ybtse"
//})
//public class XgmfjsxxGridlb {
//
//    @XmlElement(required = true)
//    protected String sybh;
//    @XmlElement(required = true)
//    protected String rdpzuuid;
//    @XmlElement(required = true)
//    protected String zsxmDm;
//    @XmlElement(required = true)
//    protected String zspmDm;
//    protected double jsyj;
//    protected double sl1;
//    protected double ynse;
//    @XmlElement(required = true)
//    protected String ssjmxzDm;
//    protected double jmse;
//    protected double yjse1;
//    protected double ybtse;
//
//    /**
//     * Gets the value of the sybh property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getSybh() {
//        return sybh;
//    }
//
//    /**
//     * Sets the value of the sybh property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setSybh(String value) {
//        this.sybh = value;
//    }
//
//    /**
//     * Gets the value of the rdpzuuid property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getRdpzuuid() {
//        return rdpzuuid;
//    }
//
//    /**
//     * Sets the value of the rdpzuuid property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setRdpzuuid(String value) {
//        this.rdpzuuid = value;
//    }
//
//    /**
//     * Gets the value of the zsxmDm property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getZsxmDm() {
//        return zsxmDm;
//    }
//
//    /**
//     * Sets the value of the zsxmDm property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setZsxmDm(String value) {
//        this.zsxmDm = value;
//    }
//
//    /**
//     * Gets the value of the zspmDm property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getZspmDm() {
//        return zspmDm;
//    }
//
//    /**
//     * Sets the value of the zspmDm property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setZspmDm(String value) {
//        this.zspmDm = value;
//    }
//
//    /**
//     * Gets the value of the jsyj property.
//     *
//     */
//    public double getJsyj() {
//        return jsyj;
//    }
//
//    /**
//     * Sets the value of the jsyj property.
//     *
//     */
//    public void setJsyj(double value) {
//        this.jsyj = value;
//    }
//
//    /**
//     * Gets the value of the sl1 property.
//     *
//     */
//    public double getSl1() {
//        return sl1;
//    }
//
//    /**
//     * Sets the value of the sl1 property.
//     *
//     */
//    public void setSl1(double value) {
//        this.sl1 = value;
//    }
//
//    /**
//     * Gets the value of the ynse property.
//     *
//     */
//    public double getYnse() {
//        return ynse;
//    }
//
//    /**
//     * Sets the value of the ynse property.
//     *
//     */
//    public void setYnse(double value) {
//        this.ynse = value;
//    }
//
//    /**
//     * Gets the value of the ssjmxzDm property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getSsjmxzDm() {
//        return ssjmxzDm;
//    }
//
//    /**
//     * Sets the value of the ssjmxzDm property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setSsjmxzDm(String value) {
//        this.ssjmxzDm = value;
//    }
//
//    /**
//     * Gets the value of the jmse property.
//     *
//     */
//    public double getJmse() {
//        return jmse;
//    }
//
//    /**
//     * Sets the value of the jmse property.
//     *
//     */
//    public void setJmse(double value) {
//        this.jmse = value;
//    }
//
//    /**
//     * Gets the value of the yjse1 property.
//     *
//     */
//    public double getYjse1() {
//        return yjse1;
//    }
//
//    /**
//     * Sets the value of the yjse1 property.
//     *
//     */
//    public void setYjse1(double value) {
//        this.yjse1 = value;
//    }
//
//    /**
//     * Gets the value of the ybtse property.
//     *
//     */
//    public double getYbtse() {
//        return ybtse;
//    }
//
//    /**
//     * Sets the value of the ybtse property.
//     *
//     */
//    public void setYbtse(double value) {
//        this.ybtse = value;
//    }
//
//}
