//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 销项信息
 *
 * <p>Java class for xxGridlbVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="xxGridlbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ewbhxh" type="{http://www.chinatax.gov.cn/dataspec/}ewbhxh"/>
 *         &lt;element name="xsdl" type="{http://www.chinatax.gov.cn/dataspec/}xsdl"/>
 *         &lt;element name="dj2" type="{http://www.chinatax.gov.cn/dataspec/}dj2"/>
 *         &lt;element name="sdsr" type="{http://www.chinatax.gov.cn/dataspec/}sdsr"/>
 *         &lt;element name="bzsdjwfy" type="{http://www.chinatax.gov.cn/dataspec/}bzsdjwfy"/>
 *         &lt;element name="ysjwfy" type="{http://www.chinatax.gov.cn/dataspec/}ysjwfy"/>
 *         &lt;element name="deslhyzl" type="{http://www.chinatax.gov.cn/dataspec/}deslhyzl"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xxGridlbVO", propOrder = {
    "ewbhxh",
    "xsdl",
    "dj2",
    "sdsr",
    "bzsdjwfy",
    "ysjwfy",
    "deslhyzl"
})
public class XxGridlbVO {

    protected long ewbhxh;
    protected double xsdl;
    protected double dj2;
    protected double sdsr;
    protected double bzsdjwfy;
    protected double ysjwfy;
    protected double deslhyzl;

    /**
     * Gets the value of the ewbhxh property.
     *
     */
    public long getEwbhxh() {
        return ewbhxh;
    }

    /**
     * Sets the value of the ewbhxh property.
     *
     */
    public void setEwbhxh(long value) {
        this.ewbhxh = value;
    }

    /**
     * Gets the value of the xsdl property.
     *
     */
    public double getXsdl() {
        return xsdl;
    }

    /**
     * Sets the value of the xsdl property.
     *
     */
    public void setXsdl(double value) {
        this.xsdl = value;
    }

    /**
     * Gets the value of the dj2 property.
     *
     */
    public double getDj2() {
        return dj2;
    }

    /**
     * Sets the value of the dj2 property.
     *
     */
    public void setDj2(double value) {
        this.dj2 = value;
    }

    /**
     * Gets the value of the sdsr property.
     *
     */
    public double getSdsr() {
        return sdsr;
    }

    /**
     * Sets the value of the sdsr property.
     *
     */
    public void setSdsr(double value) {
        this.sdsr = value;
    }

    /**
     * Gets the value of the bzsdjwfy property.
     *
     */
    public double getBzsdjwfy() {
        return bzsdjwfy;
    }

    /**
     * Sets the value of the bzsdjwfy property.
     *
     */
    public void setBzsdjwfy(double value) {
        this.bzsdjwfy = value;
    }

    /**
     * Gets the value of the ysjwfy property.
     *
     */
    public double getYsjwfy() {
        return ysjwfy;
    }

    /**
     * Sets the value of the ysjwfy property.
     *
     */
    public void setYsjwfy(double value) {
        this.ysjwfy = value;
    }

    /**
     * Gets the value of the deslhyzl property.
     *
     */
    public double getDeslhyzl() {
        return deslhyzl;
    }

    /**
     * Sets the value of the deslhyzl property.
     *
     */
    public void setDeslhyzl(double value) {
        this.deslhyzl = value;
    }

}
