package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2015.08.28 at 06:10:39 PM CST
////
//
//
//package com.example.cloud.server.common.vo.xgm.sbxx.sjgt3.zzsxgm;
//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * 征收子目GridlbVO
// *
// * <p>Java class for zszmGridlbVO complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="zszmGridlbVO">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="zspmDm" type="{http://www.chinatax.gov.cn/dataspec/}zspmDm" minOccurs="0"/>
// *         &lt;element name="zszmDm" type="{http://www.chinatax.gov.cn/dataspec/}zszmDm" minOccurs="0"/>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// *
// *
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "zszmGridlbVO", propOrder = {
//    "zspmDm",
//    "zszmDm"
//})
//public class ZszmGridlbVO {
//
//    protected String zspmDm;
//    protected String zszmDm;
//
//    /**
//     * Gets the value of the zspmDm property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getZspmDm() {
//        return zspmDm;
//    }
//
//    /**
//     * Sets the value of the zspmDm property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setZspmDm(String value) {
//        this.zspmDm = value;
//    }
//
//    /**
//     * Gets the value of the zszmDm property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getZszmDm() {
//        return zszmDm;
//    }
//
//    /**
//     * Sets the value of the zszmDm property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setZszmDm(String value) {
//        this.zszmDm = value;
//    }
//
//}
