//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * 《增值税减免税申报明细表》
 *
 * <p>Java class for zzsjmssbmxb complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="zzsjmssbmxb">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zzsjmssbmxbjsxmGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="zzsjmssbmxbjsxmGridlbVO" type="{http://www.chinatax.gov.cn/dataspec/}zzsjmssbmxbjsxmGridlbVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="zzsjmssbmxbmsxmGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="zzsjmssbmxbmsxmGridlbVO" type="{http://www.chinatax.gov.cn/dataspec/}zzsjmssbmxbmsxmGridlbVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zzsjmssbmxb", propOrder = {
    "zzsjmssbmxbjsxmGrid",
    "zzsjmssbmxbmsxmGrid"
})
@XmlSeeAlso({
    Zzsjmssbmxb.class
})
public class Zzsjmssbmxb {

    @XmlElement(required = true)
    protected ZzsjmssbmxbjsxmGrid zzsjmssbmxbjsxmGrid;
    @XmlElement(required = true)
    protected ZzsjmssbmxbmsxmGrid zzsjmssbmxbmsxmGrid;

    /**
     * Gets the value of the zzsjmssbmxbjsxmGrid property.
     *
     * @return
     *     possible object is
     *     {@link ZzsjmssbmxbjsxmGrid }
     *
     */
    public ZzsjmssbmxbjsxmGrid getZzsjmssbmxbjsxmGrid() {
        return zzsjmssbmxbjsxmGrid;
    }

    /**
     * Sets the value of the zzsjmssbmxbjsxmGrid property.
     *
     * @param value
     *     allowed object is
     *     {@link ZzsjmssbmxbjsxmGrid }
     *
     */
    public void setZzsjmssbmxbjsxmGrid(ZzsjmssbmxbjsxmGrid value) {
        this.zzsjmssbmxbjsxmGrid = value;
    }

    /**
     * Gets the value of the zzsjmssbmxbmsxmGrid property.
     *
     * @return
     *     possible object is
     *     {@link ZzsjmssbmxbmsxmGrid }
     *
     */
    public ZzsjmssbmxbmsxmGrid getZzsjmssbmxbmsxmGrid() {
        return zzsjmssbmxbmsxmGrid;
    }

    /**
     * Sets the value of the zzsjmssbmxbmsxmGrid property.
     *
     * @param value
     *     allowed object is
     *     {@link ZzsjmssbmxbmsxmGrid }
     *
     */
    public void setZzsjmssbmxbmsxmGrid(ZzsjmssbmxbmsxmGrid value) {
        this.zzsjmssbmxbmsxmGrid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="zzsjmssbmxbjsxmGridlbVO" type="{http://www.chinatax.gov.cn/dataspec/}zzsjmssbmxbjsxmGridlbVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zzsjmssbmxbjsxmGridlbVO"
    })
    public static class ZzsjmssbmxbjsxmGrid {

        @XmlElement(required = true)
        protected List<ZzsjmssbmxbjsxmGridlbVO> zzsjmssbmxbjsxmGridlbVO;

        /**
         * Gets the value of the zzsjmssbmxbjsxmGridlbVO property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the zzsjmssbmxbjsxmGridlbVO property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getZzsjmssbmxbjsxmGridlbVO().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ZzsjmssbmxbjsxmGridlbVO }
         *
         *
         */
        public List<ZzsjmssbmxbjsxmGridlbVO> getZzsjmssbmxbjsxmGridlbVO() {
            if (zzsjmssbmxbjsxmGridlbVO == null) {
                zzsjmssbmxbjsxmGridlbVO = new ArrayList<ZzsjmssbmxbjsxmGridlbVO>();
            }
            return this.zzsjmssbmxbjsxmGridlbVO;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="zzsjmssbmxbmsxmGridlbVO" type="{http://www.chinatax.gov.cn/dataspec/}zzsjmssbmxbmsxmGridlbVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zzsjmssbmxbmsxmGridlbVO"
    })
    public static class ZzsjmssbmxbmsxmGrid {

        @XmlElement(required = true)
        protected List<ZzsjmssbmxbmsxmGridlbVO> zzsjmssbmxbmsxmGridlbVO;

        /**
         * Gets the value of the zzsjmssbmxbmsxmGridlbVO property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the zzsjmssbmxbmsxmGridlbVO property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getZzsjmssbmxbmsxmGridlbVO().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ZzsjmssbmxbmsxmGridlbVO }
         *
         *
         */
        public List<ZzsjmssbmxbmsxmGridlbVO> getZzsjmssbmxbmsxmGridlbVO() {
            if (zzsjmssbmxbmsxmGridlbVO == null) {
                zzsjmssbmxbmsxmGridlbVO = new ArrayList<ZzsjmssbmxbmsxmGridlbVO>();
            }
            return this.zzsjmssbmxbmsxmGridlbVO;
        }

    }

}
