//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 增值税减免税申报明细表减税项目Grid列表VO
 *
 * <p>Java class for zzsjmssbmxbjsxmGridlbVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="zzsjmssbmxbjsxmGridlbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ewbhxh" type="{http://www.chinatax.gov.cn/dataspec/}ewbhxh" minOccurs="0"/>
 *         &lt;element name="hmc" type="{http://www.chinatax.gov.cn/dataspec/}hmc" minOccurs="0"/>
 *         &lt;element name="qcye" type="{http://www.chinatax.gov.cn/dataspec/}se" minOccurs="0"/>
 *         &lt;element name="bqfse" type="{http://www.chinatax.gov.cn/dataspec/}se" minOccurs="0"/>
 *         &lt;element name="bqydjse" type="{http://www.chinatax.gov.cn/dataspec/}se" minOccurs="0"/>
 *         &lt;element name="bqsjdjse" type="{http://www.chinatax.gov.cn/dataspec/}se" minOccurs="0"/>
 *         &lt;element name="qmye" type="{http://www.chinatax.gov.cn/dataspec/}se" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zzsjmssbmxbjsxmGridlbVO", propOrder = {
    "ewbhxh",
    "hmc",
    "qcye",
    "bqfse",
    "bqydjse",
    "bqsjdjse",
    "qmye"
})
public class ZzsjmssbmxbjsxmGridlbVO {

    protected Long ewbhxh;
    protected String hmc;
    protected Double qcye;
    protected Double bqfse;
    protected Double bqydjse;
    protected Double bqsjdjse;
    protected Double qmye;

    /**
     * Gets the value of the ewbhxh property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getEwbhxh() {
        return ewbhxh;
    }

    /**
     * Sets the value of the ewbhxh property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setEwbhxh(Long value) {
        this.ewbhxh = value;
    }

    /**
     * Gets the value of the hmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHmc() {
        return hmc;
    }

    /**
     * Sets the value of the hmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHmc(String value) {
        this.hmc = value;
    }

    /**
     * Gets the value of the qcye property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getQcye() {
        return qcye;
    }

    /**
     * Sets the value of the qcye property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setQcye(Double value) {
        this.qcye = value;
    }

    /**
     * Gets the value of the bqfse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getBqfse() {
        return bqfse;
    }

    /**
     * Sets the value of the bqfse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setBqfse(Double value) {
        this.bqfse = value;
    }

    /**
     * Gets the value of the bqydjse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getBqydjse() {
        return bqydjse;
    }

    /**
     * Sets the value of the bqydjse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setBqydjse(Double value) {
        this.bqydjse = value;
    }

    /**
     * Gets the value of the bqsjdjse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getBqsjdjse() {
        return bqsjdjse;
    }

    /**
     * Sets the value of the bqsjdjse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setBqsjdjse(Double value) {
        this.bqsjdjse = value;
    }

    /**
     * Gets the value of the qmye property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getQmye() {
        return qmye;
    }

    /**
     * Sets the value of the qmye property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setQmye(Double value) {
        this.qmye = value;
    }

}
