//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 增值税减免税申报明细表免税项目Grid列表VO
 *
 * <p>Java class for zzsjmssbmxbmsxmGridlbVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="zzsjmssbmxbmsxmGridlbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ewbhxh" type="{http://www.chinatax.gov.cn/dataspec/}ewbhxh" minOccurs="0"/>
 *         &lt;element name="hmc" type="{http://www.chinatax.gov.cn/dataspec/}hmc" minOccurs="0"/>
 *         &lt;element name="mzzzsxmxse" type="{http://www.chinatax.gov.cn/dataspec/}se" minOccurs="0"/>
 *         &lt;element name="bqsjkcje" type="{http://www.chinatax.gov.cn/dataspec/}se" minOccurs="0"/>
 *         &lt;element name="kchmsxse" type="{http://www.chinatax.gov.cn/dataspec/}se" minOccurs="0"/>
 *         &lt;element name="msxsedyjxse" type="{http://www.chinatax.gov.cn/dataspec/}se" minOccurs="0"/>
 *         &lt;element name="mse" type="{http://www.chinatax.gov.cn/dataspec/}se" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zzsjmssbmxbmsxmGridlbVO", propOrder = {
    "ewbhxh",
    "hmc",
    "mzzzsxmxse",
    "bqsjkcje",
    "kchmsxse",
    "msxsedyjxse",
    "mse"
})
public class ZzsjmssbmxbmsxmGridlbVO {

    protected Long ewbhxh;
    protected String hmc;
    protected Double mzzzsxmxse;
    protected Double bqsjkcje;
    protected Double kchmsxse;
    protected Double msxsedyjxse;
    protected Double mse;

    /**
     * Gets the value of the ewbhxh property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getEwbhxh() {
        return ewbhxh;
    }

    /**
     * Sets the value of the ewbhxh property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setEwbhxh(Long value) {
        this.ewbhxh = value;
    }

    /**
     * Gets the value of the hmc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHmc() {
        return hmc;
    }

    /**
     * Sets the value of the hmc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHmc(String value) {
        this.hmc = value;
    }

    /**
     * Gets the value of the mzzzsxmxse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getMzzzsxmxse() {
        return mzzzsxmxse;
    }

    /**
     * Sets the value of the mzzzsxmxse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setMzzzsxmxse(Double value) {
        this.mzzzsxmxse = value;
    }

    /**
     * Gets the value of the bqsjkcje property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getBqsjkcje() {
        return bqsjkcje;
    }

    /**
     * Sets the value of the bqsjkcje property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setBqsjkcje(Double value) {
        this.bqsjkcje = value;
    }

    /**
     * Gets the value of the kchmsxse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getKchmsxse() {
        return kchmsxse;
    }

    /**
     * Sets the value of the kchmsxse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setKchmsxse(Double value) {
        this.kchmsxse = value;
    }

    /**
     * Gets the value of the msxsedyjxse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getMsxsedyjxse() {
        return msxsedyjxse;
    }

    /**
     * Sets the value of the msxsedyjxse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setMsxsedyjxse(Double value) {
        this.msxsedyjxse = value;
    }

    /**
     * Gets the value of the mse property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getMse() {
        return mse;
    }

    /**
     * Sets the value of the mse property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setMse(Double value) {
        this.mse = value;
    }

}
