//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 《增值税减免税申报明细表》业务报文
 *
 * <p>Java class for zzsjmssbmxbywbw complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="zzsjmssbmxbywbw">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}taxDoc">
 *       &lt;sequence>
 *         &lt;element name="zzsjmssbmxb">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}zzsjmssbmxb">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zzsjmssbmxbywbw", propOrder = {
    "zzsjmssbmxb"
})
public class Zzsjmssbmxbywbw
    extends TaxDoc {

    @XmlElement(required = true)
    protected Zzsjmssbmxb zzsjmssbmxb;

    /**
     * Gets the value of the zzsjmssbmxb property.
     *
     * @return
     *     possible object is
     *     {@link Zzsjmssbmxb }
     *
     */
    public Zzsjmssbmxb getZzsjmssbmxb() {
        return zzsjmssbmxb;
    }

    /**
     * Sets the value of the zzsjmssbmxb property.
     *
     * @param value
     *     allowed object is
     *     {@link Zzsjmssbmxb }
     *
     */
    public void setZzsjmssbmxb(Zzsjmssbmxb value) {
        this.zzsjmssbmxb = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}zzsjmssbmxb">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Zzsjmssbmxb
        extends com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm.Zzsjmssbmxb
    {


    }

}
