//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 《增值税纳税申报表（适用小规模纳税人）》
 *
 * <p>Java class for zzssyyxgmnsr complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="zzssyyxgmnsr">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sbbhead" type="{http://www.chinatax.gov.cn/dataspec/}sbbheadkz1VO"/>
 *         &lt;element name="zzsxgmGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="4" minOccurs="4">
 *                   &lt;element name="zzsxgmGridlb" type="{http://www.chinatax.gov.cn/dataspec/}zzsxgmGridlbVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="slxxForm" type="{http://www.chinatax.gov.cn/dataspec/}slxxForm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zzssyyxgmnsr", propOrder = {
    "sbbhead",
    "zzsxgmGrid",
    "slxxForm"
})
@XmlRootElement(name = "zzssyyxgmnsr")
public class Zzssyyxgmnsr {

    @XmlElement(required = true)
    protected Sbbheadkz1VO sbbhead;
    @XmlElement(required = true)
    protected ZzsxgmGrid zzsxgmGrid;
    @XmlElement(required = true)
    protected SlxxForm slxxForm;

    /**
     * Gets the value of the sbbhead property.
     *
     * @return
     *     possible object is
     *     {@link Sbbheadkz1VO }
     *
     */
    public Sbbheadkz1VO getSbbhead() {
        return sbbhead;
    }

    /**
     * Sets the value of the sbbhead property.
     *
     * @param value
     *     allowed object is
     *     {@link Sbbheadkz1VO }
     *
     */
    public void setSbbhead(Sbbheadkz1VO value) {
        this.sbbhead = value;
    }

    /**
     * Gets the value of the zzsxgmGrid property.
     *
     * @return
     *     possible object is
     *     {@link ZzsxgmGrid }
     *
     */
    public ZzsxgmGrid getZzsxgmGrid() {
        return zzsxgmGrid;
    }

    /**
     * Sets the value of the zzsxgmGrid property.
     *
     * @param value
     *     allowed object is
     *     {@link ZzsxgmGrid }
     *
     */
    public void setZzsxgmGrid(ZzsxgmGrid value) {
        this.zzsxgmGrid = value;
    }

    /**
     * Gets the value of the slxxForm property.
     *
     * @return
     *     possible object is
     *     {@link SlxxForm }
     *
     */
    public SlxxForm getSlxxForm() {
        return slxxForm;
    }

    /**
     * Sets the value of the slxxForm property.
     *
     * @param value
     *     allowed object is
     *     {@link SlxxForm }
     *
     */
    public void setSlxxForm(SlxxForm value) {
        this.slxxForm = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="4" minOccurs="4">
     *         &lt;element name="zzsxgmGridlb" type="{http://www.chinatax.gov.cn/dataspec/}zzsxgmGridlbVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zzsxgmGridlb"
    })
    public static class ZzsxgmGrid {

        @XmlElement(required = true)
        protected List<ZzsxgmGridlbVO> zzsxgmGridlb;

        /**
         * Gets the value of the zzsxgmGridlb property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the zzsxgmGridlb property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getZzsxgmGridlb().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ZzsxgmGridlbVO }
         *
         *
         */
        public List<ZzsxgmGridlbVO> getZzsxgmGridlb() {
            if (zzsxgmGridlb == null) {
                zzsxgmGridlb = new ArrayList<ZzsxgmGridlbVO>();
            }
            return this.zzsxgmGridlb;
        }

    }

}
