//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 《增值税纳税申报表（适用小规模纳税人）》业务报文
 *
 * <p>Java class for zzssyyxgmnsrywbw complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="zzssyyxgmnsrywbw">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}taxDoc">
 *       &lt;sequence>
 *         &lt;element name="zzssyyxgmnsr" type="{http://www.chinatax.gov.cn/dataspec/}zzssyyxgmnsr"/>
 *         &lt;element name="zzsxgmflzl" type="{http://www.chinatax.gov.cn/dataspec/}zzsxgmflzl" minOccurs="0"/>
 *         &lt;element name="zzsxgmflzlsedjqkb" type="{http://www.chinatax.gov.cn/dataspec/}zzsxgmflzlsedjqkb" minOccurs="0"/>
 *         &lt;element name="jdclscqyxsmxb" type="{http://www.chinatax.gov.cn/dataspec/}jdclscqyxsmxb" minOccurs="0"/>
 *         &lt;element name="jdcxstyfpqdb" type="{http://www.chinatax.gov.cn/dataspec/}jdcxstyfpqd" minOccurs="0"/>
 *         &lt;element name="dlqyzzsxxsehjxsecdd" type="{http://www.chinatax.gov.cn/dataspec/}dlqyzzsxxsehjxsecdd" minOccurs="0"/>
 *         &lt;element name="zzsxgmfjssb" type="{http://www.chinatax.gov.cn/dataspec/}zzsxgmfjssb" minOccurs="0"/>
 *         &lt;element name="zzsjmssbmxb" type="{http://www.chinatax.gov.cn/dataspec/}zzsjmssbmxb" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zzssyyxgmnsrywbw", propOrder = {
    "zzssyyxgmnsr",
    "zzsxgmflzl",
    "zzsxgmflzlsedjqkb",
    "jdclscqyxsmxb",
    "jdcxstyfpqdb",
    "dlqyzzsxxsehjxsecdd",
    "zzsxgmfjssb",
    "zzsjmssbmxb"
})
public class Zzssyyxgmnsrywbw
    extends TaxDoc {

    @XmlElement(required = true)
    protected Zzssyyxgmnsr zzssyyxgmnsr;
    protected Zzsxgmflzl zzsxgmflzl;
    protected Zzsxgmflzlsedjqkb zzsxgmflzlsedjqkb;
    protected Jdclscqyxsmxb jdclscqyxsmxb;
    protected Jdcxstyfpqd jdcxstyfpqdb;
    protected Dlqyzzsxxsehjxsecdd dlqyzzsxxsehjxsecdd;
    protected Zzsxgmfjssb zzsxgmfjssb;
    protected Zzsjmssbmxb zzsjmssbmxb;

    /**
     * Gets the value of the zzssyyxgmnsr property.
     *
     * @return
     *     possible object is
     *     {@link Zzssyyxgmnsr }
     *
     */
    public Zzssyyxgmnsr getZzssyyxgmnsr() {
        return zzssyyxgmnsr;
    }

    /**
     * Sets the value of the zzssyyxgmnsr property.
     *
     * @param value
     *     allowed object is
     *     {@link Zzssyyxgmnsr }
     *
     */
    public void setZzssyyxgmnsr(Zzssyyxgmnsr value) {
        this.zzssyyxgmnsr = value;
    }

    /**
     * Gets the value of the zzsxgmflzl property.
     *
     * @return
     *     possible object is
     *     {@link Zzsxgmflzl }
     *
     */
    public Zzsxgmflzl getZzsxgmflzl() {
        return zzsxgmflzl;
    }

    /**
     * Sets the value of the zzsxgmflzl property.
     *
     * @param value
     *     allowed object is
     *     {@link Zzsxgmflzl }
     *
     */
    public void setZzsxgmflzl(Zzsxgmflzl value) {
        this.zzsxgmflzl = value;
    }

    /**
     * Gets the value of the zzsxgmflzlsedjqkb property.
     *
     * @return
     *     possible object is
     *     {@link Zzsxgmflzlsedjqkb }
     *
     */
    public Zzsxgmflzlsedjqkb getZzsxgmflzlsedjqkb() {
        return zzsxgmflzlsedjqkb;
    }

    /**
     * Sets the value of the zzsxgmflzlsedjqkb property.
     *
     * @param value
     *     allowed object is
     *     {@link Zzsxgmflzlsedjqkb }
     *
     */
    public void setZzsxgmflzlsedjqkb(Zzsxgmflzlsedjqkb value) {
        this.zzsxgmflzlsedjqkb = value;
    }

    /**
     * Gets the value of the jdclscqyxsmxb property.
     *
     * @return
     *     possible object is
     *     {@link Jdclscqyxsmxb }
     *
     */
    public Jdclscqyxsmxb getJdclscqyxsmxb() {
        return jdclscqyxsmxb;
    }

    /**
     * Sets the value of the jdclscqyxsmxb property.
     *
     * @param value
     *     allowed object is
     *     {@link Jdclscqyxsmxb }
     *
     */
    public void setJdclscqyxsmxb(Jdclscqyxsmxb value) {
        this.jdclscqyxsmxb = value;
    }

    /**
     * Gets the value of the jdcxstyfpqdb property.
     *
     * @return
     *     possible object is
     *     {@link Jdcxstyfpqd }
     *
     */
    public Jdcxstyfpqd getJdcxstyfpqdb() {
        return jdcxstyfpqdb;
    }

    /**
     * Sets the value of the jdcxstyfpqdb property.
     *
     * @param value
     *     allowed object is
     *     {@link Jdcxstyfpqd }
     *
     */
    public void setJdcxstyfpqdb(Jdcxstyfpqd value) {
        this.jdcxstyfpqdb = value;
    }

    /**
     * Gets the value of the dlqyzzsxxsehjxsecdd property.
     *
     * @return
     *     possible object is
     *     {@link Dlqyzzsxxsehjxsecdd }
     *
     */
    public Dlqyzzsxxsehjxsecdd getDlqyzzsxxsehjxsecdd() {
        return dlqyzzsxxsehjxsecdd;
    }

    /**
     * Sets the value of the dlqyzzsxxsehjxsecdd property.
     *
     * @param value
     *     allowed object is
     *     {@link Dlqyzzsxxsehjxsecdd }
     *
     */
    public void setDlqyzzsxxsehjxsecdd(Dlqyzzsxxsehjxsecdd value) {
        this.dlqyzzsxxsehjxsecdd = value;
    }

    /**
     * Gets the value of the zzsxgmfjssb property.
     *
     * @return
     *     possible object is
     *     {@link Zzsxgmfjssb }
     *
     */
    public Zzsxgmfjssb getZzsxgmfjssb() {
        return zzsxgmfjssb;
    }

    /**
     * Sets the value of the zzsxgmfjssb property.
     *
     * @param value
     *     allowed object is
     *     {@link Zzsxgmfjssb }
     *
     */
    public void setZzsxgmfjssb(Zzsxgmfjssb value) {
        this.zzsxgmfjssb = value;
    }

    /**
     * Gets the value of the zzsjmssbmxb property.
     *
     * @return
     *     possible object is
     *     {@link Zzsjmssbmxb }
     *
     */
    public Zzsjmssbmxb getZzsjmssbmxb() {
        return zzsjmssbmxb;
    }

    /**
     * Sets the value of the zzsjmssbmxb property.
     *
     * @param value
     *     allowed object is
     *     {@link Zzsjmssbmxb }
     *
     */
    public void setZzsjmssbmxb(Zzsjmssbmxb value) {
        this.zzsjmssbmxb = value;
    }

}
