//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 《增值税纳税申报表（小规模纳税人适用）附列资料（税额抵减情况表）》业务报文
 *
 * <p>Java class for zzsxgmflzlsedjqkbywbw complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="zzsxgmflzlsedjqkbywbw">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}taxDoc">
 *       &lt;sequence>
 *         &lt;element name="zzsxgmflzlsedjqkb" type="{http://www.chinatax.gov.cn/dataspec/}zzsxgmflzlsedjqkb"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zzsxgmflzlsedjqkbywbw", propOrder = {
    "zzsxgmflzlsedjqkb"
})
public class Zzsxgmflzlsedjqkbywbw
    extends TaxDoc {

    @XmlElement(required = true)
    protected Zzsxgmflzlsedjqkb zzsxgmflzlsedjqkb;

    /**
     * Gets the value of the zzsxgmflzlsedjqkb property.
     *
     * @return
     *     possible object is
     *     {@link Zzsxgmflzlsedjqkb }
     *
     */
    public Zzsxgmflzlsedjqkb getZzsxgmflzlsedjqkb() {
        return zzsxgmflzlsedjqkb;
    }

    /**
     * Sets the value of the zzsxgmflzlsedjqkb property.
     *
     * @param value
     *     allowed object is
     *     {@link Zzsxgmflzlsedjqkb }
     *
     */
    public void setZzsxgmflzlsedjqkb(Zzsxgmflzlsedjqkb value) {
        this.zzsxgmflzlsedjqkb = value;
    }

}
