//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.28 at 06:10:39 PM CST
//


package com.example.cloud.company.common.vo.xgm.sbxx.sjgt3.zzsxgm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 增值税纳税申报表（小规模纳税人适用）附列资料（税额抵减情况表）
 *
 * <p>Java class for zzsxgmflzlsedjqkb complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="zzsxgmflzlsedjqkb">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flzlsedjqkbGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="flzlsedjqkbGridlb" type="{http://www.chinatax.gov.cn/dataspec/}flzlsedjqkbGridlbVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zzsxgmflzlsedjqkb", propOrder = {
    "flzlsedjqkbGrid"
})
public class Zzsxgmflzlsedjqkb {

    @XmlElement(required = true)
    protected FlzlsedjqkbGrid flzlsedjqkbGrid;

    /**
     * Gets the value of the flzlsedjqkbGrid property.
     *
     * @return
     *     possible object is
     *     {@link FlzlsedjqkbGrid }
     *
     */
    public FlzlsedjqkbGrid getFlzlsedjqkbGrid() {
        return flzlsedjqkbGrid;
    }

    /**
     * Sets the value of the flzlsedjqkbGrid property.
     *
     * @param value
     *     allowed object is
     *     {@link FlzlsedjqkbGrid }
     *
     */
    public void setFlzlsedjqkbGrid(FlzlsedjqkbGrid value) {
        this.flzlsedjqkbGrid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="flzlsedjqkbGridlb" type="{http://www.chinatax.gov.cn/dataspec/}flzlsedjqkbGridlbVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flzlsedjqkbGridlb"
    })
    public static class FlzlsedjqkbGrid {

        @XmlElement(required = true)
        protected List<FlzlsedjqkbGridlbVO> flzlsedjqkbGridlb;

        /**
         * Gets the value of the flzlsedjqkbGridlb property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flzlsedjqkbGridlb property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlzlsedjqkbGridlb().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FlzlsedjqkbGridlbVO }
         *
         *
         */
        public List<FlzlsedjqkbGridlbVO> getFlzlsedjqkbGridlb() {
            if (flzlsedjqkbGridlb == null) {
                flzlsedjqkbGridlb = new ArrayList<FlzlsedjqkbGridlbVO>();
            }
            return this.flzlsedjqkbGridlb;
        }

    }

}
